---
title: "Mortality"
output: html_document
date: "2025-07-16"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

packages <- c(
  "readr",
  "dplyr",
  "purrr",
  "stringr",
  "survival",
  "survminer",
  "Publish",
  "survey",
  "DataExplorer",
  "forcats",
  "ggplot2",
  "broom",
  "gtsummary",
  "broom.helpers",
  "patchwork",
  "tidyverse",
  "nhanesA",
  "glmnet",
  "xgboost",
  "gridExtra",
  #"flextable",
  #"cairo",
  "officer"
  
)

for (pkg in packages) {
  # Check if the package is not already installed
  if (!requireNamespace(pkg, quietly = TRUE)) {
    # If not, install it from CRAN
    install.packages(pkg)
  }
  # Load the package into the R session
  library(pkg, character.only = TRUE)
}

message("All required packages are successfully installed and loaded. ✅")

```


```{r Mortality Data 1999-2016}
################
#NHANES VERSION#
################

files.mort <- c("MORTALITY-DATA/1999-2004/NHANES_1999_2000_MORT_2019_PUBLIC.dat",
                "MORTALITY-DATA/1999-2004/NHANES_2001_2002_MORT_2019_PUBLIC.dat",
                "MORTALITY-DATA/1999-2004/NHANES_2003_2004_MORT_2019_PUBLIC.dat",
                "MORTALITY-DATA/NHANES_2005_2006_MORT_2019_PUBLIC.dat",
                "MORTALITY-DATA/NHANES_2007_2008_MORT_2019_PUBLIC.dat",
                "MORTALITY-DATA/NHANES_2009_2010_MORT_2019_PUBLIC.dat",
                "MORTALITY-DATA/NHANES_2011_2012_MORT_2019_PUBLIC.dat",
                "MORTALITY-DATA/NHANES_2013_2014_MORT_2019_PUBLIC.dat",
                "MORTALITY-DATA/NHANES_2015_2016_MORT_2019_PUBLIC.dat")

years <- c(1999,2001,2003,2005,2007,2009,2011,2013,2015)
mort.table <- data.frame()
for (i in c(1:length(files.mort))){
  file <- files.mort[i]
  year <- years[i]
srvyin <- file  # full .DAT name here
#srvyout <- "NHANES_2015" # shorthand dataset name here

# Example syntax:
#srvyin <- paste("NHANES_1999_2000_MORT_2019_PUBLIC.dat")   
#srvyout <- "NHANES_1999_2000"      
# read in the fixed-width format ASCII file
dsn <- read_fwf(file=srvyin,
                col_types = "iiiiiiii",
                fwf_cols(seqn = c(1,6),
                         eligstat = c(15,15),
                         mortstat = c(16,16),
                         ucod_leading = c(17,19),
                         diabetes = c(20,20),
                         hyperten = c(21,21),
                         permth_int = c(43,45),
                         permth_exm = c(46,48)
                ),
                na = c("", ".")
)
dsn$Year <- as.integer(year)
print(year)
if (nrow(mort.table)==0){
  mort.table <- dsn
} else{
  mort.table <- mort.table %>% rbind(dsn)
}

}
# NOTE:   SEQN is the unique ID for NHANES.

# Structure and contents of data

mortality_clean <- mort.table 

```





```{r Load Data}

### This is the 2005-2016 data
df_full <-readRDS(file="~/Documents/Data/NHANES/df_nhanes_2026.01.19.Rda")
table(df_full$Year)


### this is the 1999-2004 data
df_99.04 <- readRDS(file = "~/Documents/NHANES-DMDx/df_99.04.rds")


xgb_a1cfpg_model <- readRDS(file="~/Documents/NHANES-DMDx/xgb_model2_2026.02.11.rds")

dim(df_99.04)
dim(df_full)
```


```{r}
#setdiff(names(df_full),names(df_99.04))
#setdiff(names(df_99.04),names(df_full))

df_99.04$LBXGLT <- NA
col.names <- intersect(names(df_99.04),names(df_full))

df_comp <- rbind(df_99.04[,col.names],
      df_full[,col.names])  %>% rename(
        "BMI" = "BMXBMI",
        "pulse" = "BPXPLS",
        "wbc" = "LBXWBCSI",
        "rbc" = "LBXRBCSI",
        "hg" = "LBXHGB",
        "mcv" = "LBXMCVSI",
        "plt" = "LBXPLTSI",
        "na" = "LBXSNASI",
        "potas" = "LBXSKSI",
        "chlor" = "LBXSCLSI",
        "bicarb" = "LBXSC3SI",
        "alp"="LBXSAPSI",
        "cal"="LBXSCA",
        "alt"="LBXSATSI",
        "ast"="LBXSASSI",
        "alb"="LBXSAL",
        "tbili"="LBXSTB",
        "tprot"="LBXSTP",
        "bun"="LBXSBU",
        
        )

saveRDS(object = df_comp,file="~/Documents/NHANES-DMDx/df_comp.Rds")

```


```{r Prepping Table 1 NHANES Data}

### This is the 05-16 data (filter(!is.na(diabetes_flag) & has_a1c))
df_table <- readRDS(file="~/Documents/NHANES-DMDx/df_table.Rds")


df_full$LBXGLT %>% is.na() %>% sum()
```

```{r}

intersect(df_full$SEQN,df_table$SEQN) %>% length()
setdiff(df_full$SEQN,df_table$SEQN) %>% length()


```

```{r}


mort.seqn<-mortality_clean[mortality_clean$eligstat==1,]$seqn

```


```{r}
df_comp %>% dim()
df_comp[!df_comp$SEQN %in% setdiff(df_comp$SEQN,df_table$SEQN),] %>% dim()
df_comp[df_comp$SEQN %in% setdiff(df_comp$SEQN,df_table$SEQN),] %>% filter(!SEQN %in% mort.seqn,) %>% dim()


```

```{r Prepping Table 1 NHANES Data #2}


### This is the non-A1c subset that makes the 99-16 data
df_table.99.16 <- df_comp[df_comp$SEQN %in% setdiff(df_comp$SEQN,df_table$SEQN),]
df_table.99.16 <- df_table.99.16[df_table.99.16$SEQN %in% mort.seqn,]
df_table.99.16 <- df_table.99.16 %>% filter(is.na(LBXGLT))
df_table.99.16$Type <- "1999-2016"

table1.cols <- intersect(names(df_table),names(df_table.99.16))



df_dppos_aligned<- readRDS(file="~/Documents/NHANES-DMDx/df_dppos_aligned.rds")
df_dppos_aligned$Type <- "DPPOS"
table1.cols.2 <- intersect(names(df_dppos_aligned),table1.cols)


df_table.2 <- df_table[,table1.cols.2] %>% mutate(RIDRETH1 = case_match(RIDRETH1,
    "Non-Hispanic Black" ~ "Non-Hispanic Black",
    "Other Hispanic" ~ "Hispanic",
    "Other Race - Including Multi-Racial" ~ "Other",
    "Non-Hispanic White" ~ "Non-Hispanic White",
    "Mexican American" ~ "Hispanic",
    .default = NA
  ))
df_table.99.16.2 <- df_table.99.16[,table1.cols.2] %>% mutate(RIDRETH1 = case_match(RIDRETH1,
    "Non-Hispanic Black" ~ "Non-Hispanic Black",
    "Other Hispanic" ~ "Hispanic",
    "Other Race - Including Multi-Racial" ~ "Other",
    "Non-Hispanic White" ~ "Non-Hispanic White",
    "Mexican American" ~ "Hispanic",
    .default = NA
  ))

df_dppos_table <- df_dppos_aligned[,table1.cols.2]  %>% 
  mutate(RIDRETH1 = case_match(as.character(RIDRETH1),
    "2" ~ "Non-Hispanic Black",
    "3" ~ "Hispanic",
    "4" ~ "Other",
    "1" ~ "Non-Hispanic White",
    "3" ~ "Hispanic",
    .default = NA
  ))  %>% 
  mutate(RIAGENDR = case_match(as.character(RIAGENDR),
    "1" ~ "Male",
    "2" ~ "Female",
    .default = NA
  ))

df_table.mort <- df_table  %>% mutate(RIDRETH1 = case_match(RIDRETH1,
    "Non-Hispanic Black" ~ "Non-Hispanic Black",
    "Other Hispanic" ~ "Hispanic",
    "Other Race - Including Multi-Racial" ~ "Other",
    "Non-Hispanic White" ~ "Non-Hispanic White",
    "Mexican American" ~ "Hispanic",
    .default = NA
  )) %>% filter(SEQN %in% mort.seqn) %>% mutate(Type="2005-2016<br />Mortality Cohort") %>% select(names(df_table.2))



```




```{r}
df_dppos_table %>% filter(is.na(LBXGH) | is.na(LBXGLU) )
```


```{r}
library(htmlTable)
library(Gmisc)

table.full <- rbind(df_table.mort ,
                    df_table.2,
                    df_table.99.16.2,
                    df_dppos_table %>% filter(!is.na(LBXGH) & !is.na(LBXGLU) )) %>% 
  rename("Age"="RIDAGEYR")  %>% rename(
    # --- Demographics ---
    Gender = RIAGENDR,
    `Race/Ethnicity` = RIDRETH1,
  
    # --- Body Measures & Vitals ---
    `Waist Circumference` = BMXWAIST,
    Height = BMXHT,
    Weight = BMXWT,
    `Systolic BP` = BPXSY,
    `Diastolic_ BP` = BPXDI,
    Pulse = pulse,
    
    # --- Blood Count (CBC) ---
    `White Blood Cells` = wbc,
    `Red Blood Cells` = rbc,
    Hemoglobin = hg,
    MCV = mcv,              # Mean Corpuscular Volume
    Platelets = plt,
    
    # --- Chemistry / Electrolytes ---
    Sodium = na,            # 'na' here is Natrium (Sodium), not Missing Value
    Potassium = potas,
    Chloride = chlor,
    Bicarbonate = bicarb,
    BUN = bun,              # Blood Urea Nitrogen
    Calcium = cal,
    
    # --- Liver & Kidney Function ---
    Creatinine = LBXSCR,
    `Total Protein` = tprot,
    Albumin = alb,
    `Total Bilirubin` = tbili,
    AST = ast,              # Aspartate Aminotransferase
    ALT = alt,              # Alanine Aminotransferase
    ALP = alp,              # Alkaline Phosphatase
    
    # --- Glucose & Diabetes ---
    `2hr Glucose`=LBXGLT,
    `Fasting Glucose` = LBXGLU,
    HbA1c = LBXGH           # Glycohemoglobin
  ) 


table.full <- table.full %>% mutate(Type=case_match(Type,
    "2005-2016<br />Mortality Cohort" ~ "2005-2016<br />Mortality Cohort" ,
     "Training" ~ "2005-2014<br />Training Cohort",
      "Testing" ~ "2015-2016<br />Testing Cohort",
       "1999-2016"~ "1999-2016<br />Mortality Cohort",
       "DPPOS" ~ "DPPOS<br />Cohort")) %>%   
  mutate(Type=factor(Type,levels = c("2005-2014<br />Training Cohort",
                                           "2015-2016<br />Testing Cohort",
                                            "DPPOS<br />Cohort",
                                           "1999-2016<br />Mortality Cohort",
                                           "2005-2016<br />Mortality Cohort"
                                           ))) 
table.full %>% select(Type) %>% unique()
table.cols <- names(table.full %>% select(-Type))

# 1. Calculate the counts
n_counts <- table(table.full$Type)

# 2. Format the numbers (add commas, trim extra whitespace)
n_pretty <- format(n_counts, big.mark = ",", trim = TRUE) 

# 3. Create the new labels using HTML break tag
#    Result looks like: "Control<br>(n=10,500)"
new_labels <- paste0(names(n_counts), "<br />(n=", n_pretty, ")")

# 4. Apply these new labels back to your dataframe's factor levels
levels(table.full$Type) <- new_labels

# 5. Run your table
table.full %>% 
  getDescriptionStatsBy(by = Type,table.cols, add_total_col = FALSE) %>% 
  htmlTable(# Applies to the table body
    css.cell = "font-family: Arial !important; font-size: 9pt !important;",
    css.header = "font-family: Arial !important; font-size: 9pt !important; font-weight: bold;"
  )




```


```{r}



# # 1. Create your dataframe (example data)
# df <- head(mtcars)
# 
# # 2. Create the flextable object
# ft <- flextable(df) %>% 
#   # Set font to Arial for the entire table (header + body)
#   font(fontname = "Arial", part = "all") %>% 
#   # Set font size (Diabetes Care usually prefers 10 or 12)
#   fontsize(size = 10, part = "all") %>% 
#   # Auto-adjust column widths
#   autofit()
# 
# # 3. Save to Word
# save_as_docx(ft, path = "DiabetesCare_Table.docx")
```




```{r}


setdiff(xgb_a1cfpg_model$feature_names,names(df_comp))
setdiff(names(df_comp),xgb_a1cfpg_model$feature_names)


model.cols <- intersect(xgb_a1cfpg_model$feature_names,names(df_comp))
seqn <- df_comp$SEQN


df_comp[,model.cols]

```

```{r}

# encoding for categorical variables
# encode fit uses categorical variables from training df 
encode_fit <- function(df, cols) {
  maps <- lapply(cols, function(c) {
    v <- df[[c]]
    if (is.factor(v)) v <- as.character(v)
    levs <- sort(unique(as.character(v)))
    list(col = c, lut = setNames(seq_along(levs), levs))
  })
  names(maps) <- cols
  maps
}

# encode apply then applies this logic to any dataframe
encode_apply <- function(df, enc) {
  out <- df
  for (nm in names(enc)) {
    m <- enc[[nm]]
    v <- out[[m$col]]
    if (is.factor(v)) v <- as.character(v)
    out[[m$col]] <- unname(m$lut[as.character(v)])  # unseen variables become NA
  }
  out
}


df_ready <- df_comp[,model.cols]

cat_cols <- intersect(c("RIAGENDR","RIDRETH1"), model.cols)

if (length(cat_cols) > 0)
  {
  enc <- encode_fit(df_ready, cat_cols)
  df_ready <- encode_apply(df_ready, enc)
  }


df_comp$pred <- predict(xgb_a1cfpg_model,as.matrix(df_ready))
```









```{r}
theme.1 <- theme(axis.text=element_text(size=8),
            axis.title=element_text(size=12),
            plot.tag.position = c(0.01,0.99),
            plot.tag = element_text(size=20),
            plot.title = element_text(hjust = 0.5,size=18)) 
```


```{r}
#load('df.master-2025.02.09.Rda')
f.yes1.no0 <- function(x) if_else(x=='Yes',1,if_else(x=='No',0,NA))
# Throwing out BP reading below 20
f.na.to.0 <- function(x) if_else(is.na(x),0,if_else(x<20,0,x))
f.na.or.low <- function(x) if_else(is.na(x) | x < 20,0,1)
```

```{r}
mort.seqn<-mortality_clean[mortality_clean$eligstat==1,]$seqn

df.mort3 <- left_join(df_comp,
                      mortality_clean,by=join_by(SEQN==seqn,Year==Year)) %>% 
  mutate(sample.weight=WTMEC2YR) %>% select(-c(WTSAF2YR,WTMEC2YR,WTSAF2YR)) %>% rename(a1c=LBXGH,fpg=LBXGLU)
```



```{r}
library(maxstat)

# Find the cut-point in 'pred' that maximally separates the groups
mstat <- maxstat.test(Surv(permth_exm, as.integer(mortstat)) ~ pred,
                      data = df.mort3,
                      smethod = "LogRank")

optimal_cutoff <- mstat$estimate

min.pred <- df.mort3 %>% filter(a1c >= 6.5 | fpg >= 126 ) %>% select(pred) %>% min()

if (optimal_cutoff > min.pred){
  cat("Optimal cutoff higher than minimum predicted probability, will use minimum predicted probability")
  optimal_cutoff <- min.pred
  }


# Store the optimal cut-point value in a variable


# Print the value so you can see it
cat("Optimal Cut-off for pred:", optimal_cutoff, "\n")
```

```{r}
df.mort3 %>% filter(eligstat==1) #select(mortstat,eligstat) %>% table()
```



```{r}
prepare_survival_data <- function(input_df) {
  input_df %>%
    mutate(
      #dm_status_combined = dplyr::coalesce(dm.told.x, dm.told.y),   # keep if you still need it elsewhere

      actual_status = dplyr::case_when(
        (!is.na(a1c) & a1c >= 6.5) | (!is.na(fpg) & fpg >= 126) ~ "Diabetes",
        (!is.na(a1c) & a1c < 6.5)  | (!is.na(fpg) & fpg < 126)  ~ "No Diabetes",
        TRUE ~ NA_character_
      ),
      # ------------------------------------------------------

      event        = as.numeric(mortstat),          # 0 alive, 1 dead 
      permth_exm   = as.numeric(permth_exm),
      predicted_status = factor(ifelse(pred >= optimal_cutoff,
                                       "Predicted Diabetes",
                                       "Predicted No Diabetes")),
      actual_pred_group = interaction(actual_status, predicted_status,
                                      sep = " / ", drop = TRUE)
    ) %>%
    dplyr::filter(
      !is.na(actual_status),
      !is.na(permth_exm) & permth_exm >= 0,
      !is.na(event)
    )
}

```


```{r}


df.mo3 <- df.mort3 #rbind(office_pre_final %>% select(-c(ucod_lead)),
                #df.mort3 %>% select(-c("seqn","eligstat","hyperten","permth_int","pred","DM")))

### COMBINE COMBINE
df.mo3 %>% mutate(NAN = !is.na(pred)) %>% select(NAN,Year) %>% table()
save(df.mo3,file="files/NHANES-df.mo3_noogtt.Rda")

```



```{r}

#survival_data     <- prepare_survival_data(office_test_final)
survival_data_pre <- prepare_survival_data(df.mo3)
survival_data_pre <- survival_data_pre %>%
  mutate(predicted_status = ifelse(pred >= optimal_cutoff,
                                   "Predicted Diabetes",
                                   "Predicted No Diabetes") %>% factor())


#cat("TEST rows:", nrow(survival_data), "\n")
cat("PRE  rows:", nrow(survival_data_pre), "\n")
```


```{r}
```



```{r}

survival_data_pre %>%  ggplot() + geom_point(aes(x=fpg,y=a1c,color=actual_status))

survival_data_pre %>%  ggplot() + geom_point(aes(x=pred,y=a1c,color=actual_status))

```







```{r}
survival_data_pre %>% ggplot() + geom_histogram(aes(x = pred, fill = actual_status), position = "dodge") + scale_y_log10() 


survival_data_pre %>% ggplot() + geom_histogram(aes(x = pred, fill = as.factor(mortstat)), position = "dodge") + scale_y_log10() 
```


```{r}

library(ggplot2)
library(survminer)
library(patchwork)
library(dplyr)
library(stringr)
library(survival)


fit_actual_pre <- survfit(Surv(permth_exm, event) ~ actual_status,
                          data = survival_data_pre)

df_actual <- survminer::surv_summary(fit_actual_pre, data = survival_data_pre) %>%
  mutate(source = "Actual",
         group  = str_replace(strata, "actual_status=", ""))

fit_pred_pre <- survfit(Surv(permth_exm, event) ~ predicted_status,
                        data = survival_data_pre)

df_predicted <- survminer::surv_summary(fit_pred_pre, data = survival_data_pre) %>%
  mutate(source = "Predicted",
         group = str_replace(strata, "predicted_status=", ""))

df_combined <- bind_rows(df_actual, df_predicted)

ggplot(df_combined, aes(time, surv, color = group, linetype = source)) +
  geom_step(linewidth = 1.1) +
  labs(title = "KM Curve – 2005-2016 Mortality Data",
       x = "Time (months)",
       y = "Survival Probability",
       color = "Diabetes Group") +
  scale_color_manual(values = c("Diabetes" = "red",
                                "No Diabetes" = "blue",
                                "Predicted Diabetes" = "darkblue",
                                "Predicted No Diabetes" = "lightblue")) +
  theme_minimal(base_size = 16) +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5, size = 18),
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 13),
    legend.position = "right"
  ) +
  guides(linetype = "none") 

```

```{r}
table(survival_data_pre$actual_status, survival_data_pre$predicted_status)

interaction(survival_data_pre$actual_status, survival_data_pre$predicted_status,sep="  /  ",drop=FALSE) %>% table()

# 1. rebuild predicted_status (if you changed the cutoff) AND the combo group
survival_data_pre <- survival_data_pre %>%
  mutate(
    predicted_status   = factor(ifelse(pred >= optimal_cutoff, "Predicted Diabetes", "Predicted No Diabetes")),
    actual_pred_group  = interaction(actual_status, predicted_status,
                                     sep = " / ", drop = FALSE)  # <-- keep ALL 4 levels
  )

table(survival_data_pre$actual_status, survival_data_pre$predicted_status)

interaction(survival_data_pre$actual_status, survival_data_pre$predicted_status,sep="  /  ",drop=FALSE) %>% table()

# 2. drop empty levels only AFTER you confirm counts (optional)
# survival_data_pre$actual_pred_group <- droplevels(survival_data_pre$actual_pred_group)

# 3. refit + plot (same code as before, now you'll have 4 strata)
fit_detailed <- survfit(
  Surv(permth_exm, event) ~ actual_pred_group,
  data = survival_data_pre
)

labs   <- stringr::str_remove(names(fit_detailed$strata),
                              "^actual_pred_group=")
pal_all <- c("#D81B60", "#1B9E77", "#1F78B4", "#E6AB02")
pal    <- pal_all[seq_along(labs)]

p <- ggsurvplot(
  fit_detailed,
  data                  = survival_data_pre,
  legend.labs           = labs,
  palette               = pal,

  risk.table            = TRUE,
  risk.table.height     = 0.23,
  risk.table.fontsize   = 3,
  risk.table.y.text.col = TRUE,
  risk.table.x.text     = TRUE,     # ← show month labels on risk table

  tables.theme          = theme_cleantable(),
  pval                  = TRUE,
  pval.coord            = c(10, 0.1),
  conf.int              = FALSE,
  censor.shape          = 124,
  censor.size           = 2.5,
  break.time.by         = 50,

  ggtheme               = theme_minimal(base_size = 14),  # ← smaller overall
  title                 = "KM Curve by Actual & Predicted Status",
  xlab                  = "Time (months)",
  ylab                  = "Survival probability",
  legend                = "none"
)

# fine‑tune just the title
p$plot <- p$plot +  coord_cartesian(ylim = c(0.35, 1.0)) + 
  theme(
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5) 
  ) 

# tighten up risk‑table margins
p$table <- p$table +
  theme(
    axis.title.x = element_blank(),
    plot.margin  = margin(t = 0, r = 5.5, b = 5.5, l = 5.5),
    text         = element_text(size = 11)
  )

p



```

```{r}
table(survival_data_pre$actual_status, survival_data_pre$predicted_status)

interaction(survival_data_pre$actual_status, survival_data_pre$predicted_status,sep="  /  ",drop=FALSE) %>% table()

# 1. rebuild predicted_status (if you changed the cutoff) AND the combo group
survival_data_pre <- survival_data_pre %>%
  mutate(
    predicted_status   = factor(ifelse(pred >= optimal_cutoff, "Predicted Diabetes", "Predicted No Diabetes")),
    actual_pred_group  = interaction(actual_status, predicted_status,
                                     sep = " / ", drop = FALSE)  # <-- keep ALL 4 levels
  )

table(survival_data_pre$actual_status, survival_data_pre$predicted_status)

interaction(survival_data_pre$actual_status, survival_data_pre$predicted_status,sep="  /  ",drop=FALSE) %>% table()

# 2. drop empty levels only AFTER you confirm counts (optional)
# survival_data_pre$actual_pred_group <- droplevels(survival_data_pre$actual_pred_group)

# 3. refit + plot (same code as before, now you'll have 4 strata)
fit_detailed <- survfit(
  Surv(permth_exm, event) ~ actual_pred_group,
  data = survival_data_pre
)

labs   <- stringr::str_remove(names(fit_detailed$strata),
                              "^actual_pred_group=")
pal_all <- c("#D81B60", "#1B9E77", "#1F78B4", "#E6AB02")
pal    <- pal_all[seq_along(labs)]

names(fit_detailed$strata) <- c("DM / Predicted DM","No DM / Predicted DM","No DM / Predicted No DM")


survival_data_pre$actual_pred_group <- factor(survival_data_pre$actual_pred_group,levels=c(
  "No Diabetes / Predicted No Diabetes",
  "No Diabetes / Predicted Diabetes",
  "Diabetes / Predicted Diabetes",
  "Diabetes / Predicted No Diabetes"
  ))

cox_model <- coxph(Surv(permth_exm, mortstat) ~ actual_pred_group, 
                   data = survival_data_pre )

tbl_regression(cox_model, exponentiate = TRUE)
library(ggsurvfit)

ggsurvfit(fit_detailed,size=2) +
  labs(
    x = "Months",
    y = "Survival Probability",
    #title = "Mortality (2005-2016)",
  ) +   scale_color_manual(values = c("DM / Predicted DM" = "#D81B60",
                                "No DM / Predicted DM" = "#1B9E77",
                                "No DM / Predicted No DM" = "#1F78B4"))   +
  theme_grey() + # 🎨 Change the palette here
  #add_confidence_interval() + # Add confidence interval shading
  add_risktable()    +         # Add a risk table below the plot
  add_legend_title("Diabetes\nDiagnosis") + 
  annotate("text",x=20,y=0.8,label=paste0("HR=",round(exp(cox_model$coefficients[1]),1),"\n","p<2e-16"),color="#1B9E77") + 
  annotate("text",x=20,y=0.6,label=paste0("HR=",round(exp(cox_model$coefficients[2]),1),"\n","p<2e-16"),color="#D81B60") +theme.1;
```
```{r}
library(survey)
options(survey.lonely.psu = "adjust")
options(survey.adjust.domain.lonely = TRUE)


df.weights<- rbind( nhanes("DEMO",1999) %>% select(SEQN,SDMVSTRA,SDMVPSU,WTMEC2YR),
                     nhanes("DEMO_B",2001) %>% select(SEQN,SDMVSTRA,SDMVPSU,WTMEC2YR),
                     nhanes("DEMO_C",2003) %>% select(SEQN,SDMVSTRA,SDMVPSU,WTMEC2YR),
                  nhanes("DEMO_D",2005) %>% select(SEQN,SDMVSTRA,SDMVPSU,WTMEC2YR),
                  nhanes("DEMO_E",2007) %>% select(SEQN,SDMVSTRA,SDMVPSU,WTMEC2YR),
                  nhanes("DEMO_F",2009) %>% select(SEQN,SDMVSTRA,SDMVPSU,WTMEC2YR),
                  nhanes("DEMO_G",2011) %>% select(SEQN,SDMVSTRA,SDMVPSU,WTMEC2YR),
                  nhanes("DEMO_H",2013) %>% select(SEQN,SDMVSTRA,SDMVPSU,WTMEC2YR),
                  nhanes("DEMO_I",2015) %>% select(SEQN,SDMVSTRA,SDMVPSU,WTMEC2YR))                  



survival_data_pre.weighted<-full_join(survival_data_pre %>% mutate(SEQN = sprintf("%05d", as.integer(str_trim(SEQN)))) ,
          df.weights %>% mutate(SEQN = sprintf("%05d", as.integer(str_trim(SEQN)))) ,
          by="SEQN")  %>% drop_na(WTMEC2YR)

survival_data_pre.weighted$actual_pred_group <- droplevels(survival_data_pre.weighted$actual_pred_group) 
survival_data_pre.weighted$actual_pred_group <- relevel(survival_data_pre.weighted$actual_pred_group,"No Diabetes / Predicted No Diabetes")


# fit_detailed <- survfit(
#   Surv(permth_exm, event) ~ actual_pred_group,
#   data = survival_data_pre
# )

design.INT <- svydesign(strata=~SDMVSTRA, id=~SDMVPSU, weights=~WTMEC2YR,
                        nest=TRUE, data=survival_data_pre.weighted)

km.out<-svykm(Surv(permth_exm,event) ~ actual_pred_group, design=design.INT)


# plot(km.out,
#      xlab = "Months",
#      ylab = "Survival",
#      pars=list(lty=1:3),
#      ylim=list(c(0.4,1)))
# legend(10,0.6,levels(survival_data_pre.weighted$actual_pred_group),lty=1:3)
```


```{r Middle}



survival_data_pre.weighted <- survival_data_pre.weighted %>% 
  mutate(domain_pred= complete.cases(permth_exm) & complete.cases(event) &
                         complete.cases(actual_pred_group))

survival_data_pre.weighted$actual_pred_group <- relevel(survival_data_pre.weighted$actual_pred_group,"No Diabetes / Predicted Diabetes")

# Re-create the design to include the new domain variable
design.INT <- svydesign(strata=~SDMVSTRA, id=~SDMVPSU, weights=~WTMEC2YR,
                        nest=TRUE, data=survival_data_pre.weighted)

# Subset the design to do a domain analysis
design_pred<- subset(design.INT, domain_pred)

# Log-rank test
svylogrank(Surv(permth_exm, event) ~ actual_pred_group +  RIDAGEYR + RIAGENDR + RIDRETH1, design = design_pred)[[2]]

svycoxph(Surv(permth_exm,event) ~ actual_pred_group +  RIDAGEYR + RIAGENDR + RIDRETH1, design=design_pred)
exp(svycoxph(Surv(permth_exm,event) ~ actual_pred_group +  RIDAGEYR + RIAGENDR + RIDRETH1, design=design_pred)[[1]][1])
exp(svycoxph(Surv(permth_exm,event) ~ actual_pred_group +  RIDAGEYR + RIAGENDR + RIDRETH1, design=design_pred)[[1]][2])
hr.comp <- round(exp(svycoxph(Surv(permth_exm,event) ~ actual_pred_group +  RIDAGEYR + RIAGENDR + RIDRETH1, design=design_pred)[[1]][2]),1)
p.comp <- 0.02

survival_data_pre.weighted$actual_pred_group <- relevel(survival_data_pre.weighted$actual_pred_group,"No Diabetes / Predicted No Diabetes")

```



```{r Cox PH - Discreate - Adjusted}
survival_data_pre.weighted <- survival_data_pre.weighted %>% 
  mutate(domain_pred= complete.cases(permth_exm) & complete.cases(event) &
                         complete.cases(actual_pred_group))

# Re-create the design to include the new domain variable
design.INT <- svydesign(strata=~SDMVSTRA, id=~SDMVPSU, weights=~WTMEC2YR,
                        nest=TRUE, data=survival_data_pre.weighted)

# Subset the design to do a domain analysis
design_pred<- subset(design.INT, domain_pred)

# Log-rank test
svylogrank(Surv(permth_exm, event) ~ actual_pred_group +  RIDAGEYR + RIAGENDR + RIDRETH1, design = design_pred)[[2]]

svycoxph(Surv(permth_exm,event) ~ actual_pred_group +  RIDAGEYR + RIAGENDR + RIDRETH1, design=design_pred)
exp(svycoxph(Surv(permth_exm,event) ~ actual_pred_group +  RIDAGEYR + RIAGENDR + RIDRETH1, design=design_pred)[[1]][1])
exp(svycoxph(Surv(permth_exm,event) ~ actual_pred_group +  RIDAGEYR + RIAGENDR + RIDRETH1, design=design_pred)[[1]][2])
```



```{r Cox PH - Discrete}
# 
# survival_data_pre.weighted <- survival_data_pre.weighted %>% 
#   mutate(domain_pred= complete.cases(permth_exm) & complete.cases(event) &
#                          complete.cases(actual_pred_group))
# 
# # Re-create the design to include the new domain variable
# design.INT <- svydesign(strata=~SDMVSTRA, id=~SDMVPSU, weights=~WTMEC2YR,
#                         nest=TRUE, data=survival_data_pre.weighted)
# 
# # Subset the design to do a domain analysis
# design_pred<- subset(design.INT, domain_pred)
# 
# # Log-rank test
# svylogrank(Surv(permth_exm, event) ~ actual_pred_group, design = design_pred)[[2]]
# 
# svycoxph(Surv(permth_exm,event) ~ actual_pred_group, design=design_pred)
# exp(svycoxph(Surv(permth_exm,event) ~ actual_pred_group, design=design_pred)[[1]][1])
# exp(svycoxph(Surv(permth_exm,event) ~ actual_pred_group, design=design_pred)[[1]][2])

```


```{r Cox PH - Continuous}

# survival_data_pre.weighted <- survival_data_pre.weighted %>% 
#   mutate(domain_pred= complete.cases(permth_exm) & complete.cases(event) &
#                          complete.cases(actual_pred_group))
# 
# # Re-create the design to include the new domain variable
# design.INT <- svydesign(strata=~SDMVSTRA, id=~SDMVPSU, weights=~WTMEC2YR,
#                         nest=TRUE, data=survival_data_pre.weighted)
# 
# # Subset the design to do a domain analysis
# design_pred<- subset(design.INT, domain_pred)
# 
# # Log-rank test
# svylogrank(Surv(permth_exm, event) ~ pred, design = design_pred)[[2]]
# 
# svycoxph(Surv(permth_exm,event) ~ pred, design=design_pred)
# exp(svycoxph(Surv(permth_exm,event) ~ pred, design=design_pred)[[1]][1])

```


```{r}
# This is a conceptual example as the exact transformation of svykm to
# the required survminer data frame format might need careful handling
# of confidence intervals if svykm was run with se=TRUE.
library(survey)
library(survminer)
library(dplyr)

# Assuming 'survival_data_pre.weighted' and your design.INT are already defined
# And assuming you've run the data extraction steps from the previous response
# to create 'survminer_data' correctly.

# Example of how survminer_data should look (from previous response):
if ("svykmlist" %in% class(km.out)) {
  survminer_data <- data.frame()
  for (i in seq_along(km.out)) {
    group_name <- names(km.out)[i]
    temp_data <- data.frame(
      time = km.out[[i]]$time,
      surv = km.out[[i]]$surv,
      strata = group_name
      # If km.out had se=TRUE, include lower/upper CIs
      #conf.low = km.out[[i]]$lower,
      #conf.high = km.out[[i]]$upper
    )
    survminer_data <- rbind(survminer_data, temp_data)
  }
  survminer_data$strata <- gsub("actual_pred_group=", "", survminer_data$strata)
} else {
  survminer_data <- data.frame(
    time = km.out$time,
    surv = km.out$surv,
    strata = "Overall"
    #conf.low = km.out$lower, # if se=TRUE
    #conf.high = km.out$upper # if se=TRUE
  )
}
```


```{r}
library(broom)

# 1. Extract the raw, unweighted data frame from your survey design object
raw_data <- design.INT$variables

# 2. Run a standard, unweighted survfit to calculate the actual human headcounts
unweighted_fit <- survfit(Surv(permth_exm, event) ~ actual_pred_group, data = raw_data)

# 3. Extract the time, strata, and n.risk columns
risk_counts <- broom::tidy(unweighted_fit) %>%
  select(time, strata, n.risk)

# 4. Clean up the strata names so they perfectly match your svykm output
# broom::tidy prepends the variable name, so we strip "actual_pred_group" out.
risk_counts$strata <- gsub("actual_pred_group", "", risk_counts$strata)

risk_counts %>% filter(time %% 50 ==1) %>% arrange(time)
```




```{r}
survminer_data$strata <- lapply(survminer_data$strata,function(x) gsub("Diabetes","DM",x)) %>% unlist()
survminer_data$strata <- factor(survminer_data$strata,levels=c("No DM / Predicted No DM",
                                                               "No DM / Predicted DM",
                                                               "DM / Predicted DM",
                                                               "DM / Predicted No DM"))

survminer_data$strata<-recode(survminer_data$strata,"No DM / Predicted No DM"="No DM: Predicted No DM",
                              "No DM / Predicted DM"="No DM: Predicted DM",
                              "DM / Predicted DM"="DM: Predicted DM",
                              "DM / Predicted No DM"="DM: Predicted No DM")

survminer_data$strata <- factor(survminer_data$strata,levels=c("No DM: Predicted No DM",
                                                               "No DM: Predicted DM",
                                                               "DM: Predicted DM",
                                                               "DM: Predicted No DM"))
```


```{r}


###


#####

survminer_data %>% filter(strata=="No DM: Predicted No DM") %>% filter(surv==min(surv)) %>% select(surv) %>% unique() %>% pull()
survminer_data %>% filter(strata=="No DM: Predicted DM") %>% filter(surv==min(surv)) %>% select(surv) %>% unique() %>% pull()
survminer_data %>% filter(strata=="DM: Predicted DM") %>% filter(surv==min(surv)) %>% select(surv) %>% unique() %>% pull()


survival_data_pre.weighted$actual_pred_group <- relevel(survival_data_pre.weighted$actual_pred_group,"No Diabetes / Predicted No Diabetes")

# Re-create the design to include the new domain variable
design.INT <- svydesign(strata=~SDMVSTRA, id=~SDMVPSU, weights=~WTMEC2YR,
                        nest=TRUE, data=survival_data_pre.weighted)

# Subset the design to do a domain analysis
design_pred<- subset(design.INT, domain_pred)


hr.no.dm.pred.dm <-round(exp(svycoxph(Surv(permth_exm,mortstat) ~ actual_pred_group +  RIDAGEYR + RIAGENDR + RIDRETH1, design=design_pred)[[1]][1]),1) 
hr.dm.pred.dm <-round(exp(svycoxph(Surv(permth_exm,mortstat) ~ actual_pred_group +  RIDAGEYR + RIAGENDR + RIDRETH1, design=design_pred)[[1]][2]),1) 
print(summary(svycoxph(Surv(permth_exm,event) ~ actual_pred_group +  RIDAGEYR + RIAGENDR + RIDRETH1, design=design_pred))$coefficients[, "Pr(>|z|)"][1])
print(summary(svycoxph(Surv(permth_exm,event) ~ actual_pred_group +  RIDAGEYR + RIAGENDR + RIDRETH1, design=design_pred))$coefficients[, "Pr(>|z|)"][2])

hr.1 <- hr.no.dm.pred.dm
hr.2 <- hr.dm.pred.dm

survival_data_pre.weighted$actual_pred_group <- relevel(survival_data_pre.weighted$actual_pred_group,"No Diabetes / Predicted Diabetes")

# Re-create the design to include the new domain variable
design.INT <- svydesign(strata=~SDMVSTRA, id=~SDMVPSU, weights=~WTMEC2YR,
                        nest=TRUE, data=survival_data_pre.weighted)

# Subset the design to do a domain analysis
design_pred<- subset(design.INT, domain_pred)

hr.comp <- round(exp(svycoxph(Surv(permth_exm,event) ~ actual_pred_group +  RIDAGEYR + RIAGENDR + RIDRETH1, design=design_pred)[[1]][2]),1)
print(summary(svycoxph(Surv(permth_exm,event) ~ actual_pred_group +  RIDAGEYR + RIAGENDR + RIDRETH1, design=design_pred))$coefficients[, "Pr(>|z|)"][1])
print(summary(svycoxph(Surv(permth_exm,event) ~ actual_pred_group +  RIDAGEYR + RIAGENDR + RIDRETH1, design=design_pred))$coefficients[, "Pr(>|z|)"][2])
p.comp <- 2e-16


hr.3 <- hr.comp
p.3 <- p.comp

x.1 = 260
x.2 = 265
x.3 = 255

df.seg.1 <- data.frame(x1=x.1,x2=x.1,
                       y1=survminer_data %>% filter(strata=="No DM: Predicted No DM") %>% filter(surv==min(surv)) %>% select(surv) %>% unique() %>% pull(),
                       y2=survminer_data %>% filter(strata=="No DM: Predicted DM") %>% filter(surv==min(surv)) %>% select(surv) %>% unique() %>% pull())

df.seg.2 <- data.frame(x1=x.2,x2=x.2,
                       y1=survminer_data %>% filter(strata=="No DM: Predicted No DM") %>% filter(surv==min(surv)) %>% select(surv) %>% unique() %>% pull(),
                       y2=survminer_data %>% filter(strata=="DM: Predicted DM") %>% filter(surv==min(surv)) %>% select(surv) %>% unique() %>% pull())



df.seg.3 <- data.frame(x1=x.3,x2=x.3,
                       y1=survminer_data %>% filter(strata=="No DM: Predicted DM") %>% filter(surv==min(surv)) %>% select(surv) %>% unique() %>% pull(),
                       y2=survminer_data %>% filter(strata=="DM: Predicted DM") %>% filter(surv==min(surv)) %>% select(surv) %>% unique() %>% pull())





# Correct call:
plt.km.99.16.pred<-ggsurvplot_df(
  fit = survminer_data, # Pass the data frame to 'fit'
  # The columns 'time', 'surv', 'strata' are expected to be *in* survminer_data
  # You do NOT specify them as separate arguments time="time", surv="surv", strata="strata"
  xlab = "Months",
  ylab = "Survival",
  #legend.labs = levels(survival_data_pre.weighted$actual_pred_group),
  #linetype = "strata", # This correctly tells it to use the 'strata' column for linetypes
  size=2
) + ylim(0.4,1) + theme.1 + theme_grey() +   
  scale_color_manual(values = c("No DM: Predicted No DM" = "#1F78B4",
                                "No DM: Predicted DM" = "#1B9E77",
                                "DM: Predicted DM" = "#D81B60")) +
  #add_legend_title("Diabetes\nDiagnosis") + 
  annotate("text",x=20,y=0.75,label=paste0("* HR=",hr.1,"\n","p < 2e-16"),color="#1B9E77") + 
  annotate("text",x=20,y=0.60,label=paste0("+ HR=",hr.2,"\n","p < 2e-16"),color="#D81B60") +
  annotate("text",x=20,y=0.45,label=paste0("∆ HR=",hr.3,"\n","p < ",p.3),color="black") +
  geom_segment(data=df.seg.1,aes(x=x1,xend=x2,y=y1,yend=y2),size=1) + coord_cartesian(xlim = c(0,260)) +
  annotate("text",x=df.seg.1$x1,y=1.01*max(df.seg.1$y1,df.seg.1$y2),label="*",size=5) +
  geom_segment(data=df.seg.2,aes(x=x1,xend=x2,y=y1,yend=y2),size=1) +  
  annotate("text",x=df.seg.2$x1,y=1.02*max(df.seg.2$y1,df.seg.2$y2),label="+",size=5) +
  geom_segment(data=df.seg.3,aes(x=x1,xend=x2,y=y1,yend=y2),size=1) + 
  annotate("text",x=df.seg.3$x1,y=1.03*max(df.seg.3$y1,df.seg.3$y2),label="∆",size=5) ;plot(plt.km.99.16.pred)




```


```{r}
plt.km.99.16.pred<-ggsurvplot_df(
  fit = survminer_data, # Pass the data frame to 'fit'
  # The columns 'time', 'surv', 'strata' are expected to be *in* survminer_data
  # You do NOT specify them as separate arguments time="time", surv="surv", strata="strata"
  xlab = "Months",
  ylab = "Survival",
  #legend.labs = levels(survival_data_pre.weighted$actual_pred_group),
  #linetype = "strata", # This correctly tells it to use the 'strata' column for linetypes
  size=2
) + ylim(0.4,1) + theme.1 + theme_grey() +   
  scale_color_manual(values = c("No DM: Predicted No DM" = "#1F78B4",
                                "No DM: Predicted DM" = "#1B9E77",
                                "DM: Predicted DM" = "#D81B60")) +
  #add_legend_title("Diabetes\nDiagnosis") + 
  annotate("text",x=20,y=0.75,label=paste0("* HR=",hr.1,"\n","p < 2e-16"),color="#1B9E77") + 
  annotate("text",x=20,y=0.60,label=paste0("+ HR=",hr.2,"\n","p < 2e-16"),color="#D81B60") +
  annotate("text",x=20,y=0.45,label=paste0("∆ HR=",hr.3,"\n","p < ",p.3),color="black") +
  geom_segment(data=df.seg.1,aes(x=x1,xend=x2,y=y1,yend=y2),size=1) + coord_cartesian(xlim = c(0,260)) +
  annotate("text",x=df.seg.1$x1,y=1.01*max(df.seg.1$y1,df.seg.1$y2),label="*",size=5) +
  geom_segment(data=df.seg.2,aes(x=x1,xend=x2,y=y1,yend=y2),size=1) +  
  annotate("text",x=df.seg.2$x1,y=1.02*max(df.seg.2$y1,df.seg.2$y2),label="+",size=5) +
  geom_segment(data=df.seg.3,aes(x=x1,xend=x2,y=y1,yend=y2),size=1) + 
  annotate("text",x=df.seg.3$x1,y=1.03*max(df.seg.3$y1,df.seg.3$y2),label="∆",size=5) +
  theme_bw() + theme.1 ;plot(plt.km.99.16.pred)

```
```{r}


# 5. Merge the unweighted risk counts into your existing survminer_data
survminer_data.2 <- survminer_data %>%
  # Join based on time and strata
  left_join(risk_counts, by = c("time", "strata")) %>%
  # Fill in any missing risk counts for times between events (last observation carried forward)
  group_by(strata) %>%
  arrange(time) %>%
  tidyr::fill(n.risk, .direction = "down") %>%
  ungroup() %>%
  # If time 0 is missing an n.risk, we can backfill it
  tidyr::fill(n.risk, .direction = "up")

survminer_data.2$n.event <- 0
survminer_data.2$n.censor <- 0

# 2. Force data types (survminer will also return NULL if n.risk is accidentally a character string)
survminer_data.2$time <- as.numeric(survminer_data.2$time)
survminer_data.2$surv <- as.numeric(survminer_data.2$surv)
survminer_data.2$n.risk <- as.numeric(survminer_data.2$n.risk)
survminer_data.2$strata <- as.factor(survminer_data.2$strata)
```

```{r}
# Correct call:
plt.km.99.16.pred<-ggsurvplot_df(
  fit = data.frame(survminer_data.2), # Pass the data frame to 'fit'
  # The columns 'time', 'surv', 'strata' are expected to be *in* survminer_data
  # You do NOT specify them as separate arguments time="time", surv="surv", strata="strata"
  xlab = "Months",
  ylab = "Survival",
  #legend.labs = levels(survival_data_pre.weighted$actual_pred_group),
  #linetype = "strata", # This correctly tells it to use the 'strata' column for linetypes
  size=2
) + ylim(0.4,1) + theme.1 + theme_bw() +   
  scale_color_manual(values = c("No DM: Predicted No DM" = "lightgrey",
                                "No DM: Predicted DM" = "black",
                                "DM: Predicted DM" = "darkgrey"),
                     breaks= c("No DM: Predicted No DM","DM: Predicted DM","No DM: Predicted DM")) +
  #add_legend_title("Diabetes\nDiagnosis") + 
  annotate("text",x=20,y=0.75,label=paste0("* HR=",hr.1,"\n","p < 2e-16"),color="black") + 
  annotate("text",x=20,y=0.60,label=paste0("+ HR=",hr.2,"\n","p < 2e-16"),color="black") +
  annotate("text",x=20,y=0.45,label=paste0("∆ HR=",hr.3,"\n","p < ",p.3),color="black") +
  geom_segment(data=df.seg.1,aes(x=x1,xend=x2,y=y1,yend=y2),size=1) + coord_cartesian(xlim = c(0,260)) +
  annotate("text",x=df.seg.1$x1,y=1.01*max(df.seg.1$y1,df.seg.1$y2),label="*",size=5) +
  geom_segment(data=df.seg.2,aes(x=x1,xend=x2,y=y1,yend=y2),size=1) +  
  annotate("text",x=df.seg.2$x1,y=1.02*max(df.seg.2$y1,df.seg.2$y2),label="+",size=5) +
  geom_segment(data=df.seg.3,aes(x=x1,xend=x2,y=y1,yend=y2),size=1) + 
  annotate("text",x=df.seg.3$x1,y=1.03*max(df.seg.3$y1,df.seg.3$y2),label="∆",size=5) ;plot(plt.km.99.16.pred)

```


```{r}
risk_counts$strata<-recode(risk_counts$strata,"=No Diabetes / Predicted No Diabetes"="No DM: Predicted No DM",
                              "=No Diabetes / Predicted Diabetes"="No DM: Predicted DM",
                              "=Diabetes / Predicted Diabetes"="DM: Predicted DM",
                              "=Diabetes / Predicted No Diabetes"="DM: Predicted No DM")


risk.table <- ggplot(risk_counts %>% filter(time %% 100 == 1), aes(x = time, y = strata, label = n.risk, color = strata)) +
  geom_text(size = 4.5, fontface = "bold") +
  scale_color_manual(
    values = c("No DM: Predicted No DM" = "lightgrey",
               "No DM: Predicted DM" = "black",
               "DM: Predicted DM" = "darkgrey")
  ) +
  scale_x_continuous(breaks = time, limits = c(0, 260)) +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(), # Hides the redundant x-axis text
    axis.ticks.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    legend.position = "none" # Hide the legend since the y-axis labels do the job
  );print(risk.table)
```

```{r}



```

```{r}

plt.km.05.16.actual<- readRDS(file="~/Documents/NHANES-DMDx/plt.km.05.16.actual.rds")


p.km.combo <- grid.arrange(ncol=2,
             plt.km.05.16.actual+
               theme(legend.position = "bottom")+ 
               guides(color = guide_legend(ncol = 1)) +
               labs(tag="A"),
             plt.km.99.16.pred+theme(legend.position = "bottom") + 
               guides(color = guide_legend(ncol = 1)) + 
               labs(tag="B")
             );plot(p.km.combo)


```

```{r}
ggsave("~/Dropbox/NHANES manuscript/Figure3_KMs.tiff", 
       plot = p.km.combo, 
       width = 7, 
       height = 5, 
       units = "in", 
       dpi = 300, 
       scale = 1,
       compression = "lzw")
```



```{r}

#full_join(survival_data %>% mutate(SEQN=as.integer(SEQN)),df.weights %>% mutate(SEQN=as.integer(SEQN)),join_by(SEQN==SEQN)) %>% relocate(SEQN)  %>% filter(!is.na(SDMVSTRA))

```

```{r}

# 1 = Diseases of heart (I00-I09, I11, I13, I20-I51)
# 2 = Malignant neoplasms (C00-C97)
# 3 = Chronic lower respiratory diseases (J40-J47)
# 4 = Accidents (unintentional injuries) (V01-X59, Y85-Y86)
# 5 = Cerebrovascular diseases (I60-I69)
# 6 = Alzheimer's disease (G30)
# 7 = Diabetes mellitus (E10-E14)
# 8 = Influenza and pneumonia (J09-J18)
# 9 = Nephritis, nephrotic syndrome and nephrosis (N00-N07, N17-N19, N25-N27)
# 10 = All other causes (residual)
# <NA> = Ineligible, under age 18, assumed alive, or no cause of death data available

t1 <- survival_data_pre.weighted %>% select(actual_pred_group,ucod_leading) %>% table() ; print(t1)
t1[1,] / sum(t1[1,])
t1[2,] / sum(t1[2,])
t1[3,] / sum(t1[3,])


t1 <- survival_data_pre.weighted %>% select(actual_pred_group,diabetes) %>% table(); print(t1)
t1[1,] / sum(t1[1,])
t1[2,] / sum(t1[2,])
t1[3,] / sum(t1[3,])
```

```{r Data - Leading Cause of Death}

data <- survival_data_pre.weighted %>% filter(!is.na(mortstat),!is.na(diabetes))
data$DM1 <- as.integer(data$ucod_leading==7)
data$DM2 <- data$diabetes



# Create the survey design object using your weights column
#survey_design <- svydesign(ids = ~1, data = data, weights = ~WTMEC2YR)

survey_design <-svydesign(strata=~SDMVSTRA, id=~SDMVPSU, weights=~WTMEC2YR,
                        nest=TRUE, data=data)



# Calculate the weighted mean of DM1 for each exposure group
# This gives the weighted proportion of the outcome (DM1 = 1)
weighted_props <- svyby(~DM1, ~actual_pred_group, survey_design, svymean)

rownames(weighted_props) <- lapply(rownames(weighted_props),function(x) gsub("Diabetes","DM",gsub(" \\/",":",x))) %>% unlist()
weighted_props$actual_pred_group <- factor(lapply(weighted_props$actual_pred_group,function(x) gsub("Diabetes","DM",gsub(" \\/",":\n",x))) %>% unlist())
weighted_props$actual_pred_group <- factor(weighted_props$actual_pred_group,levels=c("No DM:\n Predicted No DM" ,"No DM:\n Predicted DM","DM:\n Predicted DM"))



df.lines <- data.frame(x1=c(1,2,1),
                               x2=c(2,3,3),
                               y1=c(0.15,0.175,0.2)+0.02)
df.points <- data.frame(x1=c(1.5,2.5,2),
                               y1=0.005+c(0.15,0.175,0.2)+0.02,
                        char=c("*","***","***")) # 0.00803,3.49e-10,2.26e-10 (8e-3,4e-10,4e-10)

# Plot the results using ggplot2
plt.DMlead <- ggplot(weighted_props, aes(x = actual_pred_group, y = `DM1`)) +
  geom_bar(aes( fill = actual_pred_group),stat = "identity", position = "dodge", color = "black") +
  geom_text(aes(label = sprintf("%.2f%%", `DM1` * 100)), vjust = -0.5) +
  labs(
    title = "Diabetes as Lead Cause of Death",
    x = "Predicted Risk Group",
    y = "Proportion with Outcome"
  ) +
    scale_fill_manual(values = c("No DM:\n Predicted No DM" = "#1F78B4",
                                "No DM:\n Predicted DM" = "#1B9E77",
                                "DM:\n Predicted DM" = "#D81B60")) + 
  scale_y_continuous(labels = scales::percent_format(), limits = c(0, 0.41)) +
  theme_minimal(base_size = 14) + theme.1 + theme_grey() + 
  theme(legend.position = "none") +
  geom_segment(data=df.lines,aes(x=x1,xend=x2,y=y1,yend=y1)) + 
  geom_text(data=df.points,aes(x=x1,y=y1,label=char)); plot(plt.DMlead)
  




data$actual_pred_group <- relevel(data$actual_pred_group,"No Diabetes / Predicted No Diabetes")

survey_design <-svydesign(strata=~SDMVSTRA, id=~SDMVPSU, weights=~WTMEC2YR,
                        nest=TRUE, data=data)

# Fit the weighted logistic regression model
model <- svyglm(DM1 ~ actual_pred_group,
                design = survey_design,
                family = quasibinomial())

# View the detailed model summary
summary(model)


data$actual_pred_group <- relevel(data$actual_pred_group,"No Diabetes / Predicted Diabetes")

survey_design <-svydesign(strata=~SDMVSTRA, id=~SDMVPSU, weights=~WTMEC2YR,
                        nest=TRUE, data=data)

# Fit the weighted logistic regression model
model <- svyglm(DM1 ~ actual_pred_group,
                design = survey_design,
                family = quasibinomial())

# View the detailed model summary
summary(model)


# Exponentiate coefficients to get the Odds Ratios
odds_ratios <- exp(coef(model))

# Get the confidence intervals for the Odds Ratios
conf_intervals <- exp(confint(model))

# Combine into a final, easy-to-read table
results_table <- data.frame(
  Odds_Ratio = odds_ratios,
  CI_Lower = conf_intervals[, 1],
  CI_Upper = conf_intervals[, 2],
  p_value = summary(model)$coefficients[,4]
)

print(round(results_table, 3))

```






```{r Data All - Diabetes Contributing Factor}
# Create the survey design object using your weights column
survey_design <-svydesign(strata=~SDMVSTRA, id=~SDMVPSU, weights=~WTMEC2YR,
                        nest=TRUE, data=data)

# Calculate the weighted mean of DM2 for each exposure group
# This gives the weighted proportion of the outcome (DM2 = 1)
weighted_props <- svyby(~DM2, ~actual_pred_group, survey_design, svymean)

rownames(weighted_props) <- lapply(rownames(weighted_props),function(x) gsub("Diabetes","DM",gsub(" \\/",":",x))) %>% unlist()
weighted_props$actual_pred_group <- factor(lapply(weighted_props$actual_pred_group,function(x) gsub("Diabetes","DM",gsub(" \\/",":\n",x))) %>% unlist())
weighted_props$actual_pred_group <- factor(weighted_props$actual_pred_group,levels=c("No DM:\n Predicted No DM" ,"No DM:\n Predicted DM","DM:\n Predicted DM"))


df.lines <- data.frame(x1=c(1,2,1),
                               x2=c(2,3,3),
                               y1=0.025+c(0.325,0.35,0.375))
df.points <- data.frame(x1=c(1.5,2.5,2),
                               y1=0.03+c(0.325,0.35,0.375),
                        char=c("**","***","***")) # 0.000263, 2e-16, 2e-16 (3e-4,4e-10,4e-10)


# Plot the results using ggplot2
plt.DMcontr<-ggplot(weighted_props, aes(x = actual_pred_group, y = `DM2`)) +
  geom_bar(aes(fill = actual_pred_group),stat = "identity", position = "dodge", color = "black") +
  geom_text(aes(label = sprintf("%.2f%%", `DM2` * 100)), vjust = -0.5) +
  labs(
    title = "Diabetes as Contributing to Death",
    x = "Predicted Risk Group",
    y = "Proportion with Outcome"
  ) +
  scale_fill_manual(values = c("No DM:\n Predicted No DM" = "#1F78B4",
                                "No DM:\n Predicted DM" = "#1B9E77",
                                "DM:\n Predicted DM" = "#D81B60")) +  
  scale_y_continuous(labels = scales::percent_format(), limits = c(0, 0.41)) +
  theme_minimal(base_size = 14) + theme.1 + theme_grey() + 
  theme(legend.position = "none")  +
  geom_segment(data=df.lines,aes(x=x1,xend=x2,y=y1,yend=y1)) + 
  geom_text(data=df.points,aes(x=x1,y=y1,label=char));plot(plt.DMcontr)
  

data$actual_pred_group <- relevel(data$actual_pred_group,"No Diabetes / Predicted No Diabetes")

survey_design <-svydesign(strata=~SDMVSTRA, id=~SDMVPSU, weights=~WTMEC2YR,
                        nest=TRUE, data=data)

# Fit the weighted logistic regression model
model <- svyglm(DM2 ~ actual_pred_group,
                design = survey_design,
                family = quasibinomial())

# View the detailed model summary
summary(model)

data$actual_pred_group <- relevel(data$actual_pred_group,"No Diabetes / Predicted Diabetes")

survey_design <-svydesign(strata=~SDMVSTRA, id=~SDMVPSU, weights=~WTMEC2YR,
                        nest=TRUE, data=data)

# Fit the weighted logistic regression model
model <- svyglm(DM2 ~ actual_pred_group,
                design = survey_design,
                family = quasibinomial())

# View the detailed model summary
summary(model)



# Exponentiate coefficients to get the Odds Ratios
odds_ratios <- exp(coef(model))

# Get the confidence intervals for the Odds Ratios
conf_intervals <- exp(confint(model))

# Combine into a final, easy-to-read table
results_table <- data.frame(
  Odds_Ratio = odds_ratios,
  CI_Lower = conf_intervals[, 1],
  CI_Upper = conf_intervals[, 2],
  p_value = summary(model)$coefficients[,4]
)

print(round(results_table, 3))
```


```{r}
#install.packages("ragg")
library(ragg)
```

```{r}


g1<-grid.arrange(plt.km.99.16.pred + labs(tag="A"),
             grid.arrange(ncol=2,plt.DMlead+ labs(tag="B"),plt.DMcontr+ labs(tag="C"))
)
ggsave(plot = g1,filename = "figures/Surv-DM-cause.png",width=7,height=7,units="in")
ggsave(plot = g1,filename = "figures/4.Surv-DM-cause.bmp",width=7,height=7,units="in")
ggsave(plot = g1,filename = "figures/4.Surv-DM-cause.pdf",width=7,height=7,units="in",device=cairo_pdf)

```


```{r Data A1c & FPG - Leading Cause of Death}

data <- survival_data_pre.weighted %>% filter(!is.na(mortstat),!is.na(diabetes)) %>% drop_na(a1c,fpg)
data$DM1 <- as.integer(data$ucod_leading==7)
data$DM2 <- data$diabetes



# Create the survey design object using your weights column
survey_design <-svydesign(strata=~SDMVSTRA, id=~SDMVPSU, weights=~WTMEC2YR,
                        nest=TRUE, data=data)


# Calculate the weighted mean of DM1 for each exposure group
# This gives the weighted proportion of the outcome (DM1 = 1)
weighted_props <- svyby(~DM1, ~actual_pred_group, survey_design, svymean)

rownames(weighted_props) <- lapply(rownames(weighted_props),function(x) gsub("Diabetes","DM",x)) %>% unlist()
weighted_props$actual_pred_group <- factor(lapply(weighted_props$actual_pred_group,function(x) gsub("Diabetes","DM",x)) %>% unlist())
weighted_props$actual_pred_group <- factor(weighted_props$actual_pred_group,levels=c("No DM: Predicted No DM" ,"No DM: Predicted DM","DM: Predicted DM"))

# Plot the results using ggplot2
ggplot(weighted_props, aes(x = actual_pred_group, y = `DM1`, fill = actual_pred_group)) +
  geom_bar(stat = "identity", position = "dodge", color = "black") +
  geom_text(aes(label = sprintf("%.2f%%", `DM1` * 100)), vjust = -0.5) +
  labs(
    title = "Weighted Proportion of Outcome (DM1=1) by Risk Group",
    x = "Predicted Risk Group",
    y = "Proportion with Outcome"
  ) +
    scale_fill_manual(values = c("No DM: Predicted No DM" = "#1F78B4",
                                "No DM: Predicted DM" = "#1B9E77",
                                "DM: Predicted DM" = "#D81B60")) +  
  scale_y_continuous(labels = scales::percent_format(), limits = c(0, 0.4)) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "none")

# Fit the weighted logistic regression model
model <- svyglm(DM1 ~ actual_pred_group,
                design = survey_design,
                family = quasibinomial())

# View the detailed model summary
summary(model)


# Exponentiate coefficients to get the Odds Ratios
odds_ratios <- exp(coef(model))

# Get the confidence intervals for the Odds Ratios
conf_intervals <- exp(confint(model))

# Combine into a final, easy-to-read table
results_table <- data.frame(
  Odds_Ratio = odds_ratios,
  CI_Lower = conf_intervals[, 1],
  CI_Upper = conf_intervals[, 2],
  p_value = summary(model)$coefficients[,4]
)

print(round(results_table, 3))

```






```{r Data A1c & FPG - Diabetes Contributing Factor}
# Create the survey design object using your weights column
survey_design <-svydesign(strata=~SDMVSTRA, id=~SDMVPSU, weights=~WTMEC2YR,
                        nest=TRUE, data=data)

# Calculate the weighted mean of DM2 for each exposure group
# This gives the weighted proportion of the outcome (DM2 = 1)
weighted_props <- svyby(~DM2, ~actual_pred_group, survey_design, svymean)



rownames(weighted_props) <- lapply(rownames(weighted_props),function(x) gsub("Diabetes","DM",x)) %>% unlist()
weighted_props$actual_pred_group <- factor(lapply(weighted_props$actual_pred_group,function(x) gsub("Diabetes","DM",x)) %>% unlist())
# Plot the results using ggplot2
ggplot(weighted_props, aes(x = actual_pred_group, y = `DM2`, fill = actual_pred_group)) +
  geom_bar(stat = "identity", position = "dodge", color = "black") +
  geom_text(aes(label = sprintf("%.2f%%", `DM2` * 100)), vjust = -0.5) +
  labs(
    title = "Weighted Proportion of Outcome (DM2=1) by Risk Group",
    x = "Predicted Risk Group",
    y = "Proportion with Outcome"
  ) +
  scale_color_manual(values = c("No DM: Predicted No DM" = "#1F78B4",
                                "No DM: Predicted DM" = "#1B9E77",
                                "DM: Predicted DM" = "#D81B60")) +  
  scale_y_continuous(labels = scales::percent_format(), limits = c(0, 0.6)) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "none")

# Fit the weighted logistic regression model
model <- svyglm(DM2 ~ actual_pred_group,
                design = survey_design,
                family = quasibinomial())

# View the detailed model summary
summary(model)


# Exponentiate coefficients to get the Odds Ratios
odds_ratios <- exp(coef(model))

# Get the confidence intervals for the Odds Ratios
conf_intervals <- exp(confint(model))

# Combine into a final, easy-to-read table
results_table <- data.frame(
  Odds_Ratio = odds_ratios,
  CI_Lower = conf_intervals[, 1],
  CI_Upper = conf_intervals[, 2],
  p_value = summary(model)$coefficients[,4]
)

print(round(results_table, 3))
```



```{r}
library(maxstat)

# Find the cut-point in 'pred' that maximally separates the groups
mstat <- maxstat.test(Surv(permth_exm, event) ~ pred,
                      data = survival_data_pre,
                      smethod = "LogRank")

# Store the optimal cut-point value in a variable
optimal_cutoff <- mstat$estimate

# Print the value so you can see it
cat("Optimal Cut-off for pred:", optimal_cutoff, "\n")
```

```{r}
cox_model <- coxph(Surv(permth_exm, event) ~ predicted_status, 
                   data = survival_data_pre)

tbl_regression(cox_model, exponentiate = TRUE)
# check if identifies the best cut point (for pred)

```


```{r}
data_releveled <- survival_data_pre %>%
  mutate(
    predicted_status = fct_relevel(predicted_status, "Predicted No Diabetes")
  )

cox_model_new_ref <- coxph(Surv(permth_exm, event) ~ predicted_status, 
                           data = data_releveled)

tbl_regression(cox_model_new_ref, exponentiate = TRUE)

```


