---
title: "DmDx-Retinopathy"
output: html_document
date: "2026-01-07"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

packages <- c(
  "readr",
  "dplyr",
  "purrr",
  "stringr",
  "survival",
  "survminer",
  "Publish",
  "survey",
  "DataExplorer",
  "forcats",
  "ggplot2",
  "broom",
  "gtsummary",
  "broom.helpers",
  "patchwork",
  "tidyverse",
  "nhanesA",
  "glmnet",
  "xgboost",
  "gridExtra"
)


for (pkg in packages) {
  # Check if the package is not already installed
  if (!requireNamespace(pkg, quietly = TRUE)) {
    # If not, install it from CRAN
    install.packages(pkg)
  }
  # Load the package into the R session
  library(pkg, character.only = TRUE)
}

message("All required packages are successfully installed and loaded. ✅")

```


```{r}
load('files/df_full_2025.09.24.Rda')

df_mec <- df_full %>% filter(Year==2005) %>% select(SEQN,sample.mec.weight)

load("files/NHANES-office-test-layered_all_2026.01.08_2005test.Rda")

#office_pre <- df_full %>% filter(Year < 2005)
#office_train <- df_full %>% filter(Year > 2003, Year < 2015)
#office_test <- df_full %>% filter(Year > 2013)
#office_ext <- office_pre %>% rename(sample.weight = sample.mec.weight) %>% select(-c(sample.fasting.weight,sample.ogtt.weight))

office_test.2 <- office_test %>% left_join(df_mec,join_by(SEQN))

```


```{r}

# Install and load the package
# install.packages("nhanesA")
library(nhanesA)
library(Hmisc)

# 1. Import the Ophthalmology (Retinopathy) Exam data for 2005-2006
#retinopathy_data_05 <- nhanes('OPXRET_D')
#retinopathy_data_07 <- nhanes('OPXRET_E')


# 2. Extract and print all column names to find specific markers
retinopathy_data <- rbind(retinopathy_data_05 %>% rename(VIQ121 = VIQ141),retinopathy_data_07)

# 3. View a description of the variables directly in your browser 
# This is helpful to see what 'VIX... codes actually mean
nhanesTableVars('EXAM', 'VIX_D')

# Download Diabetes questionnaire data
diq_data_05 <- nhanes('DIQ_D')
diq_data_07 <- nhanes('DIQ_E')

diq_data <- rbind(diq_data_05,diq_data_07)

# Merge the datasets by SEQN
combined_data <- merge(retinopathy_data, diq_data, by = 'SEQN', all.x = TRUE)

# View the self-reported retinopathy column alongside graded data
# DIQ080: "Has a doctor ever told you that diabetes has affected your eyes?"
diab_ret <- combined_data[, c("SEQN", "OPDURL4","OPDUARMA", "DIQ080")]  %>% filter(!is.na(OPDUARMA))

diab_ret
```


```{r}
diab_ret %>% left_join(office_test.2,join_by(SEQN)) %>% ggplot(aes(x=a1c,y=two,color=OPDUARMA )) + geom_jitter(position=position_jitterdodge(dodge.width=0.2)) + geom_boxplot(alpha=0.9)

diab_ret %>% left_join(office_test.2,join_by(SEQN)) %>% ggplot(aes(x=a1c,y=two,color=OPDUARMA )) + geom_point() + geom_vline(xintercept = 6.5) + geom_hline(yintercept=200)

ret <- diab_ret %>% left_join(office_test.2,join_by(SEQN)) %>% filter(!is.na(sample.mec.weight))

ret$sample.mec.weight

ret %>% slice_sample(n=100000,weight_by = sample.mec.weight,replace=TRUE) %>% mutate(OGTTonly = (two >= 200 & !is.na(two)) & 
               (fpg < 126  & !is.na(fpg)) & 
               (a1c < 6.5  & !is.na(a1c)),
               
    otherDM  = (fpg >= 126 & !is.na(fpg)) | 
               (a1c >= 6.5 & !is.na(a1c)),
               
    noDM     = (two < 200  & !is.na(two)) & 
               (fpg < 126  & !is.na(fpg)) & 
               (a1c < 6.5  & !is.na(a1c)), Ret = (OPDUARMA=="Yes")) %>% 
 group_by(Ret) %>%  summarise(OGTTonly=sum(OGTTonly,na.rm=TRUE),
            otherDM = sum(otherDM,na.rm=TRUE),noDM=sum(noDM,na.rm=TRUE))  %>% t() %>% as.data.frame() %>% mutate(V3=V2/(V1+V2)) %>% rename(NoRetin=V1,Retin=V2,PercRetin=V3) %>% mutate(DM = as.factor(rownames(.)))   %>% pivot_longer(cols = c(NoRetin,Retin),values_to = "Value",names_to = "Retinopathy") %>% mutate(Retinopathy = as.factor(Retinopathy)) %>% filter(Value != 1 & Value != 0) 


ret %>% slice_sample(n=100000,weight_by = sample.mec.weight,replace=TRUE) %>% 
  mutate(OGTTonly = (two >= 200 & !is.na(two)) & 
               (fpg < 126  & !is.na(fpg)) & 
               (a1c < 6.5  & !is.na(a1c)),
               
    otherDM  = (fpg >= 126 & !is.na(fpg)) | 
               (a1c >= 6.5 & !is.na(a1c)),
               
    noDM     = (two < 200  & !is.na(two)) | 
               (fpg < 126  & !is.na(fpg)) | 
               (a1c < 6.5  & !is.na(a1c)), Ret = as.factor(OPDUARMA))  %>% select(Ret,sample.mec.weight,OGTTonly,otherDM,noDM) %>% pivot_longer(cols=c(OGTTonly,otherDM,noDM),values_to = "Value",names_to = "DM.type")  %>% filter(Value==TRUE,DM.type!="noDM") %>% glm(family="binomial",formula = Ret ~ DM.type,weights = sample.mec.weight) %>% summary() 
  # 

chisq.test(x=as.matrix(c(1519,226,8135,3448),nrow=2,ncol=2))
```


```{r}

ret %>% mutate(OGTTonly = (two >= 200 & !is.na(two)) & 
               (fpg < 126  & !is.na(fpg)) & 
               (a1c < 6.5  & !is.na(a1c)),
               
    otherDM  = (fpg >= 126 & !is.na(fpg)) | 
               (a1c >= 6.5 & !is.na(a1c)),
               
    noDM     = (two < 200  & !is.na(two)) | 
               (fpg < 126  & !is.na(fpg)) | 
               (a1c < 6.5  & !is.na(a1c))) %>% filter(otherDM==FALSE) %>% slice_sample(n=100000,weight_by = sample.mec.weight,replace=TRUE) %>% mutate(Ret = as.factor(OPDUARMA)) %>% ggplot() + geom_histogram(aes(x=Pred.SOC.Fast,y=(..count..)/tapply(..count..,..PANEL..,sum)[..PANEL..],fill=Ret),position = position_dodge()) + facet_wrap(OGTTonly~Ret)

ret %>% slice_sample(n=100000,weight_by = sample.mec.weight,replace=TRUE) %>% mutate(Ret = as.factor(OPDUARMA))%>% glm(family="binomial",formula = Ret ~ Pred.SOC.Fast,weights = sample.mec.weight) %>% summary() 
```

```{r}
optimal_cutoff <- 0.01213087 


ret.compare <- ret %>% mutate(OGTTonly = (two >= 200 & !is.na(two)) & 
               (fpg < 126  & !is.na(fpg)) & 
               (a1c < 6.5  & !is.na(a1c)),
               
    otherDM  = (fpg >= 126 & !is.na(fpg)) | 
               (a1c >= 6.5 & !is.na(a1c)),
               
    noDM     = (two < 200  & !is.na(two)) | 
               (fpg < 126  & !is.na(fpg)) | 
               (a1c < 6.5  & !is.na(a1c)))  %>% 
  mutate(Ret = as.factor(OPDUARMA)) %>% mutate(PredDM = Pred.SOC.Fast > optimal_cutoff)  %>% 
  select(PredDM,OGTTonly,Ret,sample.mec.weight) %>% 
  mutate(PredDM = ifelse(PredDM==TRUE,1,0),
         OGTTonly = ifelse(OGTTonly==TRUE,1,0),
         Ret = ifelse(Ret=="Yes",1,0))


#install.packages("survey")
library(survey)

# Create a survey design object to handle your weights
design <- svydesign(ids = ~1, weights = ~sample.mec.weight, data = ret.compare)

# Use svylogit or svychisq to compare the relationship
# To specifically compare the marginal probabilities:
svyttest(Ret ~ PredDM, design)
svyttest(Ret ~ OGTTonly, design)

```




```{r}
# Model 1: Only the "Real" test
fit_basic <- svyglm(Ret ~ OGTTonly, design = design, family = quasibinomial())

# Model 2: The "Real" test + your "Prediction"
fit_full <- svyglm(Ret ~ OGTTonly + PredDM, design = design, family = quasibinomial())

# Compare them
conflicts_prefer(stats::update)
survey:::anova.svyglm(fit_basic, fit_full)
```


```{r}
# This creates a cross-tab of the Real test vs. your Prediction
# using the survey design to see the 'population' impact
svytable(~OGTTonly + PredDM, design = design)
```

```{r}
# 1. Sensitivity of the Real Test (OGTTonly)
sens_ogtt <- svyby(~OGTTonly, ~Ret, design = design, svymean, na.rm = TRUE)

# 2. Sensitivity of the Prediction (PredDM)
sens_pred <- svyby(~PredDM, ~Ret, design = design, svymean, na.rm = TRUE)

print(sens_ogtt)
print(sens_pred)

# Create a 3-way weighted table: OGTT x PredDM x Retinopathy
discordant_table <- svytable(~OGTTonly + PredDM + Ret, design = design)

# Convert to a data frame for easier viewing
as.data.frame(discordant_table)
```


```{r}
# 1. Resolve the 'update' conflict first
library(conflicted)
conflicts_prefer(stats::update)

library(survey)
library(pROC) # install.packages("pROC") if you don't have it

# 2. Extract the weights and the outcome from your design object
# (Assuming your design object is named 'design')
weights_vec <- weights(design)
outcome_vec <- design$variables$Ret

# 3. Get the predicted probabilities from your models
# We fit the models again to ensure we have the probability vectors
fit_pred <- svyglm(Ret ~ PredDM, design = design, family = quasibinomial())
fit_ogtt <- svyglm(Ret ~ OGTTonly, design = design, family = quasibinomial())

# Generate probabilities
prob_pred <- predict(fit_pred, type = "response")
prob_ogtt <- predict(fit_ogtt, type = "response")

# 4. Create the Weighted ROC objects
roc_pred <- pROC::roc(outcome_vec, as.numeric(prob_pred), weights = sample.mec.weights)
roc_ogtt <- pROC::roc(outcome_vec, as.numeric(prob_ogtt), weights = sample.mec.weights)

# 5. Plot the comparison
plot(roc_pred, col = "blue", lwd = 3, main = "Weighted ROC Curve: Retinopathy Prediction")
plot(roc_ogtt, add = TRUE, col = "red", lwd = 3, lty = 2)

legend("bottomright", 
       legend = c(paste0("PredDM (AUC: ", round(pROC::auc(roc_pred), 3), ")"),
                  paste0("OGTTonly (AUC: ", round(pROC::auc(roc_ogtt), 3), ")")),
       col = c("blue", "red"), lwd = 3, lty = c(1, 2))

# 6. Formally test if the AUCs are significantly different
pROC::roc.test(roc_pred, roc_ogtt)
```

