---
title: "NHANES-XGBOOST-graphs"
author: "alanlhutchison"
date: "2025-02-24"
output: html_document
---


### In 2025.02.24 version, we're going to focus on taking input from NHANES-XGBOOST-generate-output
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


```{r Libraries, include=FALSE,echo=FALSE}
### PLEASE REFER TO NHANES-RMS-2024.08.06 for some additional code and checks that we deleted here for conciseness
### PLEASE REFER TO NHANES-RMS-2024.10.10 for some additional code and checks that we deleted here for conciseness

knitr::opts_chunk$set(include=FALSE, echo = FALSE, warning=FALSE,message=FALSE)
options(prType='html')


#install.packages('nhanesA')
#install.packages('foreign')
#install.packages("xgboost")
#install.packages("caret")
#install.packages("dplyr")

library(xgboost)
library(caret)
library(dplyr)
library(foreign)
library(nhanesA)
library(tidyverse)
library(gridExtra)
library(broom)
require(rms)
library(ggplot2)
library(naniar)
library(mosaic)
require(dplyr)
require(brms)
library(pROC)
library(AUC)
library(viridis)
library(Hmisc)
library(glmnet)
library(tidymodels)
library(data.table)

```

## Including Plots

You can also embed plots, for example:

```{r Load files, echo=FALSE}


dir.string <-"~/Documents/NHANES15-16/"



### Load df.master
load(paste0(dir.string,'df.master-2025.02.09.Rda'))

### Load df
load(file=paste0(dir.string,"df.2025.02.26.Rda"))



```


```{r Load files, name output files}
date.string <- "2025.03.01"
filter.string <- "all"
# filter.string <- "alb<4.1"
# filter.string <- "Cr>1"
#filter.string <- "FIB4>2"
# filter.string <- "FIB4>1.3"
# filter.string <- "Age>50"
# filter.string <- "BMI>25"
# filter.string <- "BMI>30"
# filter.string <- "BMI>35"
# filter.string <- "SBP>130"
# filter.string <- "ggt>40"
# filter.string <- "WC>100"
# filter.string <- "WC>110"



### Load office_train
load(paste0(dir.string,"NHANES-office-train-layered_",filter.string,"_",date.string,".Rda"))

### Load office_test
load(paste0(dir.string,"NHANES-office-test-layered_",filter.string,"_",date.string,".Rda"))

### Load xgb_models
load(paste0(dir.string,"NHANES-All-xgb.models_",filter.string,"_",date.string,".Rda"))




common_cols <- intersect(colnames(office_train), colnames(office_test))
df.small <- rbind(
  subset(office_train, select = common_cols), 
  subset(office_test, select = common_cols)
)

### OUTPUT FILES
file.ROCs=paste0(dir.string,"NHANES-",filter.string,"_",date.string,"-All_ROCs.bmp" )
file.importance.plots = paste0(dir.string,"NHANES-",filter.string,"_",date.string,"-ImportancePlots.bmp" )
file.dca.all = paste0(dir.string,"NHANES-",filter.string,"_",date.string,"-DCA-all.bmp" )
file.dca.fib4 = paste0(dir.string,"NHANES",filter.string,"_",date.string,"-DCA_FIB4.bmp" )

file.dca.min = paste0(dir.string,"NHANES-",filter.string,"_",date.string,"-DCA_min-set.bmp" )


#xgb_tuned.full <- load(file.xgb_tuned.full)

```





```{r}

paste("Diabetes Dx by Both:", df.small %>% filter(a1c>=6.5 & two>=200) %>% nrow()  ) 
paste("Diabetes Dx by OGTT:", df.small %>% filter(two>=200) %>% nrow() / 1 ) 
paste("Diabetes Dx by A1c:", df.small %>% filter(a1c>=6.5) %>% nrow() / 1 ) 
paste("Diabetes Dx by A1c not OGTT:", df.small %>% filter(a1c>=6.5 & two < 200) %>% nrow() / 1 ) 
paste("Diabetes Dx by OGTT not A1c:", df.small %>% filter(a1c<6.5 & two >= 200) %>% nrow() / 1 ) 

print('')
paste("Pre-Diabetes Dx by Both:", df.small %>% filter((a1c>=5.7 & a1c<6.5 )& (two<200 & two>=140)) %>% nrow() / 1 ) 
paste("Pre-Diabetes Dx by OGTT:", df.small %>% filter((two<200 & two>=140)) %>% nrow() / 1 ) 
paste("Pre-Diabetes Dx by A1c:", df.small %>% filter((a1c>=5.7 & a1c<6.5 )) %>% nrow() / 1 ) 
paste("Pre-Diabetes Dx by A1c not OGTT:", df.small %>% filter((a1c>=5.7 & a1c<6.5 ) & two < 140) %>% nrow() / 1 ) 
paste("Pre-Diabetes Dx by OGTT not A1c:", df.small %>% filter(a1c<5.7 & (two<200 & two>=140)) %>% nrow() / 1 ) 

print('')
paste("No Pre-Diabetes or Diabetes:", df.small %>% filter(a1c<5.7 & two < 140 ) %>% nrow() / 1 ) 

```



```{r}
print('Age > 60')
df.small %>% filter(Age>60,Year<2015) %>% nrow() 
df.small %>% filter(Age>60,Year>2014) %>% nrow() 

print('FIB-4 > 2.67')
df.small %>% mutate(FIB4 = Age/plt*ast/sqrt(alt)) %>% filter(FIB4>2.67,Year<2015) %>% nrow() 
df.small %>% mutate(FIB4 = Age/plt*ast/sqrt(alt)) %>% filter(Year>2014,FIB4>2.67) %>% nrow() 

print('BMI > 30')
df.small %>% mutate(BMI = Weight/(Height.Stand^2)*100*100)  %>%  filter(BMI>30,Year<2015) %>% nrow() 
df.small %>% mutate(BMI = Weight/(Height.Stand^2)*100*100)  %>%  filter(BMI>30,Year>2014) %>% nrow() 

print('SBP > 140')
df.small %>% filter(SBP>140,Year<2015) %>% nrow() 
df.small %>% filter(SBP>140,Year>2014) %>% nrow() 

print('eGFR < 60')
df.small %>% mutate(eGFR = 142 * 
                       pmin(cr/ifelse(Gender=="Male",0.9,0.7),1,na.rm=TRUE ) ^ifelse(Gender=="Male",-0.302,-0.241) *
                       pmax(cr/ifelse(Gender=="Male",0.9,0.7),1,na.rm=TRUE ) ^-1.20 *
                       0.9938 ^ Age *
                       ifelse(Gender=="Male",1,1.012)
                     )   %>% filter(eGFR < 60,Year<2015) %>% nrow()

df.small %>% mutate(eGFR = 142 * 
                       pmin(cr/ifelse(Gender=="Male",0.9,0.7),1,na.rm=TRUE ) ^ifelse(Gender=="Male",-0.302,-0.241) *
                       pmax(cr/ifelse(Gender=="Male",0.9,0.7),1,na.rm=TRUE ) ^-1.20 *
                       0.9938 ^ Age *
                       ifelse(Gender=="Male",1,1.012)
                     )   %>% filter(eGFR < 60,Year >2014) %>% nrow()


```



```{r Importance Plot}

xgb.model.full <- xgb_models$Full
df.imp <- xgb.importance(feature_names = colnames(xgb.model.full),model=xgb.model.full) %>% select(Feature,Gain)  %>% mutate(Gain=round(Gain,4)) %>% head(20) %>%
  mutate(Sum=sum(Gain)) %>%
  mutate(Feature=str_replace_all(Feature,'fpg','Fasting Plasma Glucose')) %>% 
  mutate(Feature=str_replace_all(Feature,'a1c','Hemoglobin A1c')) %>%
  mutate(Feature=str_replace_all(Feature,'tgy','Triglycerides')) %>%
  mutate(Feature=str_replace_all(Feature,'SBP','Systolic Blood Pressure')) %>%
  mutate(Feature=str_replace_all(Feature,'u.alb','Urine Albumin')) %>%
  mutate(Feature=str_replace_all(Feature,'Height.Stand','Height'))%>%
  mutate(Feature=str_replace_all(Feature,'insulin','Insulin'))%>%
  mutate(Feature=str_replace_all(Feature,'Seg.Neut.perc','% Segmented Neutrophils'))%>%
  mutate(Feature=str_replace_all(Feature,'u.cr','Urine Creatinine'))%>%
  mutate(Feature=str_replace_all(Feature,'Lymph.Perc','% Lymphocytes'))%>%
  mutate(Feature=str_replace_all(Feature,'Poverty.Ratio','Poverty Ratio'))%>%
  mutate(Feature=str_replace_all(Feature,'pulse','Pulse'))%>%
  mutate(Feature=str_replace_all(Feature,'wbc','White Blood Cell Count'))%>%
  mutate(Feature=str_replace_all(Feature,'choles','Cholesterol'))%>%
  mutate(Feature=str_replace_all(Feature,'^Waist.Circ','Waist Circumference'))%>%
  mutate(Feature=str_replace_all(Feature,'^ast','AST'))%>%
  mutate(Feature=str_replace_all(Feature,'^DBP','Diastolic Blood Pressure')) %>% 
  mutate(Feature=str_replace_all(Feature,'^ggt','GGT')) %>% 
  mutate(Feature=str_replace_all(Feature,'^cr','Creatinine')) %>%  
  mutate(Feature=str_replace_all(Feature,'^iron','Iron')) %>% 
  mutate(Feature=str_replace_all(Feature,'^plt','Platelets')) %>%  
  mutate(Feature=str_replace_all(Feature,'^Fasting.Time','Fasting Time')) %>%  
  mutate(Feature=str_replace_all(Feature,'^mcv','Mean Cellular Volume')) %>%  
  mutate(Feature=factor(Feature,levels=Feature))

p <- df.imp %>%   ggplot() + 
  geom_col(aes(x=Feature,y=Gain)) +  ylab("Importance") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  theme(text = element_text(size = 11))

print(p)
  
ggsave('Feature-Importance.bmp', p, width = 4, height = 3, units = "in")


knitr::kable(df.imp %>% select(Feature,Gain))


plot.import.full<- df.imp %>% arrange(Gain) %>% mutate(Feature=factor(Feature,levels=Feature)) %>% ggplot() + geom_col(aes(x=Feature,y=Gain))  + coord_flip() + labs(title="Importance Plot - Full Model",subtitle="Top 20 features") + theme(plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust = 0.5))
print(plot.import.full)

ggsave('~/Dropbox/NHANES manuscript/figures/Feature-Importance.bmp', plot.import.full, width = 4, height = 3, units = "in")

```



```{r}
features <- xgb.importance(feature_names = colnames(xgb.model.full),model=xgb.model.full)%>% arrange(desc(Gain)) %>% head(20) %>% pull(Feature) 
df.desc.stats <-df.small %>% select(features,Year) %>% mutate(Year.2015 = ifelse(Year > 2013,"2015-2016","2005-2014")) %>% 
  rename_with(~ str_replace_all(., c(
    'fpg' = 'Fasting Plasma Glucose',
    'a1c' = 'Hemoglobin A1c',
    'tgy' = 'Triglycerides',
    'SBP' = 'Systolic Blood Pressure',
    'u.alb' = 'Urine Albumin',
    'Height.Stand' = 'Height',
    'insulin' = 'Insulin',
    'Seg.Neut.perc' = '% Segmented Neutrophils',
    'u.cr' = 'Urine Creatinine',
    'Lymph.Perc' = '% Lymphocytes',
    'Poverty.Ratio' = 'Poverty Ratio',
    'pulse' = 'Pulse',
    'wbc' = 'White Blood Cell Count',
    'choles' = 'Cholesterol',
    '^Waist.Circ' = 'Waist Circumference',
    '^ast' = 'AST',
    '^DBP' = 'Diastolic Blood Pressure',
    '^ggt' = 'GGT',
    '^cr' = 'Creatinine',
    '^plt' = 'Platelets',
    '^iron' = 'Iron',
    '^Fasting.Time'='Fasting Time',
    '^mcv' = 'Mean Cellular Volume'
  )))  

names.stats <- names(df.desc.stats)
names.stats <- names.stats[! names.stats %in% c('Year','Year.2015')]

library(htmlTable)
library(Gmisc)
df.desc.stats %>% getDescriptionStatsBy(by=Year.2015, names.stats,
#`Fasting Glucose Plasma&dagger;`=fpg,				
add_total_col = FALSE) %>% 
  addHtmlTableStyle(pos.caption = "bottom") %>% 
  htmlTable(caption  = "Basic descriptive statistics from the NHANES dataset",
            tfoot = "&dagger; mg/dL")



# mytheme <- gridExtra::ttheme_default(
#     core = list(fg_params=list(cex = 0.7)),
#     colhead = list(fg_params=list(cex = 0.5)),
#     rowhead = list(fg_params=list(cex = 0.5)))
# 
# df.stats.pdm.grob <- df %>% tableGrob(theme=mytheme)


```



```{r}
df.sampled <- df %>% drop_na(sample.ogtt.weight,a1c,two)  %>% sample_n(size=100000,weight = sample.ogtt.weight,replace=TRUE)

paste("Diabetes Dx by Both:", df.sampled %>% filter(a1c>=6.5 | two>=200) %>% nrow() / 100000 ) 
paste("Diabetes Dx by OGTT:", df.sampled %>% filter(two>=200) %>% nrow() / 100000 ) 
paste("Diabetes Dx by A1c:", df.sampled %>% filter(a1c>=6.5) %>% nrow() / 100000 ) 
paste("Diabetes Dx by A1c not OGTT:", df.sampled %>% filter(a1c>=6.5 & two < 200) %>% nrow() / 100000 ) 
paste("Diabetes Dx by OGTT not A1c:", df.sampled %>% filter(a1c<6.5 & two >= 200) %>% nrow() / 100000 ) 



```





```{r Manuscript Figure 1}
df.boxplot <- df %>% drop_na(sample.ogtt.weight,a1c,two) %>% filter(a1c<6.5 & a1c>=3.7 ) %>% sample_n(size=100000,weight = sample.ogtt.weight,replace=TRUE)  %>% mutate(a1c_group = cut(a1c, seq(4.9, 7, 0.8)) )   %>% mutate(BMI = Weight/(Height.Stand^2)*100*100) %>% mutate(FIB4=ast/sqrt(alt)*Age/plt) %>% drop_na(a1c_group)

# Define the factor levels
colors <- c(
  "All" = "black",
  "eGFR≥60" = "blue",
  "eGFR<60" = "blue",
  "Hgb≥13" = "green",
  "Hgb<13" = "green",
  "BMI<30" = "darkgreen",
  "BMI≥30" = "darkgreen",
  "FIB4≤2.67" = "red",
  "FIB4>2.67" = "red",
  "Age<60" = "darkorange",
  "Age≥60" = "darkorange",
  "SBP<140" = "purple",
  "SBP≥140" = "purple"

)

levels_order <- names(colors)

box.width=0.07
plt.cohort.boxplots<-ggplot() +  
  geom_boxplot(data = df.boxplot, aes(x = a1c_group, y = two, color = factor("All", levels = levels_order)), 
               alpha = 0.9, position = position_nudge(x = -0.6 * box.width * 10), width = box.width * 0.95) +
  
  geom_boxplot(data = df.boxplot %>% filter(cr<2), aes(x = a1c_group, y = two, color = factor("Cr<2", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = -0.5 * box.width * 10), width = box.width * 0.95) +
  
  geom_boxplot(data = df.boxplot %>% filter(cr>=2), aes(x = a1c_group, y = two, color = factor("Cr≥2", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = -0.4 * box.width * 10), width = box.width * 0.95,fill='black') +
  
  geom_boxplot(data = df.boxplot %>% filter(hg>=13), aes(x = a1c_group, y = two, color = factor("Hgb≥13", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = -0.3 * box.width * 10), width = box.width * 0.95) +
  
  geom_boxplot(data = df.boxplot %>% filter(hg<13), aes(x = a1c_group, y = two, color = factor("Hgb<13", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = -0.2 * box.width * 10), width = box.width * 0.95,fill='black') +
  
  geom_boxplot(data = df.boxplot %>% filter(BMI < 30), aes(x = a1c_group, y = two, color = factor("BMI<30", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = -0.1 * box.width * 10), width = box.width * 0.95) +
  geom_boxplot(data = df.boxplot %>% filter(BMI >=30), aes(x = a1c_group, y = two, color = factor("BMI≥30", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0 * box.width * 10), width = box.width * 0.95,fill='black') + 
  geom_boxplot(data = df.boxplot %>% filter(FIB4 <= 2.67), aes(x = a1c_group, y = two, color = factor("FIB4≤2.67", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0.1 * box.width * 10), width = box.width * 0.95) +
  
  geom_boxplot(data = df.boxplot %>% filter(FIB4 > 2.67), aes(x = a1c_group, y = two, color = factor("FIB4>2.67", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0.2 * box.width * 10), width = box.width * 0.95,fill='black') +
  
  geom_boxplot(data = df.boxplot %>% filter(Age < 60), aes(x = a1c_group, y = two, color = factor("Age<60", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0.3 * box.width * 10), width = box.width * 0.95) +
  
  geom_boxplot(data = df.boxplot %>% filter(Age >=60), aes(x = a1c_group, y = two, color = factor("Age≥60", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0.4 * box.width * 10), width = box.width * 0.95,fill='black') +
  
  geom_boxplot(data = df.boxplot %>% filter(SBP < 140), aes(x = a1c_group, y = two, color = factor("SBP<140", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0.5 * box.width * 10), width = box.width * 0.95) +
  
  geom_boxplot(data = df.boxplot %>% filter(SBP >=140), aes(x = a1c_group, y = two, color = factor("SBP≥140", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0.6 * box.width * 10), width = box.width * 0.95,fill='black') +
  geom_hline(aes(yintercept = 140), color = 'red', linetype = 'dashed') +
  geom_hline(aes(yintercept = 200), color = 'red', linetype = 'dashed') +
  xlab('A1c Range') +
  ylab('2-hour Glucose') +
  labs(color = "Subset") +
  scale_color_manual(values = colors) ;print(plt.cohort.boxplots)

ggsave(plot=plt.cohort.boxplots,file='~/Dropbox/NHANES manuscript/figures/Cohort-Boxplots.bmp')
```


```{r}
box.width=0.07
box.perc = 0.8
plt.cohort.boxplots<-ggplot() +
  geom_boxplot(data = df.boxplot, aes(x = a1c_group, y = two, color = factor("All", levels = levels_order)), 
               alpha = 0.9, position = position_nudge(x = -0.6 * box.width * 10), width = box.width * box.perc) +
  
  geom_boxplot(data = df.boxplot %>% filter(cr<2), aes(x = a1c_group, y = two, color = factor("Cr<2", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = -0.5 * box.width * 10), width = box.width * box.perc) +
  
  geom_boxplot(data = df.boxplot %>% filter(cr>=2), aes(x = a1c_group, y = two, color = factor("Cr≥2", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = -0.4 * box.width * 10), width = box.width * box.perc,fill='black') +
  
  geom_boxplot(data = df.boxplot %>% filter(hg>=13), aes(x = a1c_group, y = two, color = factor("Hgb≥13", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = -0.3 * box.width * 10), width = box.width * box.perc) +
  
  geom_boxplot(data = df.boxplot %>% filter(hg<13), aes(x = a1c_group, y = two, color = factor("Hgb<13", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = -0.2 * box.width * 10), width = box.width * box.perc,fill='black') +
  
  geom_boxplot(data = df.boxplot %>% filter(BMI < 30), aes(x = a1c_group, y = two, color = factor("BMI<30", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = -0.1 * box.width * 10), width = box.width * box.perc) +
  geom_boxplot(data = df.boxplot %>% filter(BMI >=30), aes(x = a1c_group, y = two, color = factor("BMI≥30", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0 * box.width * 10), width = box.width * box.perc,fill='black') + 
  geom_boxplot(data = df.boxplot %>% filter(FIB4 <= 2.67), aes(x = a1c_group, y = two, color = factor("FIB4≤2.67", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0.1 * box.width * 10), width = box.width * box.perc) +
  
  geom_boxplot(data = df.boxplot %>% filter(FIB4 > 2.67), aes(x = a1c_group, y = two, color = factor("FIB4>2.67", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0.2 * box.width * 10), width = box.width * box.perc,fill='black') +
  
  geom_boxplot(data = df.boxplot %>% filter(Age < 60), aes(x = a1c_group, y = two, color = factor("Age<60", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0.3 * box.width * 10), width = box.width * box.perc) +
  
  geom_boxplot(data = df.boxplot %>% filter(Age >=60), aes(x = a1c_group, y = two, color = factor("Age≥60", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0.4 * box.width * 10), width = box.width * box.perc,fill='black') +
  
  geom_boxplot(data = df.boxplot %>% filter(SBP < 140), aes(x = a1c_group, y = two, color = factor("SBP<140", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0.5 * box.width * 10), width = box.width * box.perc) +
  
  geom_boxplot(data = df.boxplot %>% filter(SBP >=140), aes(x = a1c_group, y = two, color = factor("SBP≥140", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0.6 * box.width * 10), width = box.width * 0.95,fill='black') +
  geom_hline(aes(yintercept = 140), color = 'red', linetype = 'dashed') +
  geom_hline(aes(yintercept = 200), color = 'red', linetype = 'dashed') +
  xlab('A1c Range') +
  ylab('2-hour Glucose') +
  labs(color = "Subset") +
  scale_color_manual(values = colors)  ;print(plt.cohort.boxplots)
```




```{r}
ggplot() +  
  geom_boxplot(data = df.boxplot, aes(x = a1c_group, y = two, color = factor("All", levels = levels_order)), 
               alpha = 1, position = position_nudge(x = -0.5), width = 0.1 ,fill='white')+
  geom_boxplot(data = df.boxplot %>% filter((hg>=13 & Gender=="Male") | (hg>=11 & Gender=="Female") ), aes(x = a1c_group, y = two, color = factor("Hgb≥13", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = -0.2), width = 0.4 )+
  geom_boxplot(data = df.boxplot%>% filter((hg < 13 & Gender=="Male") | (hg < 11 & Gender=="Female") ), aes(x = a1c_group, y = two, color = factor("Hgb<13", levels = levels_order)), 
               alpha = 1, position = position_nudge(x = 0.2 ), width = 0.4,fill='darkgrey')  +
  geom_hline(aes(yintercept = 140), color = 'red', linetype = 'dashed') +
  geom_hline(aes(yintercept = 200), color = 'red', linetype = 'dashed') +
  xlab('A1c Range') +
  ylab('2-hour Glucose') +
  labs(color = "Subset") +
  scale_color_manual(values = colors) 
```


```{r}
colors <- c(
  "All" = "black",
  "eGFR≥30" = "blue",
  "eGFR<30" = "blue",
  "Hgb≥13" = "green",
  "Hgb<13" = "green",
  "BMI<30" = "darkgreen",
  "BMI≥30" = "darkgreen",
  "FIB4≤2.67" = "red",
  "FIB4>2.67" = "red",
  "Age<60" = "darkorange",
  "Age≥60" = "darkorange",
  "SBP<140" = "purple",
  "SBP≥140" = "purple"

)
levels_order <- names(colors)


plt.cohort.1 <-ggplot() +
  geom_boxplot(data = df.boxplot, aes(x = a1c_group, y = two, color = factor("All", levels = levels_order)), 
               alpha = 1, position = position_nudge(x = -0.5), width = 0.1 ,fill='white')+
  
  geom_boxplot(data = df.boxplot %>% mutate(eGFR = 142 * 
                       pmin(cr/ifelse(Gender=="Male",0.9,0.7),1,na.rm=TRUE ) ^ifelse(Gender=="Male",-0.302,-0.241) *
                       pmax(cr/ifelse(Gender=="Male",0.9,0.7),1,na.rm=TRUE ) ^-1.20 *
                       0.9938 ^ Age *
                       ifelse(Gender=="Male",1,1.012)) %>% filter(eGFR >= 30), aes(x = a1c_group, y = two, color = factor("eGFR≥30", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = -0.2), width = 0.4 )+
  geom_boxplot(data = df.boxplot %>% mutate(eGFR = 142 * 
                       pmin(cr/ifelse(Gender=="Male",0.9,0.7),1,na.rm=TRUE ) ^ifelse(Gender=="Male",-0.302,-0.241) *
                       pmax(cr/ifelse(Gender=="Male",0.9,0.7),1,na.rm=TRUE ) ^-1.20 *
                       0.9938 ^ Age *
                       ifelse(Gender=="Male",1,1.012)) %>% filter(eGFR<30), aes(x = a1c_group, y = two, color = factor("eGFR<30", levels = levels_order)), 
               alpha = 1, position = position_nudge(x = 0.2 ), width = 0.4,fill='darkgrey')  +
  geom_hline(aes(yintercept = 140), color = 'red', linetype = 'dashed') +
  geom_hline(aes(yintercept = 200), color = 'red', linetype = 'dashed') +
  xlab('A1c Range') +
  ylab('2-hour Glucose') +
  labs(color = "Subset") +
  scale_color_manual(values = colors) 


plt.cohort.2 <- ggplot() +  
  geom_boxplot(data = df.boxplot, aes(x = a1c_group, y = two, color = factor("All", levels = levels_order)), 
               alpha = 1, position = position_nudge(x = -0.5), width = 0.1 ,fill='white')+
  geom_boxplot(data = df.boxplot %>% filter((hg>=13 & Gender=="Male") | (hg>=11 & Gender=="Female") ), aes(x = a1c_group, y = two, color = factor("Hgb≥13", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = -0.2), width = 0.4 )+
  geom_boxplot(data = df.boxplot%>% filter((hg < 13 & Gender=="Male") | (hg < 11 & Gender=="Female") ), aes(x = a1c_group, y = two, color = factor("Hgb<13", levels = levels_order)), 
               alpha = 1, position = position_nudge(x = 0.2 ), width = 0.4,fill='darkgrey')  +
  geom_hline(aes(yintercept = 140), color = 'red', linetype = 'dashed') +
  geom_hline(aes(yintercept = 200), color = 'red', linetype = 'dashed') +
  xlab('A1c Range') +
  ylab('2-hour Glucose') +
  labs(color = "Subset") +
  scale_color_manual(values = colors) 

plt.cohort.3 <-ggplot() +  
  geom_boxplot(data = df.boxplot, aes(x = a1c_group, y = two, color = factor("All", levels = levels_order)), 
               alpha = 1, position = position_nudge(x = -0.5), width = 0.1 ,fill='white')+
  geom_boxplot(data = df.boxplot %>% filter(BMI < 30), aes(x = a1c_group, y = two, color = factor("BMI<30", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = -0.2), width = 0.4 )+
  geom_boxplot(data = df.boxplot %>% filter(BMI >=30), aes(x = a1c_group, y = two, color = factor("BMI≥30", levels = levels_order)), 
               alpha = 1, position = position_nudge(x = 0.2 ), width = 0.4,fill='darkgrey')  +
  geom_hline(aes(yintercept = 140), color = 'red', linetype = 'dashed') +
  geom_hline(aes(yintercept = 200), color = 'red', linetype = 'dashed') +
  xlab('A1c Range') +
  ylab('2-hour Glucose') +
  labs(color = "Subset") +
  scale_color_manual(values = colors)

plt.cohort.4 <-ggplot() +  
  geom_boxplot(data = df.boxplot, aes(x = a1c_group, y = two, color = factor("All", levels = levels_order)), 
               alpha = 1, position = position_nudge(x = -0.5), width = 0.1 ,fill='white')+
  geom_boxplot(data = df.boxplot %>% filter(FIB4 <= 2.67), aes(x = a1c_group, y = two, color = factor("FIB4≤2.67", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = -0.2), width = 0.4 )+
  
  geom_boxplot(data = df.boxplot %>% filter(FIB4 > 2.67), aes(x = a1c_group, y = two, color = factor("FIB4>2.67", levels = levels_order)), 
               alpha = 1, position = position_nudge(x = 0.2 ), width = 0.4,fill='darkgrey')  +
  geom_hline(aes(yintercept = 140), color = 'red', linetype = 'dashed') +
  geom_hline(aes(yintercept = 200), color = 'red', linetype = 'dashed') +
  xlab('A1c Range') +
  ylab('2-hour Glucose') +
  labs(color = "Subset") +
  scale_color_manual(values = colors)


plt.cohort.5 <- ggplot() +    
  geom_boxplot(data = df.boxplot, aes(x = a1c_group, y = two, color = factor("All", levels = levels_order)), 
               alpha = 1, position = position_nudge(x = -0.5), width = 0.1 ,fill='white')+
  geom_boxplot(data = df.boxplot %>% filter(Age < 60), aes(x = a1c_group, y = two, color = factor("Age<60", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = -0.2), width = 0.4 )+

  geom_boxplot(data = df.boxplot %>% filter(Age >=60), aes(x = a1c_group, y = two, color = factor("Age≥60", levels = levels_order)), 
               alpha = 1, position = position_nudge(x = 0.2 ), width = 0.4,fill='darkgrey')  +
  geom_hline(aes(yintercept = 140), color = 'red', linetype = 'dashed') +
  geom_hline(aes(yintercept = 200), color = 'red', linetype = 'dashed') +
  xlab('A1c Range') +
  ylab('2-hour Glucose') +
  labs(color = "Subset") +
  scale_color_manual(values = colors)


plt.cohort.6 <-ggplot() +    
  geom_boxplot(data = df.boxplot, aes(x = a1c_group, y = two, color = factor("All", levels = levels_order)), 
               alpha = 1, position = position_nudge(x = -0.5), width = 0.1 ,fill='white')+
  geom_boxplot(data = df.boxplot %>% filter(SBP < 140), aes(x = a1c_group, y = two, color = factor("SBP<140", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = -0.2), width = 0.4 )+
  
  geom_boxplot(data = df.boxplot %>% filter(SBP >=140), aes(x = a1c_group, y = two, color = factor("SBP≥140", levels = levels_order)), 
               alpha = 1, position = position_nudge(x = 0.2 ), width = 0.4,fill='darkgrey')  +
  geom_hline(aes(yintercept = 140), color = 'red', linetype = 'dashed') +
  geom_hline(aes(yintercept = 200), color = 'red', linetype = 'dashed') +
  xlab('A1c Range') +
  ylab('2-hour Glucose') +
  labs(color = "Subset") +
  scale_color_manual(values = colors) 

plt.cohorts <- grid.arrange(ncol=2,nrow=3,plt.cohort.1,plt.cohort.2,plt.cohort.3,plt.cohort.4,plt.cohort.5, plt.cohort.6)

plt.cohorts %>% ggsave(file="~/Dropbox/NHANES manuscript/figures/Cohort-6.bmp",height=10,width=7,units=c("in")); plot(plt.cohorts)

```


```{r Full vs True comparison}
ggplot(office_test) + geom_point(aes(x=two,y=Pred.Full)) +
  geom_point(aes(x=two,y=Pred.FIB4),color='red') +  
  geom_point(aes(x=two,y=Pred.FPG),color='green') +
  geom_point(aes(x=two,y=Pred.Min),color='blue') +
  geom_point(aes(x=two,y=Pred.NonFasting),color='pink') +
  #geom_point(aes(x=two,y=Pred.Var2),color='cyan') +
  geom_abline(aes(intercept=0,slope=1)) +
  geom_vline(aes(xintercept=140),color='red') + 
  geom_vline(aes(xintercept=200),color='red') + 
  geom_hline(aes(yintercept=140),color='red') + 
  geom_hline(aes(yintercept=200),color='red') 



ggplot(office_test) + geom_point(aes(x=two,y=Pred.Full-Pred.Min)) +
  #geom_point(aes(x=two,y=Pred.Base),color='red') +  
  #geom_point(aes(x=two,y=Pred.SDOH),color='green') +
  #geom_point(aes(x=two,y=Pred.Fasting),color='blue') +
  #geom_point(aes(x=two,y=Pred.Urine.Var),color='pink') +
  #geom_point(aes(x=two,y=Pred.Var2),color='cyan') +
  geom_abline(aes(intercept=0,slope=0)) 
  #geom_vline(aes(xintercept=140),color='red') + 
  #geom_vline(aes(xintercept=200),color='red') + 
  #geom_hline(aes(yintercept=140),color='red') + 
  #geom_hline(aes(yintercept=200),color='red') 

office_test %>% mutate(Diff = (Pred.Full-Pred.Min)*sample.ogtt.weight/sum(sample.ogtt.weight)) %>% summarise(Diff.Mean = mean(Diff),Diff.SD=sd(Diff))

```


```{r Importance Comparison}
require(dplyr)
df.importance <-full_join(
    xgb.importance(feature_names = colnames(xgb_models$Full),model=xgb_models$Full) %>% select(Feature,Gain) %>% dplyr::rename(Gain.Full=Gain),
    full_join(
      xgb.importance(feature_names = colnames(xgb_models$FIB4),model=xgb_models$FIB4) %>% select(Feature,Gain) %>% dplyr::rename(Gain.FIB4=Gain),
      full_join(
        xgb.importance(feature_names = colnames(xgb_models$NonFasting),model=xgb_models$NonFasting) %>% select(Feature,Gain) %>% dplyr::rename(Gain.NonFasting=Gain),
        full_join(
          xgb.importance(feature_names = colnames(xgb_models$FPG),model=xgb_models$FPG) %>% select(Feature,Gain) %>% dplyr::rename(Gain.FPG=Gain),
                  xgb.importance(feature_names = colnames(xgb_models$MIN),model=xgb_models$MIN) %>% select(Feature,Gain) %>% dplyr::rename(Gain.Min=Gain)                       
                  ,join_by(Feature))
            ,join_by(Feature))
      ,join_by(Feature))
    ,join_by(Feature))
      



Var.Clinic.2 = c("Age","GenderFemale","GenderMale","pulse","SBP","DBP","Height.Stand","Weight","Waist.Circ","Arm.Circ",
                 "reg.ireggRegular", "reg.ireggIrregular")
Var.Hx.2 = c("BP.Ever.Told.HighYes","BP.Ever.Told.HighNo","BP.Ever.Told.HighDon't know",
             "pdm.toldYes","pdm.toldNo","pdm.toldDon't know","pdm.toldRefused",
             "Sleep.Hours",
             "dm.test.3yrsYes","dm.test.3yrsNo","dm.test.3yrsRefused","dm.test.3yrsDon't know",
             "Ever.Told.OverweightYes","Ever.Told.OverweightNo","Ever.Told.OverweightDon't know","Ever.Told.OverweightRefused",
             "TransfusionEverYes","TransfusionEverNo","TransfusionEverDon't know",
             "Sleep.Ever.Told.PoorYes","Sleep.Ever.Told.PoorNo","Sleep.Ever.Told.PoorDon't know",
             "dm.toldYes","dm.toldNo","dm.toldBorderline","dm.toldDon't know",
             "dm.told.everYes","dm.told.everNo","dm.told.everDon't know","dm.told.everRefused",
             "relative.asthmaYes","relative.asthmaNo","relative.asthmaDon't know","relative.asthmaRefused",
             "Told.AsthmaYes","Told.AsthmaNo","Told.AsthmaDon't know",
             "Anemia.TreatmentYes","Anemia.TreatmentNo","Anemia.TreatmentDon't know") 

Var.CBC.2 = c("Seg.Neut.perc","Lymph.Perc","mcv","Monocyte.perc","eosin.perc","plt","Mean.Cell.Hemoglobin","mpv","rbc","hg","MCHC","Baso.Perc","wbc","RBC.Dist.Width")

Var.CMP.2 = c("na","potas","chlor","bicarb","bun","cr","cal","tprot","tbili","alb","ast","alt","alp","a1c")


Var.Urine.2 = c("u.alb", "u.cr")
Var.Other.1.2 = c("ggt","phos","choles","HepB.cAbNegative",
                  "HepB.sAbPositive","HepB.sAbNegative",
                  "HepB.cAbPositive")
Var.Other.2.2 = c("urica","Hydroxycontine","Hydrocontine",
                  "Hep.APositive","Hep.ANegative","Hep.AIndeterminate",
                  "Osmolality","Globulin","ldh")
Var.SDOH.2 = c("Poverty.Ratio",
               "RaceEthNon-Hispanic Black","RaceEthOther Hispanic","RaceEthNon-Hispanic White","RaceEthMexican American","RaceEthOther Race - Including Multi-Racial",
               "Num.People.Household",
               "Marriage.StatusMarried","Marriage.StatusWidowed","Marriage.StatusLiving with partner","Marriage.StatusDivorced","Marriage.StatusSeparated","Marriage.StatusNever married","Marriage.StatusRefused","Marriage.StatusDon't know", 
               "LANG",
               "CitizenStatusCitizen by birth or naturalization","CitizenStatusNot a citizen of the US","CitizenStatusDon't know","CitizenStatusRefused",
               "EduLevelCollege Graduate or above","EduLevelSome College or AA degree","EduLevelHigh School Grad/GED or Equivalent","EduLevelHigh School Grad/GED or equivalent","EduLevel9-11th Grade (Includes 12th grade with no diploma)","EduLevelLess Than 9th Grade","EduLevelRefused","EduLevelDon't know") 


Var.fasting.2 = c('fpg','tgy','insulin',"iron")


Var.Other.3.2 = c("u.alb", "u.cr","choles","ggt","phos",
                  "HepB.cAbNegative",
                  "HepB.sAbPositive","HepB.sAbNegative",
                  "HepB.cAbPositive")


Var.MIN <- c()

### BASE: Clinic + Hx CBC + CMP + Hx
### + SDOH
### + Fasting
### + Urine + Var.Other.1
### + Var.Other.2

var.vector <- c(rep("Clinic",length(Var.Clinic.2)),
                rep("History",length(Var.Hx.2)), ### excluding Ever.Told.OverweightRefused,dm.told.ever$Refused
                rep("CBC",length(Var.CBC.2)),
                rep("CMP",length(Var.CMP.2)),
                rep("SDOH History",length(Var.SDOH.2)),
                rep("Fasting Labs",length(Var.fasting.2)),
                rep("Urine",length(Var.Urine.2)),
                rep("Various Labs #1",length(Var.Other.1.2)),
                rep("Various Labs #2",length(Var.Other.2.2))  )

var.features <- c(Var.Clinic.2,
                  Var.Hx.2,
                  Var.CBC.2,
                  Var.CMP.2,
                  Var.SDOH.2,
                  Var.fasting.2,
                  Var.Urine.2,
                  Var.Other.1.2,
                  Var.Other.2.2)

lookup_df <- data.frame(X=var.vector,Y=var.features)
#df.importance$Feature[!df.importance$Feature %in% var.features]

var.features.2<-var.features[var.features %in% df.importance$Feature]
### STUCK HERE 11.22.2024

df.importance %>% left_join(lookup_df,by=c("Feature"="Y")) %>% dplyr::rename(Type=X) %>% relocate(Feature,Type) %>% mutate(Feature=factor(Feature,levels=var.features.2)) %>% arrange(Feature)  %>% pivot_longer(names_to = 'Model',cols=c(Gain.FPG,Gain.FIB4,Gain.NonFasting,Gain.Min,Gain.Full))


df.importance %>% left_join(lookup_df,by=c("Feature"="Y")) %>% dplyr::rename(Type=X) %>% mutate(Feature=factor(Feature,levels=var.features.2)) %>% arrange(Feature)  %>% pivot_longer(names_to = 'Model',cols=c(Gain.FPG,Gain.FIB4,Gain.NonFasting,Gain.Min,Gain.Full)) %>% ggplot() + geom_tile(aes(x=Model,y=Feature,fill=-log10(value)))

df.importance  %>% left_join(lookup_df,by=c("Feature"="Y")) %>% dplyr::rename(Type=X) %>% mutate(Feature=factor(Feature,levels=var.features.2)) %>% arrange(Feature)  %>% mutate(across(where(is.numeric), round, 5)) %>% write.csv(file="~/Documents/NHANES15-16/Model-Importance_2025.02.25.csv",row.names = FALSE)
```

```{r}
# plot.import.Base<- xgb.importance(feature_names = colnames(xgb.model.Base),model=xgb.model.Base) %>% head(20) %>% arrange(Gain) %>% mutate(Feature=factor(Feature,levels=Feature)) %>% ggplot() + geom_col(aes(x=Feature,y=Gain))  + coord_flip() + labs(title="Importance Plot - Base Model",subtitle="Top 20 features") + theme(plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust = 0.5))
# 
# plot.import.SDOH<- xgb.importance(feature_names = colnames(xgb.model.SDOH),model=xgb.model.SDOH) %>% head(20) %>% arrange(Gain) %>% mutate(Feature=factor(Feature,levels=Feature)) %>% ggplot() + geom_col(aes(x=Feature,y=Gain))  + coord_flip() + labs(title="Importance Plot - SDOH Model",subtitle="Top 20 features") + theme(plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust = 0.5))
# 
# plot.import.Fasting<- xgb.importance(feature_names = colnames(xgb.model.Fasting),model=xgb.model.Fasting) %>% head(20) %>% arrange(Gain) %>% mutate(Feature=factor(Feature,levels=Feature)) %>% ggplot() + geom_col(aes(x=Feature,y=Gain))  + coord_flip() + labs(title="Importance Plot - Fasting Model",subtitle="Top 20 features") + theme(plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust = 0.5))
# 
# plot.import.Urine.Var<- xgb.importance(feature_names = colnames(xgb.model.Urine.Var),model=xgb.model.Urine.Var) %>% head(20) %>% arrange(Gain) %>% mutate(Feature=factor(Feature,levels=Feature)) %>% ggplot() + geom_col(aes(x=Feature,y=Gain))  + coord_flip() + labs(title="Importance Plot - Urine + Various Labs #1 Model",subtitle="Top 20 features") + theme(plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust = 0.5))
# 
# plot.import.Var2<- xgb.importance(feature_names = colnames(xgb.model.Var2),model=xgb.model.Var2) %>% head(20) %>% arrange(Gain) %>% mutate(Feature=factor(Feature,levels=Feature)) %>% ggplot() + geom_col(aes(x=Feature,y=Gain))  + coord_flip() + labs(title="Importance Plot - Various Labs #2 Model",subtitle="Top 20 features") + theme(plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust = 0.5))
# 
# plot.import.full<- xgb.importance(feature_names = colnames(xgb.model.full),model=xgb.model.full) %>% head(20) %>% arrange(Gain) %>% mutate(Feature=factor(Feature,levels=Feature)) %>% ggplot() + geom_col(aes(x=Feature,y=Gain))  + coord_flip() + labs(title="Importance Plot - Full Model",subtitle="Top 20 features") + theme(plot.title = element_text(hjust = 0.5),plot.subtitle = element_text(hjust = 0.5))
# 
# 
# grid.arrange(ncol=2,nrow=3,plot.import.Base,plot.import.Fasting,plot.import.SDOH,plot.import.Urine.Var,plot.import.Var2,plot.import.full)
# 
# ## file.importance.plots = TAKETHIS
# ggsave(file=file.importance.plots,arrangeGrob(ncol=2,nrow=3,plot.import.Base,plot.import.Fasting,plot.import.SDOH,plot.import.Urine.Var,plot.import.Var2,plot.import.full))

```

```{r}

plt.01.line <- geom_line(data=data.frame(x=c(0,1),y=c(0,1)),aes(x=x,y=y),linetype="dashed")

plt.calibration<-office_test   %>% 
  ggplot()+ 
  geom_point(data=office_test %>% filter(a1c>=6.5),aes(x=Pred.Min,y=two),alpha=0.7,color='black') + 
  geom_point(data=office_test %>% filter( a1c<6.5),aes(x=Pred.Min,y=two,color=a1c),alpha=0.7) +  
  #geom_point(data=office_test %>% filter(a1c < 4.5 ),aes(x=Pred.Min,y=two,color=a1c),color='yellow',alpha=0.7) +  
  geom_line(data=data.frame(x=c(50,500),y=c(50,500)),aes(x=x,y=y),linetype="dashed")+ xlim(c(50,500)) + ylim(c(50,500)) + scale_color_viridis(name='Hemoglobin\nA1c (%)',direction=-1) + 
  xlab("Predicted 2-hour Glucose") + ylab("Measured 2-hour Glucose (mg/dL)");plot(plt.calibration)

ggsave(file='~/Dropbox/NHANES manuscript/figures/Calibration.bmp',plot=plt.calibration)

cor(office_test.All$two,office_test.All$Pred.MIN)^2
```




```{r}
# Define predictors and labels
predictors <- list(
  "FPG" = office_test$fpg,
  "A1c" = office_test$a1c,
  "FPG-A1c" = office_test$Pred.FPG,
  "FIB4" = office_test$Pred.FIB4,
  "NonFasting" = office_test$Pred.NonFasting,
  "Min" = office_test$Pred.Min,
  "Full" = office_test$Pred.Full
)

# Define labels
x0.igt <- as.factor(office_test$two >= 140 & office_test$two < 200)
x0.pphg <- as.factor(office_test$two >= 200)

# Helper function to compute AUC metrics
compute_auc_metrics <- function(pred, label) {
  c(
    auc(AUC::sensitivity(pred, label)),
    auc(AUC::specificity(pred, label)),
    auc(AUC::roc(pred, label))
  )
}

# Iterate over predictors and calculate stats
auc_results <- lapply(predictors, function(pred) {
  c(compute_auc_metrics(pred, x0.igt), compute_auc_metrics(pred, x0.pphg))
})

# Construct the final data frame
df.stats <- do.call(cbind, auc_results) %>% as.data.frame()
df.stats <- round(df.stats,3)
# Name rows and columns
df.stats$Stat <- rep(c("Sensitivity", "Specificity", "AUROC"),2)
df.stats$Type <- c(rep("Pre-DM",3),rep("DM",3))

df.stats %>% pivot_longer(!c("Stat","Type"),names_to="Vars",values_to="Value")

# Transpose and convert to data frame
#df.stats <- as.data.frame(t(df.stats))

compute_roc <- function(pred,label){
  tidy(AUC::roc(pred,label))
}

roc_results <- lapply(predictors,function(pred){
  cbind(compute_roc(pred,x0.igt),compute_roc(pred,x0.pphg))
})

roc_results <- do.call(rbind,roc_results) %>% as.data.frame()
colnames(roc_results) <- c("Pre-DM|Cutoff","Pre-DM|FPR","Pre-DM|TPR","DM|Cutoff","DM|FPR","DM|TPR")
roc_results$Type2 <-rownames(roc_results)
roc_results$Type <- str_split_i(rownames(roc_results),"\\.",1)

roc_results <- roc_results %>% pivot_longer(!c("Type","Type2"),names_to = "Stat",values_to = "Value") %>% mutate(Dx = str_split_i(Stat,"\\|",1), Stat = str_split_i(Stat,"\\|",2) ) %>% pivot_wider(id_cols = c("Type","Type2","Dx"),names_from = "Stat",values_from = "Value")

```

```{r}
plt.roc.results <- roc_results %>% ggplot() + 
  geom_line(aes(x=FPR,y=TPR,color=Type,linetype=Dx)) +
  labs(color="Model",linetype="Diagnosis") + 
  xlab('False Positive Rate') + 
  ylab('True Positive Rate')  + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  geom_line(data=data.frame(x=c(0,1),y=c(0,1)),aes(x=x,y=y),linetype="dashed")  + 
  scale_color_manual(values=c("A1c"="darkgreen","FPG"="green","FPG-A1c"="cyan","NonFasting"="magenta","FIB4"="purple","Full"="orange","Min"="red"),guide="none") +
  scale_linetype_discrete(labels=c("Diabetes","Pre-Diabetes")); print(plt.roc.results) 
  

```


```{r}


#df.stats <- df.stats %>% round(3)
library(ggplot2)
library(gridExtra)
library(grid)
library(lattice)
library(gtable)
rownames(df.stats) <- gsub("\\.\\.\\.",' - ', rownames(df.stats) )
df.stats

mytheme <- gridExtra::ttheme_default(
    core = list(fg_params=list(cex = 0.7)),
    colhead = list(fg_params=list(cex = 0.5)),
    rowhead = list(fg_params=list(cex = 0.5)))


df.stats.table <- df.stats[1:6,] %>% relocate(Type,Stat,A1c,FPG,`FPG-A1c`,FIB4,NonFasting,Min,Full) %>% t()

df.stats.grob <- df.stats.table %>% tableGrob(theme=mytheme)

plot(df.stats.grob)


```







```{r DCA plots}
library(dcurves)

# Create outcome variables
df.dca.eval <- office_test %>% 
  mutate(PreDM = as.integer(two >= 140 & two < 200),
         DM = as.integer(two >= 200)) %>%
  slice_sample(weight_by = sample.ogtt.weight, n = 10000, replace = TRUE)

# Define predictors and labels
predictors <- c("a1c", "fpg", "Pred.FPG", "Pred.FIB4", "Pred.NonFasting", "Pred.Min", "Pred.Full")
labels <- c("A1c", "FPG", "A1c-FPG", "FIB4", "Non.Fasting", "Min", "Full")

# Function to fit models and get predictions
fit_and_predict <- function(outcome) {
  models <- lapply(predictors, function(pred) glm(as.formula(paste(outcome, "~", pred)), 
                                                  data = df.dca.eval, family = binomial))
  preds <- sapply(models, function(mod) broom::augment(mod, type.predict = "response") %>% pull(".fitted"))
  colnames(preds) <- paste0("pm.", tolower(outcome), ".", seq_along(predictors))
  preds
}

# Get predictions for PreDM and DM
df.dca.eval <- cbind(df.dca.eval, fit_and_predict("PreDM"), fit_and_predict("DM"))

# Function to create DCA plots
dca_plot <- function(outcome, prefix, title) {
  # Identify prediction columns that match the prefix
  matching_cols <- grep(prefix, names(df.dca.eval), value = TRUE)
  
  # Ensure we have matching columns
  if (length(matching_cols) == 0) {
    stop("No matching columns found for prefix: ", prefix)
  }
  
  # Ensure labels are correctly assigned
  label_list <- setNames(labels[seq_along(matching_cols)], matching_cols)
  label_list <- split(unname(label_list),names(label_list))

  print(label_list)  # Debugging step to verify the mapping  
  # Construct the formula dynamically
  formula <- as.formula(paste(outcome, "~", paste(matching_cols, collapse = " + ")))
  
  # Perform decision curve analysis and plot
  dca(formula, data = df.dca.eval, 
      thresholds = seq(0, 0.5, 0.05), 
      label = label_list) %>%
    plot(smooth = TRUE) %>% suppressWarnings() +theme_grey()+ ggtitle(title) + 
  scale_color_manual(values=c("A1c"="darkgreen","FPG"="green","A1c-FPG"="cyan","Non.Fasting"="magenta","FIB4"="purple","Full"="orange","Min"="red","Treat All"="black","Treat None"="darkgrey"))
}

# Generate and save plots
plot.dca.eval.pdm <- dca_plot("PreDM", "pm.predm", "Pre-Diabetes")
plot.dca.eval.dm <- dca_plot("DM", "pm.dm", "Diabetes")

grid.arrange(nrow = 2, plot.dca.eval.pdm + theme(legend.position="bottom") , 
             plot.dca.eval.dm) %>% suppressWarnings()

#ggsave(file = file.dca.all, arrangeGrob(nrow = 2, plot.dca.eval.pdm, plot.dca.eval.dm))


```


```{r}
library(gridExtra)
library(grid)

```


```{r}

theme.table <- ttheme_default( core= list(bg_params = list(fill=c("darkgrey","darkgrey","grey90",rep(c("grey95", "grey90"),3) )),
                                          fg_params = list(cex = 0.45)),
                               rowhead = list( fg_params = list(cex = 0.6)) ) # Font size for row titles) 
title <- textGrob("Test Characteristics", gp = gpar(fontsize = 12, fontface = "bold"),vjust=2)
tG<-tableGrob(df.stats.table,cols=NULL,theme=theme.table)
tG <- arrangeGrob(title,tG,ncol=1,heights=c(0.01,1),vp = viewport(y = 0.55, height = 0.9))

theme.1 <- theme(axis.text=element_text(size=8),
            axis.title=element_text(size=12),
            plot.tag.position = c(0.01,0.99),
            plot.tag = element_text(size=20),
            plot.title = element_text(hjust = 0.5,size=18)) 

legend.1 <- cowplot::get_legend(plt.roc.results + theme(legend.box="horizontal"))
legend.2 <- cowplot::get_legend(plot.dca.eval.dm +  guides(color=guide_legend(title="Model",ncol=8)) ) 
grid.arrange(nrow=3,heights=c(3,3,1),
             arrangeGrob(ncol=2,
                         plt.roc.results + theme(legend.position="bottom")+theme(legend.box="horizontal") + theme.1 + labs(tag="A"),
                         tG ),
             arrangeGrob(ncol=2,
                         plot.dca.eval.pdm + theme(legend.position="none")+ theme.1 + labs(tag="B"), 
                         plot.dca.eval.dm + theme(legend.position="none")+ theme.1 + labs(tag="C")),
            legend.2 ) %>% suppressWarnings() %>% ggsave(file="~/Dropbox/NHANES manuscript/figures/ROC-DCA-figure.bmp")

```




```{r}
predictors <- c("a1c", "fpg", "Pred.FPG", "Pred.FIB4", "Pred.NonFasting", "Pred.Min", "Pred.Full")
labels <- c("A1c", "FPG", "A1c-FPG", "FIB4", "Non.Fasting", "Min", "Full")
```

```{r}
# Define Diagnosis Categories
office_test$PDM <- as.factor(between(office_test$two, 140, 199))
office_test$DM <- as.factor(office_test$two >= 200)

# Generalized ROC Metric Function
f.pROC.metric <- function(x, predictor.x, response.x, ret = c("threshold")) {
  pROC::coords(pROC::roc_(data = x, predictor = predictor.x, response = response.x), "best", ret = ret)
}

# Generate Statistics Data Frame
f.df.stat <- function(x, y, z) {
  metrics <- c("threshold", "specificity", "sensitivity", "accuracy", "precision")
  data.frame(
    Type = "best",
    Rowname = y,
    Diagnosis = z,
    f.pROC.metric(x, y, z, metrics),
    AUC = pROC::auc(pROC::roc_(data = x, predictor = y, response = z))
  )
}

# Collect Statistics for Multiple Predictors
get_all_stats <- function(x, z, predictors) {
  do.call(rbind, lapply(predictors, function(y) f.df.stat(x, y, z)))
}

#predictors <- c("a1c", "Pred.Base", "Pred.Fasting", "Pred.SDOH", "Pred.Urine.Var", "Pred.Var2", "Pred.Full")
df.stat.2 <- rbind(get_all_stats(office_test, "PDM", predictors), get_all_stats(office_test, "DM", predictors))

# Manual Cutoff Calculation
f.cutoff <- function(x, y, z, a) {
  coords <- pROC::coords(pROC::roc_(data = x, predictor = y, response = z), ret = c("threshold", "sensitivity", "specificity", "accuracy", "precision"))
  i <- which.min(abs(a - coords$threshold))
  data.frame(Type = "manual", Rowname = y, Diagnosis = z, coords[i, ], AUC = pROC::auc(pROC::roc_(data = x, predictor = y, response = z)))
}

manual_cutoffs <- list(PDM = setNames(c(5.7, rep(140, length(predictors) - 1)), predictors), DM = setNames(c(6.5, rep(200, length(predictors) - 1)), predictors))
df.stat.manual <- do.call(rbind, unlist(lapply(names(manual_cutoffs), function(z) {
  mapply(function(y, a) f.cutoff(office_test, y, z, a), names(manual_cutoffs[[z]]), manual_cutoffs[[z]], SIMPLIFY = FALSE)
}), recursive = FALSE))

# Precision-based Cutoff
f.cutoff.precision <- function(x, y, z, a) {
  coords <- pROC::coords(pROC::roc_(data = x, predictor = y, response = z), ret = c("threshold", "sensitivity", "specificity", "accuracy", "precision"))
  i <- which.min(abs(a - coords$precision))
  data.frame(Type = "manual", Rowname = y, Diagnosis = z, coords[i, ], AUC = pROC::auc(pROC::roc_(data = x, predictor = y, response = z)))
}

precision_target <- 0.5
df.stat.precise <- do.call(rbind, unlist(lapply(c("PDM", "DM"), function(z) {
  lapply(predictors, function(y) f.cutoff.precision(office_test, y, z, precision_target))
}), recursive = FALSE))

# Rearrange and Display Data
reorder_cols <- function(df) df %>% relocate(Type, Rowname, Diagnosis, threshold, specificity, sensitivity)

reorder_cols(df.stat.2)
reorder_cols(df.stat.manual)
reorder_cols(df.stat.precise)

```



```{r}
### Load office_test
#load(paste0(dir.string,"NHANES-office-test-layered_",filter.string,"_",date.string,".Rda"))

resample.size <- 1000000
int.resample.test <- resample(seq_len(nrow(office_test)), probs = weight.sample.test / sum(weight.sample.test), size = resample.size)

f.get.thresh <- function(r, s) df.stat.2[df.stat.2$Rowname == r & df.stat.2$Diagnosis == s, "threshold"]

print(head(office_test %>% select(contains("Pred"))))

s <- 'PDM'
df.pdm.confusion.4 <- office_test[int.resample.test, ] %>%
  filter(a1c < 5.7) %>%
  dplyr::mutate(A1c.PDM = a1c >= 5.7 & a1c < 6.5,
         FPG.PDM = Pred.FPG >= f.get.thresh("Pred.FPG", s) & Pred.FPG < f.get.thresh("Pred.FPG", "DM"),
         FIB4.PDM = Pred.FIB4 >= f.get.thresh("Pred.FIB4", s) & Pred.FIB4 < f.get.thresh("Pred.FIB4", "DM"),
         NonFasting.PDM = Pred.NonFasting >= f.get.thresh("Pred.NonFasting", s) & Pred.NonFasting < f.get.thresh("Pred.NonFasting", "DM"),
         Min.PDM = Pred.Min >= f.get.thresh("Pred.Min", s) & Pred.Min < f.get.thresh("Pred.Min", "DM"),
         Full.PDM = Pred.Full >= f.get.thresh("Pred.Full", s) & Pred.Full < f.get.thresh("Pred.Full", "DM")) %>%
  dplyr::mutate(a1c_group = cut(a1c, seq(3.3, 5.7, 0.4), right = FALSE)) %>%
  group_by(a1c_group) %>%
  dplyr::summarise(A1c.PDM.Sum.TP = sum(A1c.PDM & two >= 140 & two < 200),
            A1c.PDM.Sum.FP = sum(A1c.PDM & (two < 140 | two >= 200)),
            A1c.PDM.Sum.FN = sum(!A1c.PDM & (two >= 140 & two < 200)),
            A1c.PDM.Sum.TN = sum(!A1c.PDM & (two < 140 | two >= 200)),

            FPG.PDM.Sum.TP = sum(FPG.PDM & two >= 140 & two < 200),
            FPG.PDM.Sum.FP = sum(FPG.PDM & (two < 140 | two >= 200)),
            FPG.PDM.Sum.FN = sum(!FPG.PDM & (two >= 140 & two < 200)),
            FPG.PDM.Sum.TN = sum(!FPG.PDM & (two < 140 | two >= 200)),

            FIB4.PDM.Sum.TP = sum(FIB4.PDM & two >= 140 & two < 200),
            FIB4.PDM.Sum.FP = sum(FIB4.PDM & (two < 140 | two >= 200)),
            FIB4.PDM.Sum.FN = sum(!FIB4.PDM & (two >= 140 & two < 200)),
            FIB4.PDM.Sum.TN = sum(!FIB4.PDM & (two < 140 | two >= 200)),

            NonFasting.PDM.Sum.TP = sum(NonFasting.PDM & two >= 140 & two < 200),
            NonFasting.PDM.Sum.FP = sum(NonFasting.PDM & (two < 140 | two >= 200)),
            NonFasting.PDM.Sum.FN = sum(!NonFasting.PDM & (two >= 140 & two < 200)),
            NonFasting.PDM.Sum.TN = sum(!NonFasting.PDM & (two < 140 | two >= 200)),

            Min.PDM.Sum.TP = sum(Min.PDM & two >= 140 & two < 200),
            Min.PDM.Sum.FP = sum(Min.PDM & (two < 140 | two >= 200)),
            Min.PDM.Sum.FN = sum(!Min.PDM & (two >= 140 & two < 200)),
            Min.PDM.Sum.TN = sum(!Min.PDM & (two < 140 | two >= 200)),

            Full.PDM.Sum.TP = sum(Full.PDM & two >= 140 & two < 200),
            Full.PDM.Sum.FP = sum(Full.PDM & (two < 140 | two >= 200)),
            Full.PDM.Sum.FN = sum(!Full.PDM & (two >= 140 & two < 200)),
            Full.PDM.Sum.TN = sum(!Full.PDM & (two < 140 | two >= 200)),.groups="drop") %>%
  pivot_longer(-a1c_group, values_to = "Count") %>%
  separate_wider_delim(name, ".", names = c("Model","Dx", NA,"Stat")) %>%
  mutate(Stat = paste0(Stat, 'R'),
         Model = factor(Model, levels = c("A1c", "FPG", "NonFasting", "FIB4", "Min", "Full")),
         Percentage = Count / resample.size * 100,
         `A1c Group` = if_else(a1c_group %in% c("[3.7,4.1)", "[4.1,4.5)"), "[4.0,4.5)", as.character(a1c_group))) %>%
  group_by(`A1c Group`, Stat, Model) %>%
  dplyr::summarise(Count = sum(Count), Percentage = sum(Percentage), .groups = "drop")

grid.arrange(ncol = 2,
  df.pdm.confusion.4 %>%
    ggplot(aes(x = Model, y = Percentage, fill = Stat)) +
    geom_col() +
    facet_wrap(~`A1c Group`, scales = "free") +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
          plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5)) +
    labs(title = "Pre-Diabetes Diagnosis", subtitle = "Plots separated by A1c range", fill = "Statistic"),

  df.pdm.confusion.4 %>%
    ggplot(aes(x = `A1c Group`, y = Percentage, fill = Model)) +
    geom_col(position = 'dodge') +
    facet_wrap(~Stat, scales = "free") +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
          plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5)) +
    labs(title = "Pre-Diabetes Diagnosis", subtitle = "Plots separated by Statistic", fill = "Model")
)



```






```{r}
X <- df.small$a1c
# Function to find the closest value in A$Value

f.find_closest <- function(x, value_vector, ppv_vector) {
  closest_index <- which.min(abs(value_vector - x))
  return(ppv_vector[closest_index])
}

# Find the closest Value for each element in X
#closest_values <- mapply(X, find_closest, value_vector = A$threshold)

# Create a data frame with the closest values and their corresponding PPV
# data.frame(
#   Value = X,
#   Closest_Value = closest_values,
#   PPV = A$precision[match(closest_values, A$threshold)]
# ) %>% ggplot(aes(x=PPV))+ geom_histogram(aes(fill=Value>6.5),binwidth=0.05) + scale_y_log10()

x = office_test
y = "Pred.Full"
dx= "DM"

pROC::coords(pROC::roc_(data=x %>% filter(a1c<6.5) %>% sample_n(size=10000,weight = sample.ogtt.weight,replace=TRUE),predictor=y,response=dx),ret=c("threshold","precision","tn","fn","npv") ) %>% mutate(NPV=tn/(tn+fn)) %>% ggplot() + geom_point(aes(x=npv,y=NPV))

pROC::coords(pROC::roc_(data=x %>% filter(a1c<6.5) %>% sample_n(size=10000,weight = sample.ogtt.weight,replace=TRUE),predictor=y,response=dx),ret=c("threshold","precision","tn","fn","tp","fp","npv") ) %>% pivot_longer(-threshold,values_to = "Value",names_to = "Stat") %>% ggplot()+ geom_point(aes(x=threshold,y=Value,color=Stat))

y= 'a1c'
pROC::coords(pROC::roc_(data=x %>% filter(a1c<6.5) %>% sample_n(size=10000,weight = sample.ogtt.weight,replace=TRUE),predictor=y,response=dx),ret=c("threshold","precision","npv") ) %>% pivot_longer(-threshold,values_to = "Value",names_to = "Stat") %>% ggplot()+ geom_point(aes(x=threshold,y=Value,color=Stat))
```


```{r}
f.build.precise <- function(x,y,dx){
X = x[,y]
A<-pROC::coords(pROC::roc_(data=x,predictor=y,response=dx),ret=c("threshold","precision") ) 


### So, the issue here is that the pROC::coords command gives us a nice list of thresholds and precisions, but it does NOT give us the thresholds that align perfectly with our data points. This means that for a given data point X[[1]][i], we need to see which threshold it is closest too. Annoying, yes

# Function to find the closest value in A$Value
find_closest_ppv <- function(x, value_vector, ppv_vector) {
  closest_index <- which.min(abs(value_vector - x))
  return(ppv_vector[closest_index])
}

# Create a data frame to store the results
result <- data.frame(
  Value = X,
  Closest_Value = NA,
  PPV = NA
)

# Find the closest values and their corresponding PPVs
for (i in seq_along(X[[1]])) {
  closest_index <- which.min(abs(A$threshold - X[[1]][i]))
  result$Closest_Value[i] <- A$threshold[closest_index]
  result$PPV[i] <- A$precision[closest_index]
  result$NPV[i] <- A$npv[closest_index]  
}
return(result[,"PPV"])
} # close f.build.precise



f.build.npv <- function(x,y,dx){
X = x[,y]
A<-pROC::coords(pROC::roc_(data=x,predictor=y,response=dx),ret=c("threshold","npv") ) 

# Function to find the closest value in A$Value
find_closest_npv <- function(x, value_vector, npv_vector) {
  closest_index <- which.min(abs(value_vector - x))
  return(npv_vector[closest_index])
}

# Create a data frame to store the results
result <- data.frame(
  Value = X,
  Closest_Value = NA,
  PPV = NA,
  NPV = NA
)

# Find the closest values and their corresponding PPVs
for (i in seq_along(X[[1]])) {
  closest_index <- which.min(abs(A$threshold - X[[1]][i]))
  result$Closest_Value[i] <- A$threshold[closest_index]
  result$NPV[i] <- A$npv[closest_index]
}
return(result[,"NPV"])
} # close f.build.npv


#return(
#A$precision[match(closest_values, A$threshold)]#)
#}

x$PPV.DM.a1c <- f.build.precise(x,"a1c","DM")
x$PPV.DM.NonFasting <- f.build.precise(x,"Pred.NonFasting","DM") 
# x$PPV.DM.Fasting <- f.build.precise(x,"Pred.Fasting","DM") 
# x$PPV.DM.SDOH <- f.build.precise(x,"Pred.SDOH","DM") 
# x$PPV.DM.Urine.Var <- f.build.precise(x,"Pred.Urine.Var","DM") 
x$PPV.DM.Min <- f.build.precise(x,"Pred.Min","DM")
# x$PPV.DM.Var2 <- f.build.precise(x,"Pred.Var2","DM") 
# x$PPV.DM.Full <- f.build.precise(x,"Pred.Full","DM") 


x$PPV.PDM.a1c <- f.build.precise(x,"a1c","PDM")
x$PPV.PDM.NonFasting<- f.build.precise(x,"Pred.NonFasting","PDM") 
# x$PPV.PDM.Fasting <- f.build.precise(x,"Pred.Fasting","PDM") 
# x$PPV.PDM.SDOH <- f.build.precise(x,"Pred.SDOH","PDM") 
# x$PPV.PDM.Urine.Var <- f.build.precise(x,"Pred.Urine.Var","PDM") 
x$PPV.PDM.Min <- f.build.precise(x,"Pred.Min","PDM")
# x$PPV.PDM.Var2 <- f.build.precise(x,"Pred.Var2","PDM") 
# 
# x$PPV.PDM.Full <- f.build.precise(x,"Pred.Full","PDM") 


x$NPV.DM.a1c <- f.build.npv(x,"a1c","DM")
x$NPV.DM.NonFasting <- f.build.npv(x,"Pred.NonFasting","DM") 
# x$PPV.DM.Fasting <- f.build.precise(x,"Pred.Fasting","DM") 
# x$PPV.DM.SDOH <- f.build.precise(x,"Pred.SDOH","DM") 
# x$PPV.DM.Urine.Var <- f.build.precise(x,"Pred.Urine.Var","DM") 
x$NPV.DM.Min <- f.build.npv(x,"Pred.Min","DM")
# x$PPV.DM.Var2 <- f.build.precise(x,"Pred.Var2","DM") 
# x$PPV.DM.Full <- f.build.precise(x,"Pred.Full","DM") 


x$NPV.PDM.a1c <- f.build.npv(x,"a1c","PDM")
x$NPV.PDM.NonFasting<- f.build.npv(x,"Pred.NonFasting","PDM") 
# x$PPV.PDM.Fasting <- f.build.precise(x,"Pred.Fasting","PDM") 
# x$PPV.PDM.SDOH <- f.build.precise(x,"Pred.SDOH","PDM") 
# x$PPV.PDM.Urine.Var <- f.build.precise(x,"Pred.Urine.Var","PDM") 
x$NPV.PDM.Min <- f.build.npv(x,"Pred.Min","PDM")
# x$PPV.PDM.Var2 <- f.build.precise(x,"Pred.Var2","PDM") 
# 
# x$PPV.PDM.Full <- f.build.precise(x,"Pred.Full","PDM") 



x$PPV.Two <- ifelse(x$two>=200,1.1,ifelse(x$two>=140,-0.5,-1))
x$NPV.Two <- ifelse(x$two<200,1.1,ifelse(x$two<140,-0.5,-1))
```

```{r}
x %>% filter(a1c<6.5) %>% sample_n(size=10000,weight = sample.ogtt.weight,replace=TRUE) %>% ggplot()+ geom_point(aes(x=PPV.DM.a1c,y=PPV.DM.Min,color=DM)) + geom_abline(aes(slope=1,intercept=0)) + facet_wrap(~DM)

theme.1 <- theme(axis.text=element_text(size=8),
            axis.title=element_text(size=12),
            plot.tag.position = c(0.01,0.99),
            plot.tag = element_text(size=20),
            plot.title = element_text(hjust = 0.5,size=18)) 

plt.ppv.dm <- x %>% filter(a1c<6.5 & a1c>4.0) %>% sample_n(size=10000,weight = sample.ogtt.weight,replace=TRUE) %>% mutate(a1c_group = cut(a1c, seq(3.3, 7, 0.4))) %>% group_by(a1c_group,DM) %>% dplyr::summarise(DM=DM,PPV.DM.Min=PPV.DM.Min,PPV.DM.a1c = mean(PPV.DM.a1c,na.rm=TRUE)) %>% 
  ggplot() + 
  geom_boxplot(aes(x=a1c_group,y=PPV.DM.Min,color=DM,shape="Model")) + 
  geom_point(aes(x=a1c_group,y=PPV.DM.a1c,shape="A1c",color=DM),size=4,position=position_dodge(width=0.75)) +
  scale_shape_manual(name = "Method", values = c(15,1), labels=c("A1c","Model")) + #values = c("A1c" = 15,"Min" = 1)) +
  guides(shape = guide_legend(override.aes = list(color = "black")))  + 
  scale_color_manual(name="Diabetes Diagnosis", labels=c("2hG < 200 mg/dL","2hG ≥ 200 mg/dL"),values=c("red","blue")) + 
  guides(color = guide_legend(override.aes = list(linetype = 0, color = c("red","blue")))) + 
  xlab("A1c Group") + ylab("Positive Predictive Value") ;print(plt.ppv.dm)

plt.npv.dm <- x %>% filter(a1c<6.5 & a1c>4.0) %>% sample_n(size=10000,weight = sample.ogtt.weight,replace=TRUE) %>% mutate(a1c_group = cut(a1c, seq(3.3, 7, 0.4))) %>% group_by(a1c_group) %>% dplyr::summarise(DM=DM,NPV.DM.Min=NPV.DM.Min,NPV.DM.a1c = mean(NPV.DM.a1c,na.rm=TRUE)) %>% 
  ggplot() + 
  geom_boxplot(aes(x=a1c_group,y=NPV.DM.Min,color=DM,shape="Model")) + 
  geom_point(aes(x=a1c_group,y=NPV.DM.a1c,shape="A1c",color=DM),size=4,position=position_dodge(width=0.75)) +
  scale_shape_manual(name = "Method", values = c(15,1), labels=c("A1c","Model")) + #values = c("A1c" = 15,"Min" = 1)) +
  guides(shape = guide_legend(override.aes = list(color = "black")))  + 
  scale_color_manual(name="Diabetes Diagnosis", labels=c("2hG < 200 mg/dL","2hG ≥ 200 mg/dL"),values=c("red","blue")) + 
  guides(color = guide_legend(override.aes = list(linetype = 0, color = c("red","blue")))) + 
  xlab("A1c Group") + ylab("Negative Predictive Value") 


plt.ppv.pdm <- x %>% filter(a1c<5.7 & a1c>4.0) %>% sample_n(size=10000,weight = sample.ogtt.weight,replace=TRUE) %>% mutate(a1c_group = cut(a1c, seq(3.3, 5.7, 0.4))) %>% group_by(a1c_group) %>% dplyr::summarise(PDM=PDM,PPV.PDM.Min=PPV.PDM.Min,PPV.PDM.a1c = mean(PPV.PDM.a1c,na.rm=TRUE)) %>% 
  ggplot() + 
  geom_boxplot(aes(x=a1c_group,y=PPV.PDM.Min,color=PDM,shape="Model")) + 
  geom_point(aes(x=a1c_group,y=PPV.PDM.a1c,shape="A1c",color=PDM),size=4,position=position_dodge(width=0.75)) +
  scale_shape_manual(name = "Method", values = c(15,1), labels=c("A1c","Model")) + #values = c("A1c" = 15,"Min" = 1)) +
  guides(shape = guide_legend(override.aes = list(color = "black")))  + 
  scale_color_manual(name="Pre-Diabetes Diagnosis", labels=c("2hG < 140 mg/dL","140 ≤ 2hG < 200 mg/dL"),values=c("orange","purple")) + 
  guides(color = guide_legend(override.aes = list(linetype = 0, color = c("orange","purple")))) + 
  xlab("A1c Group") + ylab("Positive Predictive Value") 


plt.npv.pdm <-x %>% filter(a1c<5.7 & a1c>4.0) %>% sample_n(size=10000,weight = sample.ogtt.weight,replace=TRUE) %>% mutate(a1c_group = cut(a1c, seq(3.3, 5.7, 0.4))) %>% group_by(a1c_group) %>% dplyr::summarise(PDM=PDM,NPV.PDM.Min=NPV.PDM.Min,NPV.PDM.a1c = mean(NPV.PDM.a1c,na.rm=TRUE)) %>% 
  ggplot() + 
  geom_boxplot(aes(x=a1c_group,y=NPV.PDM.Min,color=PDM,shape="Model")) + 
  geom_point(aes(x=a1c_group,y=NPV.PDM.a1c,shape="A1c",color=PDM),size=4,position=position_dodge(width=0.75)) +
  scale_shape_manual(name = "Method", values = c(15,1), labels=c("A1c","Model")) + #values = c("A1c" = 15,"Min" = 1)) +
  guides(shape = guide_legend(override.aes = list(color = "black")))  + 
  scale_color_manual(name="Pre-Diabetes Diagnosis", labels=c("2hG < 140 mg/dL","140 ≤ 2hG < 200 mg/dL"),values=c("orange","purple")) + 
  guides(color = guide_legend(override.aes = list(linetype = 0, color = c("orange","purple")))) + 
  xlab("A1c Group") + ylab("Negative Predictive Value") 

legend.1 <- cowplot::get_legend(plt.ppv.dm + theme(legend.direction = "horizontal",legend.spacing.y=unit(0,"in"),legend.margin=unit(0,"in")))
legend.2 <- cowplot::get_legend(plt.ppv.pdm + theme(legend.direction = "horizontal",legend.spacing.y=unit(0,"in"),legend.margin=unit(0,"in")))

grid.arrange(nrow=4,heights=c(3,0.5,3,0.5),
  arrangeGrob(ncol=2,
              plt.ppv.dm + theme.1  + theme(legend.position="none") + labs(tag="A")  ,
              plt.npv.dm + theme.1  + theme(legend.position="none") + labs(tag="B") ),
  legend.1,
  arrangeGrob(ncol=2,
              plt.ppv.pdm + theme.1  + theme(legend.position="none") + labs(tag="C"),
              plt.npv.pdm + theme.1  + theme(legend.position="none") + labs(tag="D")),
  legend.2
) %>% ggsave(file="~/Dropbox/NHANES manuscript/figures/PPV-plots.bmp",height = 7,width = 7,units = "in")

 
  

```


```{r}
plot.ppv.comparison <- x %>% sample_n(size=10000,weight = sample.ogtt.weight,replace=TRUE) %>% ggplot() + geom_point(aes(x=PPV.DM.Min,y=PPV.PDM.Min)) + 
  geom_abline(aes(slope=1,intercept=0),linetype='dashed') + 
  xlab("PPV of Diabetes by Model") + 
  ylab("PPV of Pre-Diabetes by Model")+
  xlim(c(0,1)) + ylim(c(0,1)) ; print(plot.ppv.comparison)


x %>% sample_n(size=10000,weight = sample.ogtt.weight,replace=TRUE) %>% ggplot()+ geom_point(aes(x=a1c,y=PPV.DM.Min))
plot.ppv.comparison <- x %>% sample_n(size=10000,weight = sample.ogtt.weight,replace=TRUE)  %>% ggplot() + geom_point(aes(x=PPV.DM.Min,y=PPV.PDM.Min)) + 
  geom_abline(aes(slope=1,intercept=0),linetype='dashed') + 
  xlab("PPV of Diabetes by Model") + 
  ylab("PPV of Pre-Diabetes by Model")+
  xlim(c(0,1)) + ylim(c(0,1)) ; print(plot.ppv.comparison)
  
#ggsave(file="~/Dropbox/NHANES manuscript/PPV.comparison.jpg",plot=plot.ppv.comparison)

x %>% sample_n(size=10000,weight = sample.ogtt.weight,replace=TRUE) %>% ggplot()+ geom_point(aes(x=a1c,y=1-NPV.DM.Min))
plot.ppv.comparison <- x %>% sample_n(size=10000,weight = sample.ogtt.weight,replace=TRUE)  %>% ggplot() + geom_point(aes(x=PPV.DM.Min,y=PPV.PDM.Min)) + 
  geom_abline(aes(slope=1,intercept=0),linetype='dashed') + 
  xlab("PPV of Diabetes by Model") + 
  ylab("PPV of Pre-Diabetes by Model")+
  xlim(c(0,1)) + ylim(c(0,1)) ; print(plot.ppv.comparison)


x %>% filter(a1c<6.5) %>% sample_n(size=10000,weight = sample.ogtt.weight,replace=TRUE) %>% ggplot()+ geom_point(aes(x=a1c,y=1-NPV.DM.Min)) + geom_point(aes(x=a1c,y=1-NPV.DM.a1c),color='red')
plot.npv.comparison <- x %>% sample_n(size=10000,weight = sample.ogtt.weight,replace=TRUE) %>% ggplot() + geom_point(aes(x=1-NPV.DM.Min,y=1-NPV.PDM.Min)) + 
  geom_abline(aes(slope=1,intercept=0),linetype='dashed') + 
  xlab("NPV of Diabetes by Model") + 
  ylab("NPV of Pre-Diabetes by Model")+
  xlim(c(0,1)) + ylim(c(0,1)) ; print(plot.npv.comparison)


x %>% filter(PPV.DM.Min<0.5) %>% select(PPV.PDM.Min) %>% min()
x %>% select(PPV.DM.Min) %>% min()
```


```{r Alluvial PPV 1}
library(ggalluvial)
library(plyr)
xx <- x %>% filter(a1c<6.5) %>% sample_n(size=10000,weight = sample.ogtt.weight,replace=TRUE) %>% select(matches("PPV|NPV"))

# Use lapply to categorize each column
ordinal_sets <- lapply(xx, function(column) cut(column, breaks = c(-1,-0.6,0,0.06,0.39,0.7,1,1.5) , labels = FALSE, include.lowest = TRUE))

# Convert the list to a data frame and rename columns
ordinal_sets_df <- as.data.frame(ordinal_sets)
colnames(ordinal_sets_df) <- colnames(xx)

 
ordinal_sets_df  %>%  select(PPV.DM.a1c,PPV.DM.Min,PPV.Two,PPV.DM.NonFasting) %>%  #select(PPV.DM.a1c,PPV.DM.Base,PPV.DM.Fasting,PPV.DM.Full,PPV.DM.Min,PPV.Two) %>% 
  filter(!(PPV.DM.a1c<=4   & PPV.DM.Min<=4 & PPV.Two<=2 & PPV.DM.NonFasting)) %>%  ### This filters values without low PPV diabetes by any condition
  filter(!(PPV.DM.a1c==7  & PPV.Two==7 & PPV.DM.Min==7 & PPV.DM.NonFasting)) %>%   ### THis fileters values definitely with diabetes
  #filter(!(PPV.DM.a1c<=4 & PPV.DM.Base<=4 & PPV.DM.Fasting<=4 & PPV.DM.Full<=4  & PPV.DM.Min<=4 & PPV.Two<=2)) %>% 
  #filter(!(PPV.DM.a1c==7 & PPV.DM.Base==7 & PPV.DM.Fasting==7 & PPV.DM.Full==7 & PPV.Two==7 & PPV.DM.Min==7)) %>%   
  
  mutate(
    across(contains("PPV"), ~ factor(.x, levels = sort(unique(.x)), ordered = TRUE)),
    PPV.a1c = factor(PPV.DM.a1c, levels = c(1,2,3,4,5,6,7)), 
    PPV.NonFasting = factor(PPV.DM.NonFasting, levels = c(1,2,3,4,5,6,7)), 
    #PPV.Fasting = factor(PPV.DM.Fasting, levels = c(1,2,3,4,5,6,7)), 
    #PPV.Full = factor(PPV.DM.Full, levels = c(1,2,3,4,5,6,7)) ,
    PPV.Two = factor(PPV.Two, levels = c(1,2,3,4,5,6,7)),
    PPV.Min = factor(PPV.DM.Min, levels = c(1,2,3,4,5,6,7))
  ) %>% # arrange(PPV.a1c,PPV.Base,PPV.Fasting,PPV.Full,PPV.Min,PPV.Two) %>% 
  ggplot(aes(axis1=PPV.Two, axis2 = PPV.DM.a1c, 
             #axis3 = PPV.DM.Base, axis4 = PPV.DM.Fasting, 
             #axis5 = PPV.DM.Full,
             axis5=PPV.DM.NonFasting,axis6=PPV.Min)) +
  stat_stratum(width=1/4,aes(color=after_stat(stratum))) + 
  stat_flow(aes(fill=PPV.Two),width = 1/4, aes.bind = TRUE,alpha=0.5) +
  scale_x_discrete(limits = c("OGTT","A1c",
                              #"Base","Fasting",#"Full",
                              "Non-Fasting","Min"), expand = c(.05, .05)) +
  labs(y = "Individuals out of 1000", title = "Flow Diagram of Predictions of OGTT-based Diabetes from Models") +
  scale_fill_manual(name="2-hour glucose",labels=c("< 140 mg/dL","140-200 mg/dL","≥200 mg/dL","?"),values=c('blue','green',"purple")) +
  geom_text(stat = "stratum",size=5, aes(color=after_stat(stratum),label=after_stat(revalue(stratum,c("1"="Normal","1"="","2"="Pre-DM","3"="<6%","4"="P(Pre-DM)>P(DM)","5"="39-70%","6"=">70%","7"="DM")))),angle=90) +
  scale_color_manual(name="Positive\nPredictive\nValue",labels=c("Normal","Pre-DM","<6%","P(Pre-DM)>P(DM)","39-70%","70-100%","DM"),values=c("blue","darkgreen","magenta","brown","red","purple","black")) + theme(legend.key = element_rect(color="square")) +
  theme_minimal() + guides(
  color = guide_legend(
    title = "Positive\nPredictive\nValue",
    override.aes = aes(label = "X")
  )
)
```


```{r Alluvial PPV 2}
xx <- x %>% filter(a1c<6.5) %>% sample_n(size=10000,weight = sample.ogtt.weight,replace=TRUE) %>% select(contains("PPV"),contains('a1c'))
a1c.temp <- xx$a1c
xx <- xx %>% select(contains("PPV"))
# Use lapply to categorize each column
ordinal_sets <- lapply(xx, function(column) cut(column, breaks = c(-1,-0.6,0,0.06,0.39,0.7,1,1.5) , labels = FALSE, include.lowest = TRUE))

# Convert the list to a data frame and rename columns
ordinal_sets_df <- as.data.frame(ordinal_sets)
colnames(ordinal_sets_df) <- colnames(xx)

 
ordinal_sets_df  %>%  select(PPV.DM.a1c,PPV.DM.Min,PPV.Two) %>%  #select(PPV.DM.a1c,PPV.DM.Base,PPV.DM.Fasting,PPV.DM.Full,PPV.DM.Min,PPV.Two) %>% 
  filter(!(PPV.DM.a1c<=4   & PPV.DM.Min<=4 & PPV.Two<=2)) %>% 
  filter(!(PPV.DM.a1c==6  & PPV.Two==7 & PPV.DM.Min==6)) %>%   
  #filter(!(PPV.DM.a1c<=4 & PPV.DM.Base<=4 & PPV.DM.Fasting<=4 & PPV.DM.Full<=4  & PPV.DM.Min<=4 & PPV.Two<=2)) %>% 
  #filter(!(PPV.DM.a1c==7 & PPV.DM.Base==7 & PPV.DM.Fasting==7 & PPV.DM.Full==7 & PPV.Two==7 & PPV.DM.Min==7)) %>%   
  
  mutate(
    across(contains("PPV"), ~ factor(.x, levels = sort(unique(.x)), ordered = TRUE)),
    PPV.a1c = factor(PPV.DM.a1c, levels = c(1,2,3,4,5,6,7)), 
    #PPV.Base = factor(PPV.DM.Base, levels = c(1,2,3,4,5,6,7)), 
    #PPV.Fasting = factor(PPV.DM.Fasting, levels = c(1,2,3,4,5,6,7)), 
    #PPV.Full = factor(PPV.DM.Full, levels = c(1,2,3,4,5,6,7)) ,
    PPV.Two = factor(PPV.Two, levels = c(1,2,3,4,5,6,7)),
    PPV.Min = factor(PPV.DM.Min, levels = c(1,2,3,4,5,6,7))
  ) %>% # arrange(PPV.a1c,PPV.Base,PPV.Fasting,PPV.Full,PPV.Min,PPV.Two) %>% 
  ggplot(aes(#axis1=PPV.Two, 
             axis1 = PPV.DM.a1c, 
             #axis3 = PPV.DM.Base, axis4 = PPV.DM.Fasting, 
             #axis5 = PPV.DM.Full,
             axis2 = PPV.DM.Min
             #axis6=PPV.Two
             )) +
  stat_stratum(width=1/4,aes(color=after_stat(stratum))) + 
  stat_flow(aes(fill=PPV.Two),width = 1/4, alpha=0.5) +
  scale_x_discrete(limits = c(#"OGTT",
                              "A1c",
                              #"Base","Fasting",#"Full",
                              "Min"
                              #"OGTT."
                              ), expand = c(.05, .05)) +
  labs(y = "Individuals out of 1000", title = "Flow Diagram of Predictions of OGTT-based Diabetes from Models") +
  scale_fill_manual(name="2-hour glucose",labels=c("< 140 mg/dL","140-200 mg/dL","≥200 mg/dL","?"),values=c('purple','green',"maroon")) +
  geom_text(stat = "stratum",size=5, aes(color=after_stat(stratum),label=after_stat(revalue(stratum,c("1"="Normal","1"="","2"="Pre-DM","3"="<6%","4"="P(Pre-DM)\n>P(DM)","5"="39-70%","6"=">70%","7"="DM")))),angle=00) +
  scale_color_manual(name="Positive\nPredictive\nValue",labels=c("Normal","Pre-DM","<6%","P(Pre-DM)>P(DM)","39-70%","70-100%","DM"),values=c("blue","darkgreen","magenta","brown","red","purple","black")) + theme(legend.key = element_rect(color="square")) +
  theme_minimal() + guides(
  color = guide_legend(
    title = "Positive\nPredictive\nValue",
    override.aes = aes(label = "X")
  )
)
```

```{r Alluvial PPV 3}
library(ggalluvial)
library(plyr)
xx <- x %>% filter(a1c<6.5) %>% sample_n(size=10000,weight = sample.ogtt.weight,replace=TRUE) %>% select(matches("PPV|NPV")) %>% mutate(PPV.Two.2 = ifelse(PPV.Two<1.1,-1,1.1))

# Use lapply to categorize each column
ordinal_sets <- lapply(xx, function(column) cut(column, breaks = c(-1,-0.6,0,0.06,0.39,0.7,1,1.5) , labels = FALSE, include.lowest = TRUE))

# Convert the list to a data frame and rename columns
ordinal_sets_df <- as.data.frame(ordinal_sets)
colnames(ordinal_sets_df) <- colnames(xx)

 
ordinal_sets_df  %>%  select(PPV.DM.a1c,PPV.DM.Min,PPV.Two,PPV.DM.NonFasting,PPV.Two.2) %>%  #select(PPV.DM.a1c,PPV.DM.Base,PPV.DM.Fasting,PPV.DM.Full,PPV.DM.Min,PPV.Two) %>% 
  #filter(!(PPV.DM.a1c<=4   & PPV.DM.Min<=4 & PPV.Two<=2 & PPV.DM.NonFasting)) %>%  ### This filters values without low PPV diabetes by any condition
  #filter(!(PPV.DM.a1c==7  & PPV.Two==7 & PPV.DM.Min==7 & PPV.DM.NonFasting)) %>%   ### THis fileters values definitely with diabetes
  #filter(!(PPV.DM.a1c<=4 & PPV.DM.Base<=4 & PPV.DM.Fasting<=4 & PPV.DM.Full<=4  & PPV.DM.Min<=4 & PPV.Two<=2)) %>% 
  #filter(!(PPV.DM.a1c==7 & PPV.DM.Base==7 & PPV.DM.Fasting==7 & PPV.DM.Full==7 & PPV.Two==7 & PPV.DM.Min==7)) %>%   
  
  mutate(
    across(contains("PPV"), ~ factor(.x, levels = sort(unique(.x)), ordered = TRUE)),
    PPV.a1c = factor(PPV.DM.a1c, levels = c(1,2,3,4,5,6,7)), 
    PPV.NonFasting = factor(PPV.DM.NonFasting, levels = c(1,2,3,4,5,6,7)), 
    #PPV.Fasting = factor(PPV.DM.Fasting, levels = c(1,2,3,4,5,6,7)), 
    #PPV.Full = factor(PPV.DM.Full, levels = c(1,2,3,4,5,6,7)) ,
    PPV.Two.2 = factor(PPV.Two.2,levels=c(1,2,3,4,5,6,7)),
    PPV.Two = factor(PPV.Two, levels = c(1,2,3,4,5,6,7)),
    PPV.Min = factor(PPV.DM.Min, levels = c(1,2,3,4,5,6,7))
  ) %>% # arrange(PPV.a1c,PPV.Base,PPV.Fasting,PPV.Full,PPV.Min,PPV.Two) %>% 
  ggplot(aes(axis2 = PPV.DM.a1c, 
             #axis3 = PPV.DM.Base, axis4 = PPV.DM.Fasting, 
             #axis5 = PPV.DM.Full,
             axis5=PPV.DM.NonFasting,
             axis6=PPV.Min)) +
  stat_stratum(width=1/4,aes(color=after_stat(stratum))) + 
  stat_flow(aes(fill=PPV.Two.2),width = 1/4, aes.bind = TRUE,alpha=0.5) +
  scale_x_discrete(limits = c("A1c",
                              #"Base","Fasting",#"Full",
                              "Non-Fasting","Min"), expand = c(.05, .05)) +
  labs(y = "Individuals out of 1000", title = "Flow Diagram of Predictions of OGTT-based Diabetes from Models") +
  scale_fill_manual(name="2-hour glucose",labels=c("< 200 mg/dL","≥200 mg/dL"),values=c('green','blue',"purple")) +
  geom_text(stat = "stratum",size=5, aes(color=after_stat(stratum),label=after_stat(revalue(stratum,c("1"="Normal","1"="","2"="Pre-DM","3"="<6%","4"="P(Pre-DM)>P(DM)","5"="39-70%","6"=">70%","7"="DM")))),angle=90) +
  scale_color_manual(name="Positive\nPredictive\nValue",labels=c("Normal","Pre-DM","<6%","P(Pre-DM)>P(DM)","39-70%","70-100%","DM"),values=c("blue","darkgreen","magenta","brown","red","purple","black")) +
  theme(legend.key = element_rect(color="square")) +
  theme_minimal() + 
  guides(
  color = guide_legend(
    title = "Positive\nPredictive\nValue",
    override.aes = aes(label = "X")
  )
)
```


```{r PPV Box and Whiskers}
xx %>% mutate(PPV.Two = as.factor(PPV.Two)) %>% ggplot()+ geom_point(aes(x=PPV.DM.a1c,y=PPV.DM.Min,color=PPV.Two)) + geom_abline(aes(slope=1,intercept=0))  + facet_wrap(~PPV.Two)

xx %>% ggplot()+ geom_point(aes(x=PPV.DM.a1c,y=PPV.DM.Min-PPV.DM.a1c,color=as.factor(PPV.Two))) #+ geom_abline(aes(slope=1,intercept=0))
 
xx$a1c <- a1c.temp

cutpoints = c(4,5.7,5.8,5.9,6,6.1,6.2,6.3,6.4)
## cut(PPV.DM.a1c, breaks = cutpoints, include.lowest = TRUE)

x3 <- xx %>% mutate(PPV.Two = as.factor(PPV.Two))%>% 
  mutate(PPV.Two = revalue(PPV.Two,c("-1"= "Normal","-0.5"="Pre-Diabetes","1.1"="Diabetes"))) %>% 
  mutate(a1c_cut = factor(cut(a1c,breaks=cutpoints,include.lowest = TRUE,))) 

x4 <- x3 %>% filter(a1c<5.3 )  %>% dplyr::summarise(
  PPV.DM.a1c = mean(PPV.DM.a1c),
  PPV.DM.Min = PPV.DM.Min,
  PPV.PDM.a1c = mean(PPV.DM.a1c),
  PPV.PDM.Min = PPV.PDM.Min,
  PPV.Two = PPV.Two,
  a1c = a1c,
  a1c_cut = a1c_cut,
) 


plot.ppv <- x3  %>% filter(a1c>=5.7) %>% bind_rows(x4) %>% mutate(A1C = if_else(a1c>=5.7,as.character(a1c),"(4,5.7]") )  %>%
  ggplot()+ geom_boxplot(aes(x=as.factor(A1C),y=PPV.DM.Min,fill=PPV.Two)) +# facet_wrap(~a1c_cut,scales="free_x") +
  geom_boxplot(aes(x=as.factor(A1C),y=PPV.DM.a1c),outlier.shape=NA,linetype="solid",color='blue')  + 
  geom_abline(aes(slope=0,intercept=0,color="PPV.DM.A1c"),linetype="solid" )+ scale_color_manual(name="",values=c('PPV.DM.A1c'='blue'),labels=c('PPV.DM.A1c'='PPV for\nDiabetes\ngiven A1c')) + labs(title="PPV for Diabetes stratified by A1c",fill="2-hour\nGlucose\nDiagnosis") + xlab("A1c") + ylab("PPV for Diabetes by Model") + 
  scale_fill_manual(values = c("Normal" = "purple", "Pre-Diabetes" = "green", "Diabetes" = "maroon"))  +
  #scale_color_manual(values = c("Normal" = "blue", "Pre-Diabetes" = "green", "Diabetes" = "maroon")) +
  theme_minimal(); print(plot.ppv)

ggsave(file="~/Dropbox/NHANES manuscript/Plot-PPV.jpg",plot=plot.ppv)



```



```{r}

xx <- x %>% filter(a1c<6.5) %>% sample_n(size=10000,weight = sample.ogtt.weight,replace=TRUE) %>% select(contains("PPV"))


# Load necessary packages
library(tidyverse)

# Sample data (assuming df is already defined and loaded)
# df <- read_csv("your_data.csv")

# Define the cutpoints for X
cutpoints <- seq(0,1, length.out = 21)

# Create a new column in the dataframe indicating the cutpoint range
xx <- xx %>%
  mutate(X_cut = cut(PPV.DM.a1c, breaks = cutpoints, include.lowest = TRUE)) %>% 
  mutate(X_cut = droplevels(X_cut)) %>% mutate(X_cut_num = as.numeric(X_cut)) %>% 
  mutate(PPV.Two = factor(PPV.Two)) %>% 
  mutate(PPV.Two = revalue(PPV.Two,c("-1"= "Normal","-0.5"="Pre-Diabetes","1.1"="Diabetes")))

xxx <- xx %>% group_by(X_cut) %>% dplyr::summarise(mean_PPV = mean(PPV.DM.a1c)) 

xxx <- xx %>% left_join(xxx,join_by(X_cut)) %>% ungroup()

# Plot the boxplots using ggplot
ggplot() +
  geom_boxplot(data=xxx, aes(x = X_cut, y = PPV.DM.Min, fill = as.factor(PPV.Two) ) ) +
  geom_segment(data=xxx %>% select(X_cut_num,mean_PPV) %>% unique(),aes(x=X_cut_num-0.5, xend=X_cut_num+0.5, y=mean_PPV,yend=mean_PPV),linetype="dashed") + 
  #facet_wrap(~ as.factor(X_cut), scales = "free") +
  labs(x = "PPV for Diabetes given A1c", y = "PPV for Diabetes given Min Model", fill = "Diagnosis") +
  theme_minimal() +
  theme(legend.position = "right") 




xx <- xx %>%
  mutate(X_cut = cut(PPV.PDM.a1c, breaks = cutpoints, include.lowest = TRUE)) %>% 
  mutate(X_cut = droplevels(X_cut)) %>% mutate(X_cut_num = as.numeric(X_cut)) %>% 
  mutate(PPV.Two = factor(PPV.Two)) %>% 
  mutate(PPV.Two = revalue(PPV.Two,c("-1"= "Normal","-0.5"="Pre-Diabetes","1.1"="Diabetes")))

xxx <- xx %>% group_by(X_cut) %>% dplyr::summarise(mean_PPV = mean(PPV.PDM.a1c)) 

xxx <- xx %>% left_join(xxx,join_by(X_cut)) %>% ungroup()

# Plot the boxplots using ggplot
ggplot() +
  geom_boxplot(data=xxx, aes(x = X_cut, y = PPV.PDM.Min, fill = as.factor(PPV.Two) ) ) +
  geom_segment(data=xxx %>% select(X_cut_num,mean_PPV) %>% unique(),aes(x=X_cut_num-0.5, xend=X_cut_num+0.5, y=mean_PPV,yend=mean_PPV),linetype="dashed") + 
  #facet_wrap(~ as.factor(X_cut), scales = "free") +
  labs(x = "PPV for Pre-Diabetes given A1c", y = "PPV for Pre-Diabetes given Min Model", fill = "Diagnosis") +
  theme_minimal() +
  theme(legend.position = "right") 

```



```{r}
### Sensitivity = TPR
### Specificity = 1 - FPR

df.stat.2 %>% mutate() 


office_test
int.resample.df <- resample(seq(1,dim(df %>% drop_na(two,a1c,sample.ogtt.weight))[1]),probs=sample.ogtt.weight/sum(sample.ogtt.weight),size=10000)



mytheme <- gridExtra::ttheme_default(
    core = list(fg_params=list(cex = 0.6)),
    colhead = list(fg_params=list(cex = 0.5)),
    rowhead = list(fg_params=list(cex = 0.5)))

df.stats.pdm.grob <- df.stats[1:7,] %>% tableGrob(theme=mytheme)
df.stats.dm.grob <- df.stats[8:14,] %>% tableGrob(theme=mytheme)

boxplot.table.stats<- df %>% drop_na(sample.ogtt.weight,a1c,two) %>% filter(a1c<7) %>% sample_n(size=100000,weight = sample.ogtt.weight,replace=TRUE)  %>% mutate(a1c_group = cut(a1c, seq(3.3, 7, 0.4)) ) %>% group_by(a1c_group) %>% summarise(PreDM = round(sum(two>=140 & two < 200)/sum(two>0),2),DM = round(sum(two > 200)/sum(two>0),2))

boxplot.table.stats.grob <- boxplot.table.stats[2:9,]  %>% tableGrob(theme=mytheme)

set.seed(1234)
df %>% drop_na(sample.ogtt.weight,a1c,two) %>% filter(a1c<7) %>% sample_n(size=100000,weight = sample.ogtt.weight,replace=TRUE)  %>% mutate(a1c_group = cut(a1c, seq(3.3, 7, 0.4)) )  %>% ggplot(aes(x= a1c_group, y = two))   + geom_boxplot(alpha=0.9) + geom_hline(aes(yintercept=140),color='red')+ geom_hline(aes(yintercept=200),color='red') + xlab('A1c Range')+ ylab('2-hour Glucose') + annotation_custom(boxplot.table.stats.grob,xmin=0,xmax=3.5,ymin=250,ymax=490) 



```




```{r}
# df.small <- df.small %>% filter(Age > 50) 
# filter.string <- "Age>50"

# df.small <- df.small %>% mutate(BMI = Weight/(Height.Stand^2)*100*100) %>% filter(BMI>25) %>% select(-BMI)
# filter.string <- "BMI>25"
# 
# df.small <- df.small %>% mutate(BMI = Weight/(Height.Stand^2)*100*100) %>% filter(BMI>30) %>% select(-BMI)
# filter.string <- "BMI>30"
# 
# df.small <- df.small %>% mutate(BMI = Weight/(Height.Stand^2)*100*100) %>% filter(BMI>35) %>% select(-BMI)
# filter.string <- "BMI>35"
# 
# df.small <- df.small %>% filter(SBP > 130)
# filter.string <- "SBP>130"
# 
# df.small <- df.small %>% filter(ggt > 40)
# filter.string <- "ggt>40"
# 
# df.small <- df.small %>% filter((Waist.Circ > 100 & Gender=="Male" )| (Waist.Circ > 90 & Gender=="Female" ))  #cm
# filter.string <- "WC>100"
#
#df.small <- df.small %>% filter((Waist.Circ > 110 & Gender=="Male" )| (Waist.Circ > 105 & Gender=="Female" ))  #cm
#filter.string <- "WC>110"

df.boxplot <- df %>% drop_na(sample.ogtt.weight,a1c,two) %>% filter(a1c<6.5 & a1c>=3.7 ) %>% sample_n(size=100000,weight = sample.ogtt.weight,replace=TRUE)  %>% mutate(a1c_group = cut(a1c, seq(4.1, 7, 0.4)) )   %>% mutate(BMI = Weight/(Height.Stand^2)*100*100) %>% mutate(FIB4=ast/sqrt(alt)*Age/plt) %>% drop_na(a1c_group)

ggplot()   + geom_boxplot(data=df.boxplot,aes(x= a1c_group, y = two),alpha=0.9,position= position_nudge(x=-0.3),width=0.1) + 
  geom_boxplot(data=df.boxplot %>% filter(SBP>130),aes(x= a1c_group, y = two),alpha=0.1,color='blue',position= position_nudge(x=-0.2),width=0.1) + 
  geom_boxplot(data=df.boxplot %>% filter(Age>50),aes(x= a1c_group, y = two),alpha=0.1,color='green',position= position_nudge(x=-0.1),width=0.1) + 
  geom_boxplot(data=df.boxplot  %>% filter(BMI>25 & BMI<=30),aes(x= a1c_group, y = two),alpha=0.1,color='red',position= position_nudge(x=0),width=0.1) + 
  geom_boxplot(data=df.boxplot %>% filter(BMI>30 & BMI<=35),aes(x= a1c_group, y = two),alpha=0.1,color='purple',position= position_nudge(x=0.1),width=0.1) + 
  geom_boxplot(data=df.boxplot %>% filter(BMI>35 ),aes(x= a1c_group, y = two),alpha=0.1,color='orange',position= position_nudge(x=0.2),width=0.1) + 
  geom_boxplot(data=df.boxplot %>% filter(FIB4>2),aes(x= a1c_group, y = two),alpha=0.1,color='cyan',position= position_nudge(x=0.3),width=0.1) + 
  #geom_boxplot(data=df.boxplot %>% filter(SBP>130),aes(x= a1c_group, y = two),alpha=0.1,color='blue',position= position_nudge(x=0.2),width=0.1) + 
  
  geom_hline(aes(yintercept=140),color='red')+ geom_hline(aes(yintercept=200),color='red') + xlab('A1c Range')+ ylab('2-hour Glucose') + annotation_custom(boxplot.table.stats.grob,xmin=0,xmax=3.5,ymin=250,ymax=490) 

colors <- c(
  "All" = "black",
  "Waist: Overweight" = "lightblue",
  "Waist: Obese" = "blue",
  "BMI: Overweight" = "lightgreen",
  "BMI: Obese" = "green",
  "BMI: Obese Class 2" = "darkgreen",
  "FIB4: 1.3-2" = "magenta",
  "FIB4 > 2.67" = "red",
  "Age 50-60" = "orange",
  "Age > 60" = "darkorange",
  "SBP > 140" = "purple",
  "Plt < 150" = "grey",
  "GGT > 40" = "brown"
)



# Define the factor levels
levels_order <- c(
  "All",
  "Waist: Overweight",
  "Waist: Obese",
  "BMI: Overweight",
  "BMI: Obese",
  "BMI: Obese Class 2",
  "FIB4: 1.3-2",
  "FIB4 > 2.67",
  "Age 50-60",
  "Age > 60",
  "SBP > 140",
  "Plt < 150",
  "GGT > 40"
)
box.width=0.07
ggplot() +
  geom_boxplot(data = df.boxplot, aes(x = a1c_group, y = two, color = factor("All", levels = levels_order)), alpha = 0.9, position = position_nudge(x = -0.6 * box.width * 10), width = box.width * 0.95) +
  geom_boxplot(data = df.boxplot %>% filter((Waist.Circ > 90 & Gender == "Female" & Waist.Circ <= 105) | (Waist.Circ > 100 & Gender == "Male" & Waist.Circ <= 110)), aes(x = a1c_group, y = two, color = factor("Waist: Overweight", levels = levels_order)), alpha = 0.1, position = position_nudge(x = -0.5 * box.width * 10), width = box.width * 0.95) +
  geom_boxplot(data = df.boxplot %>% filter((Waist.Circ > 105 & Gender == "Female") | (Waist.Circ > 110 & Gender == "Male")), aes(x = a1c_group, y = two, color = factor("Waist: Obese", levels = levels_order)), alpha = 0.1, position = position_nudge(x = -0.4 * box.width * 10), width = box.width * 0.95) +
  geom_boxplot(data = df.boxplot %>% filter(BMI > 25 & BMI <= 30), aes(x = a1c_group, y = two, color = factor("BMI: Overweight", levels = levels_order)), alpha = 0.1, position = position_nudge(x = -0.3 * box.width * 10), width = box.width * 0.95) +
  geom_boxplot(data = df.boxplot %>% filter(BMI > 30 & BMI <= 35), aes(x = a1c_group, y = two, color = factor("BMI: Obese Class 1", levels = levels_order)), alpha = 0.1, position = position_nudge(x = -0.2 * box.width * 10), width = box.width * 0.95) +
  geom_boxplot(data = df.boxplot %>% filter(BMI > 35), aes(x = a1c_group, y = two, color = factor("BMI: Obese Class 2", levels = levels_order)), alpha = 0.1, position = position_nudge(x = -0.1 * box.width * 10), width = box.width * 0.95) +
  geom_boxplot(data = df.boxplot %>% filter(FIB4 > 1.3 & FIB4 <= 2), aes(x = a1c_group, y = two, color = factor("FIB4: 1.3-2", levels = levels_order)), alpha = 0.1, position = position_nudge(x = 0 * box.width * 10), width = box.width * 0.95) +
  geom_boxplot(data = df.boxplot %>% filter(FIB4 > 2), aes(x = a1c_group, y = two, color = factor("FIB4: ≥2", levels = levels_order)), alpha = 0.1, position = position_nudge(x = 0.1 * box.width * 10), width = box.width * 0.95) +
  geom_boxplot(data = df.boxplot %>% filter(Age > 50 & Age < 60), aes(x = a1c_group, y = two, color = factor("Age 50-60", levels = levels_order)), alpha = 0.1, position = position_nudge(x = 0.2 * box.width * 10), width = box.width * 0.95) +
  geom_boxplot(data = df.boxplot %>% filter(Age > 60), aes(x = a1c_group, y = two, color = factor("Age > 60", levels = levels_order)), alpha = 0.1, position = position_nudge(x = 0.3 * box.width * 10), width = box.width * 0.95) +
  geom_boxplot(data = df.boxplot %>% filter(SBP > 130), aes(x = a1c_group, y = two, color = factor("SBP > 130", levels = levels_order)), alpha = 0.1, position = position_nudge(x = 0.4 * box.width * 10), width = box.width * 0.95) +
  geom_boxplot(data = df.boxplot %>% filter(plt < 150), aes(x = a1c_group, y = two, color = factor("Plt < 150", levels = levels_order)), alpha = 0.1, position = position_nudge(x = 0.5 * box.width * 10), width = box.width * 0.95) +
  geom_boxplot(data = df.boxplot %>% filter(ggt > 40), aes(x = a1c_group, y = two, color = factor("GGT > 40", levels = levels_order)), alpha = 0.1, position = position_nudge(x = 0.6 * box.width * 10), width = box.width * 0.95) +
  geom_hline(aes(yintercept = 140), color = 'red', linetype = 'dashed') +
  geom_hline(aes(yintercept = 200), color = 'red', linetype = 'dashed') +
  xlab('A1c Range') +
  ylab('2-hour Glucose') +
  labs(color = "Subset") +
  scale_color_manual(values = colors)
```


```{r}
# Load necessary packages
library(tidyverse)

# Sample data (assuming df is already defined and loaded)
# df <- read_csv("your_data.csv")

# Define the function to calculate the p-value from the ANOVA
calculate_p_value <- function(df, cutpoint_col, x) {
  # Drop missing values
  df_clean <- df %>% drop_na(two, a1c, sample.ogtt.weight)
  
  # Dynamically construct the formulas
  formula1 <- as.formula(paste("two ~ a1c + (", cutpoint_col, " >= ", x, ")"))
  formula2 <- as.formula(paste("two ~ a1c * (", cutpoint_col, " < ", x, ")"))
  
  # Fit the linear models
  model1 <- lm(formula1, data = df_clean)
  model2 <- lm(formula2, data = df_clean)
  
  # Perform ANOVA and extract the p-value
  p_value <- anova(model1, model2)[2, "Pr(>F)"]
  
  return(p_value)
}



# Define a function to find the minimum p-value for a range of cutpoints
find_min_p_value <- function(df, cutpoint_col, seq_range) {
  # Apply the function to each value in the sequence and store the results in a tibble
  results <- tibble(
    x = seq_range,
    p_value = map_dbl(seq_range, ~ calculate_p_value(df, cutpoint_col, .x))
  )
}
# Define the range of cutpoints
seq_range <- seq(5, 16, 0.5)

# Find the minimum p-value for the column 'hg'
min_p_value_result <- find_min_p_value(df, "hg", seq_range) %>% filter(p_value==min(p_value,na.rm=TRUE))

# Print the results
print(min_p_value_result)
```


```{r}
df.cut <- df %>% drop_na(sample.ogtt.weight,a1c,two) %>% filter(a1c<6.5 & a1c>=3.7 ) %>% sample_n(size=100000,weight = sample.ogtt.weight,replace=TRUE)    %>% mutate(BMI = Weight/(Height.Stand^2)*100*100) %>% mutate(FIB4=ast/sqrt(alt)*Age/plt) 

find_min_p_value(df.cut, "hg", seq(5, 16, 0.5)) %>% filter(p_value==min(p_value,na.rm=TRUE))
find_min_p_value(df.cut, "Age", seq(5, 80, 1)) %>% filter(p_value==min(p_value,na.rm=TRUE))
find_min_p_value(df.cut, "cr", seq(0.1, 5, 0.2)) %>% filter(p_value==min(p_value,na.rm=TRUE))
find_min_p_value(df.cut, "SBP", seq(10, 200, 10)) %>% filter(p_value==min(p_value,na.rm=TRUE))
find_min_p_value(df.cut %>% mutate(BMI = Weight/(Height.Stand^2)*100*100) %>% mutate(FIB4=ast/sqrt(alt)*Age/plt), "BMI", seq(5, 40, 1)) %>% filter(p_value==min(p_value,na.rm=TRUE))
find_min_p_value(df.cut, "FIB4", seq(0, 3, 0.1)) %>% filter(p_value==min(p_value,na.rm=TRUE))

```




```{r Start Boxplots of Summary Data}
df.boxplot <- df %>% drop_na(sample.ogtt.weight,a1c,two) %>% filter(a1c<6.5 & a1c>=3.7 ) %>% sample_n(size=100000,weight = sample.ogtt.weight,replace=TRUE)  %>% mutate(a1c_group = cut(a1c, seq(4.1, 7, 0.8)) )   %>% mutate(BMI = Weight/(Height.Stand^2)*100*100) %>% mutate(FIB4=ast/sqrt(alt)*Age/plt) %>% drop_na(a1c_group)

# Define the factor levels
colors <- c(
  "All" = "black",
  "Cr<2" = "blue",
  "Cr>=2" = "blue",
  "Hgb>=13" = "green",
  "Hgb<13" = "green",
  "BMI<30" = "darkgreen",
  "FIB4≤2.67" = "red",
  "FIB4>2.67" = "red",
  "Age<60" = "darkorange",
  "Age>=60" = "darkorange",
  "SBP<140" = "purple",
  "SBP>=140" = "purple",
  "BMI>=30" = "darkgreen"
)

levels_order <- names(colors)

box.width=0.07
ggplot() +
  geom_boxplot(data = df.boxplot, aes(x = a1c_group, y = two, color = factor("All", levels = levels_order)), 
               alpha = 0.9, position = position_nudge(x = -0.6 * box.width * 10), width = box.width * 0.95) +
  
  geom_boxplot(data = df.boxplot %>% filter(cr<1.1), aes(x = a1c_group, y = two, color = factor("Cr<2", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = -0.5 * box.width * 10), width = box.width * 0.95) +
  
  geom_boxplot(data = df.boxplot %>% filter(cr>=1.1), aes(x = a1c_group, y = two, color = factor("Cr>=2", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = -0.4 * box.width * 10), width = box.width * 0.95) +
  
  geom_boxplot(data = df.boxplot %>% filter(hg>=12.5), aes(x = a1c_group, y = two, color = factor("Hgb>=13", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = -0.3 * box.width * 10), width = box.width * 0.95) +
  
  geom_boxplot(data = df.boxplot %>% filter(hg<12.5), aes(x = a1c_group, y = two, color = factor("Hgb<13", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = -0.2 * box.width * 10), width = box.width * 0.95) +
  
  geom_boxplot(data = df.boxplot %>% filter(BMI < 23), aes(x = a1c_group, y = two, color = factor("BMI<30", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = -0.1 * box.width * 10), width = box.width * 0.95) +
  
  geom_boxplot(data = df.boxplot %>% filter(FIB4 <= 0.7), aes(x = a1c_group, y = two, color = factor("FIB4≤2.67", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0 * box.width * 10), width = box.width * 0.95) +
  
  geom_boxplot(data = df.boxplot %>% filter(FIB4 > 0.7), aes(x = a1c_group, y = two, color = factor("FIB4>2.67", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0.1 * box.width * 10), width = box.width * 0.95) +
  
  geom_boxplot(data = df.boxplot %>% filter(Age < 33), aes(x = a1c_group, y = two, color = factor("Age<60", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0.2 * box.width * 10), width = box.width * 0.95) +
  
  geom_boxplot(data = df.boxplot %>% filter(Age >=33), aes(x = a1c_group, y = two, color = factor("Age>=60", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0.3 * box.width * 10), width = box.width * 0.95) +
  
  geom_boxplot(data = df.boxplot %>% filter(SBP < 120), aes(x = a1c_group, y = two, color = factor("SBP<140", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0.4 * box.width * 10), width = box.width * 0.95) +
  
  geom_boxplot(data = df.boxplot %>% filter(SBP >=120), aes(x = a1c_group, y = two, color = factor("SBP>=140", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0.5 * box.width * 10), width = box.width * 0.95) +
  
  geom_boxplot(data = df.boxplot %>% filter(BMI >=23), aes(x = a1c_group, y = two, color = factor("BMI>=30", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0.6 * box.width * 10), width = box.width * 0.95) +
  
  geom_hline(aes(yintercept = 140), color = 'red', linetype = 'dashed') +
  geom_hline(aes(yintercept = 200), color = 'red', linetype = 'dashed') +
  xlab('A1c Range') +
  ylab('2-hour Glucose') +
  labs(color = "Subset") +
  scale_color_manual(values = colors)
```




```{r}
df.boxplot <- df %>% drop_na(sample.ogtt.weight,a1c,two) %>% filter(a1c<6.5 & a1c>=3.7 ) %>% sample_n(size=100000,weight = sample.ogtt.weight,replace=TRUE)  %>% mutate(a1c_group = cut(a1c, seq(4.9, 7, 0.4)) )   %>% mutate(BMI = Weight/(Height.Stand^2)*100*100) %>% mutate(FIB4=ast/sqrt(alt)*Age/plt) %>% drop_na(a1c_group)

# Define the factor levels
colors <- c(
  "All" = "black",
  "Cr<2" = "blue",
  "Cr≥2" = "blue",
  "Hgb≥13" = "green",
  "Hgb<13" = "green",
  "BMI<30" = "darkgreen",
  "BMI≥30" = "darkgreen",
  "FIB4≤2.67" = "red",
  "FIB4>2.67" = "red",
  "Age<60" = "darkorange",
  "Age≥60" = "darkorange",
  "SBP<140" = "purple",
  "SBP≥140" = "purple"

)

levels_order <- names(colors)

box.width=0.07
ggplot() +
  geom_boxplot(data = df.boxplot, aes(x = a1c_group, y = two, color = factor("All", levels = levels_order)), 
               alpha = 0.9, position = position_nudge(x = -0.6 * box.width * 10), width = box.width * 0.95) +
  
  geom_boxplot(data = df.boxplot %>% filter(cr<2), aes(x = a1c_group, y = two, color = factor("Cr<2", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = -0.5 * box.width * 10), width = box.width * 0.95) +
  
  geom_boxplot(data = df.boxplot %>% filter(cr>=2), aes(x = a1c_group, y = two, color = factor("Cr≥2", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = -0.4 * box.width * 10), width = box.width * 0.95,fill='black') +
  
  geom_boxplot(data = df.boxplot %>% filter(hg>=13), aes(x = a1c_group, y = two, color = factor("Hgb≥13", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = -0.3 * box.width * 10), width = box.width * 0.95) +
  
  geom_boxplot(data = df.boxplot %>% filter(hg<13), aes(x = a1c_group, y = two, color = factor("Hgb<13", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = -0.2 * box.width * 10), width = box.width * 0.95,fill='black') +
  
  geom_boxplot(data = df.boxplot %>% filter(BMI < 30), aes(x = a1c_group, y = two, color = factor("BMI<30", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = -0.1 * box.width * 10), width = box.width * 0.95) +
  geom_boxplot(data = df.boxplot %>% filter(BMI >=30), aes(x = a1c_group, y = two, color = factor("BMI≥30", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0 * box.width * 10), width = box.width * 0.95,fill='black') + 
  geom_boxplot(data = df.boxplot %>% filter(FIB4 <= 2.67), aes(x = a1c_group, y = two, color = factor("FIB4≤2.67", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0.1 * box.width * 10), width = box.width * 0.95) +
  
  geom_boxplot(data = df.boxplot %>% filter(FIB4 > 2.67), aes(x = a1c_group, y = two, color = factor("FIB4>2.67", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0.2 * box.width * 10), width = box.width * 0.95,fill='black') +
  
  geom_boxplot(data = df.boxplot %>% filter(Age < 60), aes(x = a1c_group, y = two, color = factor("Age<60", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0.3 * box.width * 10), width = box.width * 0.95) +
  
  geom_boxplot(data = df.boxplot %>% filter(Age >=60), aes(x = a1c_group, y = two, color = factor("Age≥60", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0.4 * box.width * 10), width = box.width * 0.95,fill='black') +
  
  geom_boxplot(data = df.boxplot %>% filter(SBP < 140), aes(x = a1c_group, y = two, color = factor("SBP<140", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0.5 * box.width * 10), width = box.width * 0.95) +
  
  geom_boxplot(data = df.boxplot %>% filter(SBP >=140), aes(x = a1c_group, y = two, color = factor("SBP≥140", levels = levels_order)), 
               alpha = 0.1, position = position_nudge(x = 0.6 * box.width * 10), width = box.width * 0.95,fill='black') 
```











```{r}
box.width=0.1
ggplot() +
  geom_boxplot(data = df.boxplot, aes(x = a1c_group, y = two, color = factor("All", levels = levels_order)), position = position_nudge(x = -0.3 * box.width * 10), width = box.width * 0.95) +
  #geom_boxplot(data = df.boxplot %>% filter((Waist.Circ > 90 & Gender == "Female" & Waist.Circ <= 105) | (Waist.Circ > 100 & Gender == "Male" & Waist.Circ <= 110)), aes(x = a1c_group, y = two, color = factor("Waist: Overweight", levels = levels_order)), alpha = 0.1, position = position_nudge(x = -0.5 * box.width * 10), width = box.width * 0.95) +
  geom_boxplot(data = df.boxplot %>% filter((Waist.Circ > 105 & Gender == "Female") | (Waist.Circ > 110 & Gender == "Male")), aes(x = a1c_group, y = two, color = factor("Waist: Obese", levels = levels_order)),  position = position_nudge(x = -0.2 * box.width * 10), width = box.width * 0.95) +
  #geom_boxplot(data = df.boxplot %>% filter(BMI > 25 & BMI <= 30), aes(x = a1c_group, y = two, color = factor("BMI: Overweight", levels = levels_order)), alpha = 0.1, position = position_nudge(x = -0.3 * box.width * 10), width = box.width * 0.95) +
  geom_boxplot(data = df.boxplot %>% filter(BMI > 30 ), aes(x = a1c_group, y = two, color = factor("BMI: Obese", levels = levels_order)),  position = position_nudge(x = -0.1 * box.width * 10), width = box.width * 0.95) +
  #geom_boxplot(data = df.boxplot %>% filter(BMI > 35), aes(x = a1c_group, y = two, color = factor("BMI: Obese Class 2", levels = levels_order)), alpha = 0.1, position = position_nudge(x = -0.1 * box.width * 10), width = box.width * 0.95) +
  #geom_boxplot(data = df.boxplot %>% filter(FIB4 > 1.3 & FIB4 <= 2), aes(x = a1c_group, y = two, color = factor("FIB4: 1.3-2", levels = levels_order)), alpha = 0.1, position = position_nudge(x = 0 * box.width * 10), width = box.width * 0.95) +
  geom_boxplot(data = df.boxplot %>% filter(FIB4 > 2.67), aes(x = a1c_group, y = two, color = factor("FIB4 > 2.67", levels = levels_order)),  position = position_nudge(x = 0 * box.width * 10), width = box.width * 0.95) +
  #geom_boxplot(data = df.boxplot %>% filter(Age > 50 & Age < 60), aes(x = a1c_group, y = two, color = factor("Age 50-60", levels = levels_order)), alpha = 0.1, position = position_nudge(x = 0.2 * box.width * 10), width = box.width * 0.95) +
  geom_boxplot(data = df.boxplot %>% filter(Age > 60), aes(x = a1c_group, y = two, color = factor("Age > 60", levels = levels_order)),  position = position_nudge(x = 0.1 * box.width * 10), width = box.width * 0.95) +
  geom_boxplot(data = df.boxplot %>% filter(SBP > 140), aes(x = a1c_group, y = two, color = factor("SBP > 140", levels = levels_order)), position = position_nudge(x = 0.2 * box.width * 10), width = box.width * 0.95) +
  #geom_boxplot(data = df.boxplot %>% filter(plt < 150), aes(x = a1c_group, y = two, color = factor("Plt < 150", levels = levels_order)),  position = position_nudge(x = 0.3 * box.width * 10), width = box.width * 0.95) +
  geom_boxplot(data = df.boxplot %>% filter(ggt > 40), aes(x = a1c_group, y = two, color = factor("GGT > 40", levels = levels_order)),position = position_nudge(x = 0.3 * box.width * 10), width = box.width * 0.95) +
  geom_hline(aes(yintercept = 140), color = 'red', linetype = 'dashed') +
  geom_hline(aes(yintercept = 200), color = 'red', linetype = 'dashed') +
  xlab('A1c Range') +
  ylab('2-hour Glucose') +
  labs(color = "Subset") +
  scale_color_manual(values = colors)







```


```{r}


df %>% drop_na(sample.ogtt.weight,a1c,two) %>% sample_n(size=100000,weight = sample.ogtt.weight,replace=TRUE) %>% dplyr::summarise(DM=sum(a1c>=6.5 | two>=200),undxDM=sum(two>=200 & a1c<6.5),noDM=sum(a1c<6.5 & two<200),OGTT.DM=sum(two>=200),A1c.DM.notOGTT=sum(a1c>=6.5 & two < 200)) %>% mutate(Div = undxDM/OGTT.DM)

df %>% drop_na(sample.ogtt.weight,a1c,two) %>% sample_n(size=100000,weight = sample.ogtt.weight,replace=TRUE)  %>% filter(two >= 200) %>% dplyr::summarise(A1c.PDM = sum(a1c<6.5 & a1c>=5.7)/n(),A1c.norm = sum(a1c<5.7)/n())



df %>% drop_na(sample.ogtt.weight,a1c,two) %>% sample_n(size=100000,weight = sample.ogtt.weight,replace=TRUE)  %>% dplyr::summarise(PDM =sum(a1c>=5.7 & a1c<6.5), PDM.to.DM = sum(a1c>=5.7 & a1c<6.5 & two >=200),Norm.to.DM = sum(a1c<5.7 & two>=200), PDM.to.PDM = sum(a1c>=5.7 & a1c<6.5 & two < 200 & two >= 140),norm = sum(a1c<5.7)) %>% mutate(Div=PDM.to.DM/PDM,Div2=Norm.to.DM/norm)

```

```{r}
# Load the required library
library(ggplot2)

# Assuming your data is in a dataframe called `data`
# Columns: a1c_group (A1c bins), OGTT (2-hour glucose levels), diabetes_status (categorical variable: "no DM", "prediabetes", "diabetes")

f.dm <- function(x){
  if(x >=200){ y="Diabetes" }else if (x < 200 & x >=140){y="Pre-Diabetes"} else {y="Normal"}
  return(y)
}

# Create the dot plot
df %>% drop_na(sample.ogtt.weight,a1c,two) %>% select(a1c,two,sample.ogtt.weight) %>% mutate(diabetes_status = sapply(two,f.dm)) %>% filter(a1c<7) %>% sample_n(size=100000,weight = sample.ogtt.weight,replace=TRUE)  %>% mutate(a1c_group = cut(a1c, seq(3.3, 7, 0.4)) )   %>% 
  ggplot( aes(x = a1c_group, y = two, color = diabetes_status,fill= diabetes_status)) +
  geom_dotplot(binaxis = "y",
               stackdir = "center",
               binwidth = 1,
               dotsize = 0.2,
               stackratio = 0.5) +
  scale_fill_manual(values = c("Normal" = "blue", "Pre-Diabetes" = "green", "Diabetes" = "maroon"))  +
  scale_color_manual(values = c("Normal" = "blue", "Pre-Diabetes" = "green", "Diabetes" = "maroon")) +
  labs(title = "Distribution of OGTT Levels by A1c",
       x = "A1c Range",
       y = "2-hour Glucose Levels",
       fill = "Diabetes Status") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid.major = element_line(color = "gray", linetype = "dashed")
  )


plot.a1c.bins<-df %>% drop_na(sample.ogtt.weight,a1c,two) %>% select(a1c,two,sample.ogtt.weight) %>% mutate(diabetes_status = sapply(two,f.dm)) %>% filter(a1c<10) %>% filter(a1c>4.1) %>% sample_n(size=100000,weight = sample.ogtt.weight,replace=TRUE)  %>% mutate(a1c_group = cut(a1c, seq(3.3, 6.5, 0.8)) )   %>% 
  mutate(diabetes_status=factor(diabetes_status,levels=c("Diabetes","Pre-Diabetes","Normal"))) %>% 
  filter(!is.na(a1c_group)) %>% 
  ggplot( aes(x = a1c_group, y = two, color = diabetes_status,fill= diabetes_status)) +
  geom_dotplot(binaxis = "y",
               stackdir = "center",
               binwidth = 1,
               dotsize = 0.2,
               stackratio = 0.5) +
  scale_fill_manual(values = c("Normal" = "purple", "Pre-Diabetes" = "green", "Diabetes" = "maroon"))  +
  scale_color_manual(values = c("Normal" = "purple", "Pre-Diabetes" = "green", "Diabetes" = "maroon")) +
  labs(title = "Distribution of OGTT Levels by A1c",
       x = "A1c Range",
       y = "2-hour Glucose Levels",
       fill = "2-hour\nGlucose\nDiagnosis",
       color= "2-hour\nGlucose\nDiagnosis") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid.major = element_line(color = "gray", linetype = "dashed")
  );print(plot.a1c.bins)

```


```{r}
df.dot.plot <- df %>% drop_na(sample.ogtt.weight,a1c,two) %>% mutate(diabetes_status = sapply(two,f.dm))  %>% sample_n(size=100000,weight = sample.ogtt.weight,replace=TRUE)  %>% mutate(a1c_group = cut(a1c, seq(3.3, 6.5, 0.4)) ) 

 
ggplot( ) +
  geom_dotplot(data=df.dot.plot,aes(x = a1c_group, y = two, color = diabetes_status),
               binaxis = "y",
               stackdir = "centerwhole",
               binwidth = 1,
               dotsize = 0.2,
               stackratio = 0.5) +
  geom_dotplot(data=df.dot.plot %>% filter(SBP>130),aes(x = a1c_group, y = two),
               binaxis = "y",
               stackdir = "centerwhole",
               binwidth = 1,
               dotsize = 0.5,
               stackratio = 0.5,alpha=0.5) +
  
  scale_color_manual(values = c("no DM" = "blue", "prediabetes" = "green", "diabetes" = "maroon")) +
  labs(title = "Distribution of OGTT Levels by A1c Bin",
       x = "A1c Range",
       y = "2-hour Glucose Levels",
       fill = "Diabetes Status") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid.major = element_line(color = "gray", linetype = "dashed")
  )

```




```{r Loading the Cohort tests}

load("~/Documents/NHANES15-16/2024-12-14_res/NHANES-office-test-layered_wIns_MIN_Age>60_2024.12.12.Rda")
office_test.Age <- office_test

load("~/Documents/NHANES15-16/2024-12-14_res/NHANES-office-test-layered_wIns_MIN_BMI>30_2024.12.12.Rda")
office_test.BMI <- office_test


load("~/Documents/NHANES15-16/2024-12-14_res/NHANES-office-test-layered_wIns_MIN_FIB4>2.67_2024.12.12.Rda")
office_test.FIB4 <- office_test


load("~/Documents/NHANES15-16/2024-12-14_res/NHANES-office-test-layered_wIns_MIN_ggt>40_2024.12.12.Rda")
office_test.GGT <- office_test


load("~/Documents/NHANES15-16/2024-12-14_res/NHANES-office-test-layered_wIns_MIN_SBP>140_2024.12.12.Rda")
office_test.SBP <- office_test


load("~/Documents/NHANES15-16/2024-12-14_res/NHANES-office-test-layered_wIns_MIN_WC>110_2024.12.12.Rda")
office_test.WC <- office_test

load("~/Documents/NHANES15-16/2024-12-14_res/NHANES-office-test-layered_wIns_MIN_all_2024.12.12.Rda")
office_test.All <- office_test

load("~/Documents/NHANES15-16/2024-12-14_res/NHANES-office-test-layered_wIns_MIN_eGFR<60_2024.12.12.Rda")
office_test.eGFR <- office_test

#load("~/Documents/NHANES15-16/NHANES-office-test-layered_wIns_MIN_")
#office_test.eGFR <- office_test

### Load office_test
load(paste0(dir.string,"NHANES-office-test-layered_",filter.string,"_",date.string,".Rda"))

```


```{r Old ROC Figures with All and Subpopulations}

  
yy <- office_test.All
x0.yy.pdm <- yy.pdm <-  factor(yy$two >=140 & yy$two<200)
x0.pdm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.pdm)) %>% mutate(Stat="A1c",Dx="pdm",Cohort="All")
x0.pdm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.pdm))  %>% mutate(Stat="Min",Dx="pdm",Cohort="All")
x0.pdm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.pdm))  %>% mutate(Stat="Full",Dx="pdm",Cohort="All")


yy <- office_test.Age
x1.yy.pdm<-yy.pdm <-  factor(yy$two >=140 & yy$two<200)
x1.pdm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.pdm)) %>% mutate(Stat="A1c",Dx="pdm",Cohort="Age>60")
x1.pdm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.pdm))  %>% mutate(Stat="Min",Dx="pdm",Cohort="Age>60")
x1.pdm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.pdm))  %>% mutate(Stat="Full",Dx="pdm",Cohort="Age>60")


yy <- office_test.BMI
x2.yy.pdm <- yy.pdm <-  factor(yy$two >=140 & yy$two<200)
x2.pdm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.pdm)) %>% mutate(Stat="A1c",Dx="pdm",Cohort="BMI>30")
x2.pdm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.pdm))  %>% mutate(Stat="Min",Dx="pdm",Cohort="BMI>30")
x2.pdm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.pdm))  %>% mutate(Stat="Full",Dx="pdm",Cohort="BMI>30")

yy <- office_test.WC  
x3.yy.pdm <-yy.pdm <-  factor(yy$two >=140 & yy$two<200)
x3.pdm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.pdm)) %>% mutate(Stat="A1c",Dx="pdm",Cohort="WC>110")
x3.pdm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.pdm)) %>% mutate(Stat="Min",Dx="pdm",Cohort="WC>110")
x3.pdm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.pdm))  %>% mutate(Stat="Full",Dx="pdm",Cohort="WC>110")

yy <- office_test.FIB4
x4.yy.pdm <-yy.pdm <-  factor(yy$two >=140 & yy$two<200)
x4.pdm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.pdm)) %>% mutate(Stat="A1c",Dx="pdm",Cohort="FIB4>2.67")
x4.pdm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.pdm)) %>% mutate(Stat="Min",Dx="pdm",Cohort="FIB4>2.67")
x4.pdm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.pdm))  %>% mutate(Stat="Full",Dx="pdm",Cohort="FIB4>2.67")


yy <- office_test.eGFR
x5.yy.pdm <-yy.pdm <-  factor(yy$two >=140 & yy$two<200)
x5.pdm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.pdm)) %>% mutate(Stat="A1c",Dx="pdm",Cohort="eGFR<60")
x5.pdm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.pdm)) %>% mutate(Stat="Min",Dx="pdm",Cohort="eGFR<60")
x5.pdm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.pdm))  %>% mutate(Stat="Full",Dx="pdm",Cohort="eGFR<60")

yy <- office_test.SBP
x6.yy.pdm <- yy.pdm <-  factor(yy$two >=140 & yy$two<200)# %>% as.data.frame() %>% mutate(Stat="A1c",Dx="pdm",Cohort="SBP>140")
x6.pdm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.pdm)) %>% mutate(Stat="A1c",Dx="pdm",Cohort="SBP>140")
x6.pdm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.pdm)) %>% mutate(Stat="Min",Dx="pdm",Cohort="SBP>140")
x6.pdm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.pdm))  %>% mutate(Stat="Full",Dx="pdm",Cohort="SBP>140")




roc.pdm.cohort <-bind_rows(
  x0.pdm.roc.a1c ,
x0.pdm.roc.min,
x0.pdm.roc.full,

x1.pdm.roc.a1c,
x1.pdm.roc.min,
x1.pdm.roc.full,

x2.pdm.roc.a1c,
x2.pdm.roc.min,
x2.pdm.roc.full,

# x3.pdm.roc.a1c,
# x3.pdm.roc.min,

x4.pdm.roc.a1c,
x4.pdm.roc.min,
x4.pdm.roc.full,

x5.pdm.roc.a1c,
x5.pdm.roc.min,
x5.pdm.roc.full,

x6.pdm.roc.a1c,
x6.pdm.roc.min,
x6.pdm.roc.full,

) 


## DM
yy <- office_test.All
yy.dm <-  factor(yy$two >= 200)
x0.dm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.dm)) %>% mutate(Stat="A1c",Dx="DM",Cohort="All")
x0.dm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.dm))  %>% mutate(Stat="Min",Dx="DM",Cohort="All")
x0.dm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.dm))  %>% mutate(Stat="Full",Dx="DM",Cohort="All")

yy <- office_test.Age
yy.dm <-  factor(yy$two >= 200)
x1.dm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.dm)) %>% mutate(Stat="A1c",Dx="DM",Cohort="Age>60")
x1.dm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.dm))  %>% mutate(Stat="Min",Dx="DM",Cohort="Age>60")
x1.dm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.dm))  %>% mutate(Stat="Full",Dx="DM",Cohort="Age>60")

yy <- office_test.BMI
yy.dm <-  factor(yy$two >= 200)
x2.dm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.dm)) %>% mutate(Stat="A1c",Dx="DM",Cohort="BMI>30")
x2.dm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.dm))  %>% mutate(Stat="Min",Dx="DM",Cohort="BMI>30")
x2.dm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.dm))  %>% mutate(Stat="Full",Dx="DM",Cohort="BMI>30")

yy <- office_test.WC  
yy.dm <-  factor(yy$two >= 200)
x3.dm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.dm)) %>% mutate(Stat="A1c",Dx="DM",Cohort="WC>110")
x3.dm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.dm)) %>% mutate(Stat="Min",Dx="DM",Cohort="WC>110")
x3.dm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.dm))  %>% mutate(Stat="Full",Dx="DM",Cohort="WC>110")

yy <- office_test.FIB4
yy.dm <-  factor(yy$two >= 200)
x4.dm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.dm)) %>% mutate(Stat="A1c",Dx="DM",Cohort="FIB4>2.67")
x4.dm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.dm)) %>% mutate(Stat="Min",Dx="DM",Cohort="FIB4>2.67")
x4.dm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.dm))  %>% mutate(Stat="Full",Dx="DM",Cohort="FIB4>2.67")

yy <- office_test.GGT
yy.dm <-  factor(yy$two >= 200)
x5.dm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.dm)) %>% mutate(Stat="A1c",Dx="DM",Cohort="eGFR<60")
x5.dm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.dm)) %>% mutate(Stat="Min",Dx="DM",Cohort="eGFR<60")
x5.dm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.dm))  %>% mutate(Stat="Full",Dx="DM",Cohort="eGFR<60")

yy <- office_test.SBP
yy.dm <-  factor(yy$two >= 200)
x6.dm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.dm)) %>% mutate(Stat="A1c",Dx="DM",Cohort="SBP>140")
x6.dm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.dm)) %>% mutate(Stat="Min",Dx="DM",Cohort="SBP>140")
x6.dm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.dm))  %>% mutate(Stat="Full",Dx="DM",Cohort="SBP>140")





roc.dm.cohort <-bind_rows(
  x0.dm.roc.a1c ,
x0.dm.roc.min,
x0.dm.roc.full,

x1.dm.roc.a1c,
x1.dm.roc.min,
x1.dm.roc.full,

x2.dm.roc.a1c,
x2.dm.roc.min,
x2.dm.roc.full,

#x3.dm.roc.a1c,
#x3.dm.roc.min,

x4.dm.roc.a1c,
x4.dm.roc.min,
x4.dm.roc.full,

x5.dm.roc.a1c,
x5.dm.roc.min,
x5.dm.roc.full,

x6.dm.roc.a1c,
x6.dm.roc.min,
x6.dm.roc.full
) 


library(ggrepel)
plot.pdm.cohort.roc <- roc.pdm.cohort %>% bind_rows(roc.pdm.cohort  %>% group_by(Cohort,Stat) %>% mutate(Best = tpr - fpr) %>% filter(Best==max(Best)) ) %>% filter(Stat=="A1c" | Stat=="Min") %>% 
  ggplot() + geom_line(aes(x=fpr,y=tpr,color=Cohort,linetype=Stat))  +
 geom_point(data=. %>% filter(!is.na(Best)),aes(label=paste0(round(fpr,2),', ',round(tpr,2)),x=fpr,y=tpr,color=Cohort,shape=Stat),size=2) +   
  geom_text_repel(data=. %>% filter(!is.na(Best)),aes(label=paste0("(",round(fpr,2),', ',round(tpr,2),")"),x=fpr,y=tpr),size=2) + 
  geom_abline(aes(slope=1,intercept=0),linetype="dotted")+ facet_wrap(~Cohort)  + labs(title="Pre-Diabetes Diagnosis") + xlab("1-Specificity") + ylab("Sensitivity") + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

plot.dm.cohort.roc <- roc.dm.cohort %>% bind_rows(roc.dm.cohort %>% group_by(Cohort,Stat) %>% 
                                                    mutate(Best = tpr - fpr) %>% filter(Best==max(Best)) ) %>%   filter(Stat=="A1c" | Stat=="Min") %>% 
 ggplot(aes(x=fpr,y=tpr,color=Cohort,linetype=Stat,shape=Stat)) + geom_line() +
 geom_point(data=. %>% filter(!is.na(Best)),
            aes(label=paste0(round(fpr,2),', ',round(tpr,2))),size=2) +   
  geom_text_repel(data=. %>% filter(!is.na(Best)),
                  aes(label=paste0("(",round(fpr,2),', ',round(tpr,2),")"),x=fpr,y=tpr),size=2,color='black') + 
  geom_abline(aes(slope=1,intercept=0),linetype="dotted") + facet_wrap(~Cohort) + labs(title="Diabetes Diagnosis") + xlab("1-Specificity") + ylab("Sensitivity") + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))


grid.plot.cohort.roc<-grid.arrange(plot.pdm.cohort.roc,plot.dm.cohort.roc,ncol=2)
ggsave(file='~/Dropbox/NHANES manuscript/Grid-PreDM-DM-Cohorts-MinvA1c.jpg',plot=grid.plot.cohort.roc)



plot.roc.abstract <- roc.dm.cohort %>% bind_rows(roc.dm.cohort %>% group_by(Cohort,Stat) %>% mutate(Best = tpr - fpr) %>% filter(Best==max(Best)) ) %>% 
bind_rows(roc.pdm.cohort %>% bind_rows(roc.pdm.cohort %>% group_by(Cohort,Stat) %>% mutate(Best = tpr - fpr) %>% filter(Best==max(Best)) ) ) %>% 
 filter(Cohort=="All") %>% 
  mutate(Diagnosis=if_else(Dx=="DM","Diabetes","Pre-Diabetes")) %>% mutate(Stat=if_else(Stat=="Min","Model",Stat)) %>% 
 ggplot(aes(x=fpr,y=tpr,linetype=Stat,shape=Stat,color=Diagnosis)) + geom_line() +
 geom_point(data=. %>% filter(!is.na(Best)),
            aes(label=paste0(round(fpr,2),', ',round(tpr,2))),size=3) +   
  geom_text_repel(data=. %>% filter(!is.na(Best)),
                  aes(label=paste0("(",round(fpr,2),', ',round(tpr,2),")"),x=fpr,y=tpr)) + 
  geom_abline(aes(slope=1,intercept=0),linetype="dotted") + labs(title="Receiver Operator Curves",linetype="Method",shape="Method") + xlab("1-Specificity") + ylab("Sensitivity") + 
  scale_color_manual(values=c("Diabetes"="maroon","Pre-Diabetes"="green")) ; print(plot.roc.abstract)
ggsave('~/Dropbox/NHANES manuscript/ROC-PreDM-DM-MinvA1cvFull.jpg',plot=plot.roc.abstract)

plot.roc.abstract <- roc.dm.cohort %>% bind_rows(roc.dm.cohort %>% group_by(Cohort,Stat) %>% mutate(Best = tpr - fpr) %>% filter(Best==max(Best)) ) %>% 
bind_rows(roc.pdm.cohort %>% bind_rows(roc.pdm.cohort %>% group_by(Cohort,Stat) %>% mutate(Best = tpr - fpr) %>% filter(Best==max(Best)) ) ) %>% 
 filter(Cohort=="All") %>% 
  mutate(Diagnosis=if_else(Dx=="DM","Diabetes","Pre-Diabetes")) %>% filter(Stat=="Min" |Stat=="A1c") %>% mutate(Stat=if_else(Stat=="Min","Model",Stat)) %>% 
 ggplot(aes(x=fpr,y=tpr,linetype=Stat,shape=Stat,color=Diagnosis)) + geom_line() +
 #geom_point(data=. %>% filter(!is.na(Best)),
 #            aes(label=paste0(round(fpr,2),', ',round(tpr,2))),size=2) +   
  geom_text_repel(data=. %>% filter(!is.na(Best)),
                  aes(label=paste0("(",round(fpr,2),', ',round(tpr,2),")"),x=fpr,y=tpr),size=3) + 
  geom_abline(aes(slope=1,intercept=0),linetype="dotted") + labs(title="Receiver Operator Curves",linetype="Method",shape="Method") + xlab("1-Specificity") + ylab("Sensitivity") + 
  scale_color_manual(values=c("Diabetes"="maroon","Pre-Diabetes"="green")); print(plot.roc.abstract)

ggsave('~/Dropbox/NHANES manuscript/ROC-PreDM-DM-MinvA1c.jpg',plot=plot.roc.abstract)


#roc.dm.cohort %>% group_by(Cohort,Stat) %>% mutate(Best = tpr - fpr) %>% filter(Best==max(Best)) ) %>% mutate(PPV = tpr/)
```


```{r MANUSCRIPT - Making ROC Figures with All and Subpopulations}

### PDM
yy <- office_test
x0.yy.pdm <- yy.pdm <-  factor(yy$two >=140 & yy$two<200)
x0.pdm.roc.fpg <- tidy(AUC::roc(yy$fpg,yy.pdm)) %>% mutate(Stat="FPG",Dx="pdm",Cohort="All")
x0.pdm.roc.fpg.a1c <- tidy(AUC::roc(yy$Pred.FPG,yy.pdm)) %>% mutate(Stat="FPG-A1c",Dx="pdm",Cohort="All")
x0.pdm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.pdm)) %>% mutate(Stat="A1c",Dx="pdm",Cohort="All")
x0.pdm.roc.nonfasting <- tidy(AUC::roc(yy$Pred.NonFasting,yy.pdm)) %>% mutate(Stat="NonFasting",Dx="pdm",Cohort="All")
x0.pdm.roc.min <- tidy(AUC::roc(yy$Pred.Min,yy.pdm))  %>% mutate(Stat="Min",Dx="pdm",Cohort="All")
x0.pdm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.pdm))  %>% mutate(Stat="Full",Dx="pdm",Cohort="All")
x0.pdm.roc.FIB4 <- tidy(AUC::roc(yy$Pred.FIB4,yy.pdm))  %>% mutate(Stat="FIB4",Dx="pdm",Cohort="All")

roc.pdm.cohort <-bind_rows(
  x0.pdm.roc.a1c ,
  x0.pdm.roc.fpg ,  
x0.pdm.roc.min,
x0.pdm.roc.full,
x0.pdm.roc.fpg.a1c,
x0.pdm.roc.FIB4,
x0.pdm.roc.nonfasting
) 


### IGT
yy <- office_test
x0.yy.igt <- yy.igt <-  factor(yy$two >= 140)
x0.igt.roc.fpg <- tidy(AUC::roc(yy$fpg,yy.igt)) %>% mutate(Stat="FPG",Dx="IGT",Cohort="All")
x0.igt.roc.fpg.a1c <- tidy(AUC::roc(yy$Pred.FPG,yy.igt)) %>% mutate(Stat="FPG-A1c",Dx="IGT",Cohort="All")
x0.igt.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.igt)) %>% mutate(Stat="A1c",Dx="IGT",Cohort="All")
x0.igt.roc.nonfasting <- tidy(AUC::roc(yy$Pred.NonFasting,yy.igt)) %>% mutate(Stat="NonFasting",Dx="IGT",Cohort="All")
x0.igt.roc.min <- tidy(AUC::roc(yy$Pred.Min,yy.igt))  %>% mutate(Stat="Min",Dx="IGT",Cohort="All")
x0.igt.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.igt))  %>% mutate(Stat="Full",Dx="IGT",Cohort="All")
x0.igt.roc.FIB4 <- tidy(AUC::roc(yy$Pred.FIB4,yy.igt))  %>% mutate(Stat="FIB4",Dx="IGT",Cohort="All")


roc.igt.cohort <-bind_rows(
x0.igt.roc.a1c ,
x0.igt.roc.fpg ,
x0.igt.roc.min,
x0.igt.roc.full,
x0.igt.roc.nonfasting,
x0.igt.roc.FIB4,
x0.igt.roc.fpg.a1c
) 

### DM
yy <- office_test
x0.yy.dm <- yy.dm <-  factor(yy$two >= 200)
x0.dm.roc.fpg <- tidy(AUC::roc(yy$fpg,yy.dm)) %>% mutate(Stat="FPG",Dx="DM",Cohort="All")
x0.dm.roc.fpg.a1c <- tidy(AUC::roc(yy$Pred.FPG,yy.dm)) %>% mutate(Stat="FPG-A1c",Dx="DM",Cohort="All")
x0.dm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.dm)) %>% mutate(Stat="A1c",Dx="DM",Cohort="All")
x0.dm.roc.nonfasting <- tidy(AUC::roc(yy$Pred.NonFasting,yy.dm)) %>% mutate(Stat="NonFasting",Dx="DM",Cohort="All")
x0.dm.roc.min <- tidy(AUC::roc(yy$Pred.Min,yy.dm))  %>% mutate(Stat="Min",Dx="DM",Cohort="All")
x0.dm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.dm))  %>% mutate(Stat="Full",Dx="DM",Cohort="All")
x0.dm.roc.FIB4 <- tidy(AUC::roc(yy$Pred.FIB4,yy.dm))  %>% mutate(Stat="FIB4",Dx="DM",Cohort="All")


roc.dm.cohort <-bind_rows(
x0.dm.roc.a1c ,
x0.dm.roc.fpg ,
x0.dm.roc.min,
x0.dm.roc.full,
x0.dm.roc.nonfasting,
x0.dm.roc.FIB4,
x0.dm.roc.fpg.a1c

) 


library(ggrepel)
plot.pdm.cohort.roc <- roc.pdm.cohort %>% bind_rows(roc.pdm.cohort  %>% group_by(Cohort,Stat) %>% mutate(Best = tpr - fpr) %>% filter(Best==max(Best)) ) %>% filter(Stat=="A1c" | Stat=="Min"| Stat=="FPG") %>% 
  ggplot() + geom_line(aes(x=fpr,y=tpr,color=Cohort,linetype=Stat))  +
 #geom_point(data=. %>% filter(!is.na(Best)),aes(label=paste0(round(fpr,2),', ',round(tpr,2)),x=fpr,y=tpr,color=Cohort,shape=Stat),size=2) +   
  #geom_text_repel(data=. %>% filter(!is.na(Best)),aes(label=paste0("(",round(fpr,2),', ',round(tpr,2),")"),x=fpr,y=tpr),size=2) + 
  geom_abline(aes(slope=1,intercept=0),linetype="dotted")+ facet_wrap(~Cohort)  + labs(title="Pre-Diabetes Diagnosis") + xlab("1-Specificity") + ylab("Sensitivity") + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

plot.dm.cohort.roc <- roc.dm.cohort %>% bind_rows(roc.dm.cohort %>% group_by(Cohort,Stat) %>% 
                                                    mutate(Best = tpr - fpr) %>% filter(Best==max(Best)) ) %>%   filter(Stat=="A1c" | Stat=="Min" | Stat=="FPG") %>% 
 ggplot(aes(x=fpr,y=tpr,color=Cohort,linetype=Stat,shape=Stat)) + geom_line() +
 #geom_point(data=. %>% filter(!is.na(Best)),aes(label=paste0(round(fpr,2),', ',round(tpr,2))),size=2) +   
  #geom_text_repel(data=. %>% filter(!is.na(Best)),aes(label=paste0("(",round(fpr,2),', ',round(tpr,2),")"),x=fpr,y=tpr),size=2,color='black') + 
  geom_abline(aes(slope=1,intercept=0),linetype="dotted") + facet_wrap(~Cohort) + labs(title="Diabetes Diagnosis") + xlab("1-Specificity") + ylab("Sensitivity") + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))


grid.plot.cohort.roc<-grid.arrange(plot.pdm.cohort.roc,plot.dm.cohort.roc,ncol=2);print(grid.plot.cohort.roc)
#ggsave(file='~/Dropbox/NHANES manuscript/Grid-PreDM-DM-Cohorts-MinvA1cvFPG.jpg',plot=grid.plot.cohort.roc)


plot.roc.abstract <- roc.dm.cohort %>% bind_rows(roc.dm.cohort %>% group_by(Cohort,Stat) %>% mutate(Best = tpr - fpr) %>% filter(Best==max(Best)) ) %>% 
bind_rows(roc.pdm.cohort %>% bind_rows(roc.pdm.cohort %>% group_by(Cohort,Stat) %>% mutate(Best = tpr - fpr) %>% filter(Best==max(Best)) ) ) %>% 
 filter(Cohort=="All") %>% 
  mutate(Diagnosis=if_else(Dx=="DM","Diabetes","Pre-Diabetes")) %>% mutate(Stat=if_else(Stat=="Min","Model",Stat)) %>% 
 ggplot(aes(x=fpr,y=tpr,linetype=Stat,shape=Stat,color=Diagnosis)) + geom_line() +
 geom_point(data=. %>% filter(!is.na(Best)),
            aes(label=paste0(round(fpr,2),', ',round(tpr,2))),size=3) +   
  geom_text_repel(data=. %>% filter(!is.na(Best)),
                  aes(label=paste0("(",round(fpr,2),', ',round(tpr,2),")"),x=fpr,y=tpr)) + 
  geom_abline(aes(slope=1,intercept=0),linetype="dotted") + labs(title="Receiver Operator Curves",linetype="Method",shape="Method") + xlab("1-Specificity") + ylab("Sensitivity") + 
  scale_color_manual(values=c("Diabetes"="maroon","Pre-Diabetes"="green")) ; print(plot.roc.abstract)
#ggsave('~/Dropbox/NHANES manuscript/ROC-PreDM-DM-MinvA1cvFullvsFPG.jpg',plot=plot.roc.abstract)

plot.roc.abstract <- roc.dm.cohort %>% bind_rows(roc.dm.cohort %>% group_by(Cohort,Stat) %>% mutate(Best = tpr - fpr) %>% filter(Best==max(Best)) ) %>% 
bind_rows(roc.pdm.cohort %>% bind_rows(roc.pdm.cohort %>% group_by(Cohort,Stat) %>% mutate(Best = tpr - fpr) %>% filter(Best==max(Best)) ) ) %>% 
 filter(Cohort=="All") %>% 
  mutate(Diagnosis=if_else(Dx=="DM","Diabetes","Pre-Diabetes")) %>% mutate(Stat=if_else(Stat=="Min","Model",Stat)) %>% 
 ggplot(aes(x=fpr,y=tpr,linetype=Stat,shape=Stat,color=Stat)) + geom_line() +
 #geom_point(data=. %>% filter(!is.na(Best)),
  #          aes(label=paste0(round(fpr,2),', ',round(tpr,2))),size=3) +   
  #geom_text_repel(data=. %>% filter(!is.na(Best)),
  #                aes(label=paste0("(",round(fpr,2),', ',round(tpr,2),")"),x=fpr,y=tpr)) + 
  geom_abline(aes(slope=1,intercept=0),linetype="dotted") + labs(title="Receiver Operator Curves",linetype="Method",shape="Method") + xlab("1-Specificity") + ylab("Sensitivity") + 
  scale_color_manual(values=c("Diabetes"="maroon","Pre-Diabetes"="green")) + facet_wrap(~Diagnosis); print(plot.roc.abstract)
#ggsave('~/Dropbox/NHANES manuscript/ROC-PreDM-DM-MinvA1cvFullvsFPG.jpg',plot=plot.roc.abstract)

plot.roc.abstract <- roc.dm.cohort %>% 
bind_rows(roc.pdm.cohort %>% bind_rows(roc.igt.cohort)) %>% 
 filter(Cohort=="All") %>% 
  mutate(Diagnosis=if_else(Dx=="DM","Diabetes",ifelse(Dx=="pdm","Pre-Diabetes","IGT"))) %>% filter(Stat=="Min" |Stat=="A1c" | Stat=="FPG") %>% mutate(Stat=if_else(Stat=="Min","Model",Stat)) %>% 
 ggplot(aes(x=fpr,y=tpr,linetype=Stat,shape=Stat,color=Diagnosis)) + geom_line() +
  geom_abline(aes(slope=1,intercept=0),linetype="dotted") + labs(title="Receiver Operator Curves",linetype="Method",shape="Method") + xlab("1-Specificity") + ylab("Sensitivity"); print(plot.roc.abstract)

#ggsave('~/Dropbox/NHANES manuscript/ROC-PreDM-DM-MinvA1c.jpg',plot=plot.roc.abstract)


#roc.dm.cohort %>% group_by(Cohort,Stat) %>% mutate(Best = tpr - fpr) %>% filter(Best==max(Best)) ) %>% mutate(PPV = tpr/)
```



```{r}
plot.roc.dm<- roc.dm.cohort %>% bind_rows(roc.dm.cohort %>% group_by(Cohort,Stat) %>% mutate(Best = tpr - fpr) %>% filter(Best==max(Best)) ) %>% 
bind_rows(roc.pdm.cohort %>% bind_rows(roc.pdm.cohort %>% group_by(Cohort,Stat) %>% mutate(Best = tpr - fpr) %>% filter(Best==max(Best)) ) ) %>% 
 filter(Cohort=="All") %>% 
  mutate(Diagnosis=if_else(Dx=="DM","Diabetes","Pre-Diabetes")) %>% #mutate(Stat=if_else(Stat=="Min","Model",Stat)) %>% 
  filter(Diagnosis=="Diabetes") %>% 
 ggplot() + geom_line(aes(x=fpr,y=tpr,color=Stat),size=1,alpha=0.7) +
  geom_line(data=data.frame(x=c(0,1),y=c(0,1)),aes(x=x,y=y),linetype="dotted") + 
  labs(title="Receiver Operator Curves",linetype="Method",color="Model") + xlab("1-Specificity") + ylab("Sensitivity") + ggtitle("Diabetes") + 
  scale_color_manual(values=c("A1c"="darkgreen","FPG"="green","FPG-A1c"="cyan","NonFasting"="magenta","FIB4"="purple","Full"="orange","Min"="red"));print(plot.roc.dm)


plot.roc.pdm<- roc.dm.cohort %>% bind_rows(roc.dm.cohort %>% group_by(Cohort,Stat) %>% mutate(Best = tpr - fpr) %>% filter(Best==max(Best)) ) %>% 
bind_rows(roc.pdm.cohort %>% bind_rows(roc.pdm.cohort %>% group_by(Cohort,Stat) %>% mutate(Best = tpr - fpr) %>% filter(Best==max(Best)) ) ) %>% 
 filter(Cohort=="All") %>% 
  mutate(Diagnosis=if_else(Dx=="DM","Diabetes","Pre-Diabetes")) %>% #mutate(Stat=if_else(Stat=="Min","Model",Stat)) %>% 
  filter(Diagnosis=="Pre-Diabetes") %>% 
 ggplot() + geom_line(aes(x=fpr,y=tpr,color=Stat),size=1,alpha=0.7) +
  geom_line(data=data.frame(x=c(0,1),y=c(0,1)),aes(x=x,y=y),linetype="dotted") + 
  labs(title="Receiver Operator Curves",linetype="Method",color="Model") + xlab("1-Specificity") + ylab("Sensitivity") + ggtitle("Pre-Diabetes") + 
  scale_color_manual(values=c("A1c"="darkgreen","FPG"="green","FPG-A1c"="cyan","NonFasting"="magenta","FIB4"="purple","Full"="orange","Min"="red"));print(plot.roc.pdm)

```



```{r MANUSCRIPT - Making ROC Figures with All and Subpopulations}

  
yy <- office_test.All
x0.yy.pdm <- yy.pdm <-  factor(yy$two >=140 & yy$two<200)
x0.pdm.roc.fpg <- tidy(AUC::roc(yy$fpg,yy.pdm)) %>% mutate(Stat="FPG",Dx="pdm",Cohort="All")
x0.pdm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.pdm)) %>% mutate(Stat="A1c",Dx="pdm",Cohort="All")
x0.pdm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.pdm))  %>% mutate(Stat="Min",Dx="pdm",Cohort="All")
x0.pdm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.pdm))  %>% mutate(Stat="Full",Dx="pdm",Cohort="All")


yy <- office_test.Age
x1.yy.pdm<-yy.pdm <-  factor(yy$two >=140 & yy$two<200)
x1.pdm.roc.fpg <- tidy(AUC::roc(yy$fpg,yy.pdm)) %>% mutate(Stat="FPG",Dx="pdm",Cohort="Age>60")
x1.pdm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.pdm)) %>% mutate(Stat="A1c",Dx="pdm",Cohort="Age>60")
x1.pdm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.pdm))  %>% mutate(Stat="Min",Dx="pdm",Cohort="Age>60")
x1.pdm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.pdm))  %>% mutate(Stat="Full",Dx="pdm",Cohort="Age>60")


yy <- office_test.BMI
x2.yy.pdm <- yy.pdm <-  factor(yy$two >=140 & yy$two<200)
x2.pdm.roc.fpg <- tidy(AUC::roc(yy$fpg,yy.pdm)) %>% mutate(Stat="FPG",Dx="pdm",Cohort="BMI>30")
x2.pdm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.pdm)) %>% mutate(Stat="A1c",Dx="pdm",Cohort="BMI>30")
x2.pdm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.pdm))  %>% mutate(Stat="Min",Dx="pdm",Cohort="BMI>30")
x2.pdm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.pdm))  %>% mutate(Stat="Full",Dx="pdm",Cohort="BMI>30")

yy <- office_test.WC  
x3.yy.pdm <-yy.pdm <-  factor(yy$two >=140 & yy$two<200)
x3.pdm.roc.fpg <- tidy(AUC::roc(yy$fpg,yy.pdm)) %>% mutate(Stat="FPG",Dx="pdm",Cohort="WC>110")
x3.pdm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.pdm)) %>% mutate(Stat="A1c",Dx="pdm",Cohort="WC>110")
x3.pdm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.pdm)) %>% mutate(Stat="Min",Dx="pdm",Cohort="WC>110")
x3.pdm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.pdm))  %>% mutate(Stat="Full",Dx="pdm",Cohort="WC>110")

yy <- office_test.FIB4
x4.yy.pdm <-yy.pdm <-  factor(yy$two >=140 & yy$two<200)
x4.pdm.roc.fpg <- tidy(AUC::roc(yy$fpg,yy.pdm)) %>% mutate(Stat="FPG",Dx="pdm",Cohort="FIB4>2.67")
x4.pdm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.pdm)) %>% mutate(Stat="A1c",Dx="pdm",Cohort="FIB4>2.67")
x4.pdm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.pdm)) %>% mutate(Stat="Min",Dx="pdm",Cohort="FIB4>2.67")
x4.pdm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.pdm))  %>% mutate(Stat="Full",Dx="pdm",Cohort="FIB4>2.67")


yy <- office_test.eGFR
x5.yy.pdm <-yy.pdm <-  factor(yy$two >=140 & yy$two<200)
x5.pdm.roc.fpg <- tidy(AUC::roc(yy$fpg,yy.pdm)) %>% mutate(Stat="FPG",Dx="pdm",Cohort="eGFR<60")
x5.pdm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.pdm)) %>% mutate(Stat="A1c",Dx="pdm",Cohort="eGFR<60")
x5.pdm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.pdm)) %>% mutate(Stat="Min",Dx="pdm",Cohort="eGFR<60")
x5.pdm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.pdm))  %>% mutate(Stat="Full",Dx="pdm",Cohort="eGFR<60")

yy <- office_test.SBP
x6.yy.pdm <- yy.pdm <-  factor(yy$two >=140 & yy$two<200)# %>% as.data.frame() %>% mutate(Stat="A1c",Dx="pdm",Cohort="SBP>140")
x6.pdm.roc.fpg <- tidy(AUC::roc(yy$fpg,yy.pdm)) %>% mutate(Stat="FPG",Dx="pdm",Cohort="SBP>140")
x6.pdm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.pdm)) %>% mutate(Stat="A1c",Dx="pdm",Cohort="SBP>140")
x6.pdm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.pdm)) %>% mutate(Stat="Min",Dx="pdm",Cohort="SBP>140")
x6.pdm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.pdm))  %>% mutate(Stat="Full",Dx="pdm",Cohort="SBP>140")




roc.pdm.cohort <-bind_rows(
  x0.pdm.roc.a1c ,
  x0.pdm.roc.fpg ,  
x0.pdm.roc.min,
x0.pdm.roc.full,

x1.pdm.roc.a1c,
x1.pdm.roc.fpg,
x1.pdm.roc.min,
x1.pdm.roc.full,

x2.pdm.roc.a1c,
x2.pdm.roc.fpg,
x2.pdm.roc.min,
x2.pdm.roc.full,

# x3.pdm.roc.a1c,
# x3.pdm.roc.min,

x4.pdm.roc.a1c,
x4.pdm.roc.fpg,
x4.pdm.roc.min,
x4.pdm.roc.full,

x5.pdm.roc.a1c,
x5.pdm.roc.fpg,
x5.pdm.roc.min,
x5.pdm.roc.full,

x6.pdm.roc.a1c,
x6.pdm.roc.fpg,
x6.pdm.roc.min,
x6.pdm.roc.full,

) 


## DM
yy <- office_test.All
yy.dm <-  factor(yy$two >= 200)
x0.dm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.dm)) %>% mutate(Stat="A1c",Dx="DM",Cohort="All")
x0.dm.roc.fpg <- tidy(AUC::roc(yy$fpg,yy.dm)) %>% mutate(Stat="FPG",Dx="DM",Cohort="All")
x0.dm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.dm))  %>% mutate(Stat="Min",Dx="DM",Cohort="All")
x0.dm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.dm))  %>% mutate(Stat="Full",Dx="DM",Cohort="All")

yy <- office_test.Age
yy.dm <-  factor(yy$two >= 200)
x1.dm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.dm)) %>% mutate(Stat="A1c",Dx="DM",Cohort="Age>60")
x1.dm.roc.fpg <- tidy(AUC::roc(yy$fpg,yy.dm)) %>% mutate(Stat="FPG",Dx="DM",Cohort="Age>60")
x1.dm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.dm))  %>% mutate(Stat="Min",Dx="DM",Cohort="Age>60")
x1.dm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.dm))  %>% mutate(Stat="Full",Dx="DM",Cohort="Age>60")

yy <- office_test.BMI
yy.dm <-  factor(yy$two >= 200)
x2.dm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.dm)) %>% mutate(Stat="A1c",Dx="DM",Cohort="BMI>30")
x2.dm.roc.fpg <- tidy(AUC::roc(yy$fpg,yy.dm)) %>% mutate(Stat="FPG",Dx="DM",Cohort="BMI>30")
x2.dm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.dm))  %>% mutate(Stat="Min",Dx="DM",Cohort="BMI>30")
x2.dm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.dm))  %>% mutate(Stat="Full",Dx="DM",Cohort="BMI>30")

yy <- office_test.WC  
yy.dm <-  factor(yy$two >= 200)
x3.dm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.dm)) %>% mutate(Stat="A1c",Dx="DM",Cohort="WC>110")
x3.dm.roc.fpg <- tidy(AUC::roc(yy$fpg,yy.dm)) %>% mutate(Stat="FPG",Dx="DM",Cohort="WC>110")
x3.dm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.dm)) %>% mutate(Stat="Min",Dx="DM",Cohort="WC>110")
x3.dm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.dm))  %>% mutate(Stat="Full",Dx="DM",Cohort="WC>110")

yy <- office_test.FIB4
yy.dm <-  factor(yy$two >= 200)
x4.dm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.dm)) %>% mutate(Stat="A1c",Dx="DM",Cohort="FIB4>2.67")
x4.dm.roc.fpg <- tidy(AUC::roc(yy$fpg,yy.dm)) %>% mutate(Stat="FPG",Dx="DM",Cohort="FIB4>2.67")
x4.dm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.dm)) %>% mutate(Stat="Min",Dx="DM",Cohort="FIB4>2.67")
x4.dm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.dm))  %>% mutate(Stat="Full",Dx="DM",Cohort="FIB4>2.67")

yy <- office_test.GGT
yy.dm <-  factor(yy$two >= 200)
x5.dm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.dm)) %>% mutate(Stat="A1c",Dx="DM",Cohort="eGFR<60")
x5.dm.roc.fpg <- tidy(AUC::roc(yy$fpg,yy.dm)) %>% mutate(Stat="FPG",Dx="DM",Cohort="eGFR<60")
x5.dm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.dm)) %>% mutate(Stat="Min",Dx="DM",Cohort="eGFR<60")
x5.dm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.dm))  %>% mutate(Stat="Full",Dx="DM",Cohort="eGFR<60")

yy <- office_test.SBP
yy.dm <-  factor(yy$two >= 200)
x6.dm.roc.a1c <- tidy(AUC::roc(yy$a1c,yy.dm)) %>% mutate(Stat="A1c",Dx="DM",Cohort="SBP>140")
x6.dm.roc.fpg <- tidy(AUC::roc(yy$fpg,yy.dm)) %>% mutate(Stat="FPG",Dx="DM",Cohort="SBP>140")
x6.dm.roc.min <- tidy(AUC::roc(yy$Pred.MIN,yy.dm)) %>% mutate(Stat="Min",Dx="DM",Cohort="SBP>140")
x6.dm.roc.full <- tidy(AUC::roc(yy$Pred.Full,yy.dm))  %>% mutate(Stat="Full",Dx="DM",Cohort="SBP>140")





roc.dm.cohort <-bind_rows(
x0.dm.roc.a1c ,
x0.dm.roc.fpg ,
x0.dm.roc.min,
x0.dm.roc.full,

x1.dm.roc.a1c,
x1.dm.roc.fpg ,
x1.dm.roc.min,
x1.dm.roc.full,

x2.dm.roc.a1c,
x2.dm.roc.fpg ,
x2.dm.roc.min,
x2.dm.roc.full,

#x3.dm.roc.a1c,
#x3.dm.roc.min,

x4.dm.roc.a1c,
x4.dm.roc.fpg ,
x4.dm.roc.min,
x4.dm.roc.full,

x5.dm.roc.a1c,
x5.dm.roc.fpg ,
x5.dm.roc.min,
x5.dm.roc.full,

x6.dm.roc.a1c,
x6.dm.roc.fpg ,
x6.dm.roc.min,
x6.dm.roc.full
) 


library(ggrepel)
plot.pdm.cohort.roc <- roc.pdm.cohort %>% bind_rows(roc.pdm.cohort  %>% group_by(Cohort,Stat) %>% mutate(Best = tpr - fpr) %>% filter(Best==max(Best)) ) %>% filter(Stat=="A1c" | Stat=="Min"| Stat=="FPG") %>% 
  ggplot() + geom_line(aes(x=fpr,y=tpr,color=Cohort,linetype=Stat))  +
 #geom_point(data=. %>% filter(!is.na(Best)),aes(label=paste0(round(fpr,2),', ',round(tpr,2)),x=fpr,y=tpr,color=Cohort,shape=Stat),size=2) +   
  #geom_text_repel(data=. %>% filter(!is.na(Best)),aes(label=paste0("(",round(fpr,2),', ',round(tpr,2),")"),x=fpr,y=tpr),size=2) + 
  geom_abline(aes(slope=1,intercept=0),linetype="dotted")+ facet_wrap(~Cohort)  + labs(title="Pre-Diabetes Diagnosis") + xlab("1-Specificity") + ylab("Sensitivity") + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

plot.dm.cohort.roc <- roc.dm.cohort %>% bind_rows(roc.dm.cohort %>% group_by(Cohort,Stat) %>% 
                                                    mutate(Best = tpr - fpr) %>% filter(Best==max(Best)) ) %>%   filter(Stat=="A1c" | Stat=="Min" | Stat=="FPG") %>% 
 ggplot(aes(x=fpr,y=tpr,color=Cohort,linetype=Stat,shape=Stat)) + geom_line() +
 #geom_point(data=. %>% filter(!is.na(Best)),aes(label=paste0(round(fpr,2),', ',round(tpr,2))),size=2) +   
  #geom_text_repel(data=. %>% filter(!is.na(Best)),aes(label=paste0("(",round(fpr,2),', ',round(tpr,2),")"),x=fpr,y=tpr),size=2,color='black') + 
  geom_abline(aes(slope=1,intercept=0),linetype="dotted") + facet_wrap(~Cohort) + labs(title="Diabetes Diagnosis") + xlab("1-Specificity") + ylab("Sensitivity") + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))


grid.plot.cohort.roc<-grid.arrange(plot.pdm.cohort.roc,plot.dm.cohort.roc,ncol=2);print(grid.plot.cohort.roc)
ggsave(file='~/Dropbox/NHANES manuscript/Grid-PreDM-DM-Cohorts-MinvA1cvFPG.jpg',plot=grid.plot.cohort.roc)


plot.roc.abstract <- roc.dm.cohort %>% bind_rows(roc.dm.cohort %>% group_by(Cohort,Stat) %>% mutate(Best = tpr - fpr) %>% filter(Best==max(Best)) ) %>% 
bind_rows(roc.pdm.cohort %>% bind_rows(roc.pdm.cohort %>% group_by(Cohort,Stat) %>% mutate(Best = tpr - fpr) %>% filter(Best==max(Best)) ) ) %>% 
 filter(Cohort=="All") %>% 
  mutate(Diagnosis=if_else(Dx=="DM","Diabetes","Pre-Diabetes")) %>% mutate(Stat=if_else(Stat=="Min","Model",Stat)) %>% 
 ggplot(aes(x=fpr,y=tpr,linetype=Stat,shape=Stat,color=Diagnosis)) + geom_line() +
 geom_point(data=. %>% filter(!is.na(Best)),
            aes(label=paste0(round(fpr,2),', ',round(tpr,2))),size=3) +   
  geom_text_repel(data=. %>% filter(!is.na(Best)),
                  aes(label=paste0("(",round(fpr,2),', ',round(tpr,2),")"),x=fpr,y=tpr)) + 
  geom_abline(aes(slope=1,intercept=0),linetype="dotted") + labs(title="Receiver Operator Curves",linetype="Method",shape="Method") + xlab("1-Specificity") + ylab("Sensitivity") + 
  scale_color_manual(values=c("Diabetes"="maroon","Pre-Diabetes"="green")) ; print(plot.roc.abstract)
ggsave('~/Dropbox/NHANES manuscript/ROC-PreDM-DM-MinvA1cvFullvsFPG.jpg',plot=plot.roc.abstract)

plot.roc.abstract <- roc.dm.cohort %>% bind_rows(roc.dm.cohort %>% group_by(Cohort,Stat) %>% mutate(Best = tpr - fpr) %>% filter(Best==max(Best)) ) %>% 
bind_rows(roc.pdm.cohort %>% bind_rows(roc.pdm.cohort %>% group_by(Cohort,Stat) %>% mutate(Best = tpr - fpr) %>% filter(Best==max(Best)) ) ) %>% 
 filter(Cohort=="All") %>% 
  mutate(Diagnosis=if_else(Dx=="DM","Diabetes","Pre-Diabetes")) %>% filter(Stat=="Min" |Stat=="A1c" | Stat=="FPG") %>% mutate(Stat=if_else(Stat=="Min","Model",Stat)) %>% 
 ggplot(aes(x=fpr,y=tpr,linetype=Stat,shape=Stat,color=Diagnosis)) + geom_line() +
 geom_point(data=. %>% filter(!is.na(Best)),
            aes(label=paste0(round(fpr,2),', ',round(tpr,2))),size=2) +   
  geom_text_repel(data=. %>% filter(!is.na(Best)),
                  aes(label=paste0("(",round(fpr,2),', ',round(tpr,2),")"),x=fpr,y=tpr),size=3) + 
  geom_abline(aes(slope=1,intercept=0),linetype="dotted") + labs(title="Receiver Operator Curves",linetype="Method",shape="Method") + xlab("1-Specificity") + ylab("Sensitivity") + 
  scale_color_manual(values=c("Diabetes"="maroon","Pre-Diabetes"="green")); print(plot.roc.abstract)

ggsave('~/Dropbox/NHANES manuscript/ROC-PreDM-DM-MinvA1c.jpg',plot=plot.roc.abstract)


#roc.dm.cohort %>% group_by(Cohort,Stat) %>% mutate(Best = tpr - fpr) %>% filter(Best==max(Best)) ) %>% mutate(PPV = tpr/)
```



```{r Getting the AUROCs}

yy <- office_test.All
x0.yy.pdm <- yy.pdm <- factor(yy$two >=140 & yy$two<200)
x0.pdm.auroc.a1c <- auc(AUC::roc(yy$a1c, yy.pdm))
x0.pdm.auroc.min <- auc(AUC::roc(yy$Pred.MIN, yy.pdm))
x0.pdm.auroc.full <- auc(AUC::roc(yy$Pred.Full, yy.pdm))

yy <- office_test.Age
x1.yy.pdm <- yy.pdm <- factor(yy$two >=140 & yy$two<200)
x1.pdm.auroc.a1c <- auc(AUC::roc(yy$a1c, yy.pdm))
x1.pdm.auroc.min <- auc(AUC::roc(yy$Pred.MIN, yy.pdm))
x1.pdm.auroc.full <- auc(AUC::roc(yy$Pred.Full, yy.pdm))

yy <- office_test.BMI
x2.yy.pdm <- yy.pdm <- factor(yy$two >=140 & yy$two<200)
x2.pdm.auroc.a1c <- auc(AUC::roc(yy$a1c, yy.pdm))
x2.pdm.auroc.min <- auc(AUC::roc(yy$Pred.MIN, yy.pdm))
x2.pdm.auroc.full <- auc(AUC::roc(yy$Pred.Full, yy.pdm))

yy <- office_test.WC  
x3.yy.pdm <- yy.pdm <- factor(yy$two >=140 & yy$two<200)
x3.pdm.auroc.a1c <- auc(AUC::roc(yy$a1c, yy.pdm))
x3.pdm.auroc.min <- auc(AUC::roc(yy$Pred.MIN, yy.pdm))
x3.pdm.auroc.full <- auc(AUC::roc(yy$Pred.Full, yy.pdm))

yy <- office_test.FIB4
x4.yy.pdm <- yy.pdm <- factor(yy$two >=140 & yy$two<200)
x4.pdm.auroc.a1c <- auc(AUC::roc(yy$a1c, yy.pdm))
x4.pdm.auroc.min <- auc(AUC::roc(yy$Pred.MIN, yy.pdm))
x4.pdm.auroc.full <- auc(AUC::roc(yy$Pred.Full, yy.pdm))

yy <- office_test.eGFR
x5.yy.pdm <- yy.pdm <- factor(yy$two >=140 & yy$two<200)
x5.pdm.auroc.a1c <- auc(AUC::roc(yy$a1c, yy.pdm))
x5.pdm.auroc.min <- auc(AUC::roc(yy$Pred.MIN, yy.pdm))
x5.pdm.auroc.full <- auc(AUC::roc(yy$Pred.Full, yy.pdm))

yy <- office_test.SBP
x6.yy.pdm <- yy.pdm <- factor(yy$two >=140 & yy$two<200)
x6.pdm.auroc.a1c <- auc(AUC::roc(yy$a1c, yy.pdm))
x6.pdm.auroc.min <- auc(AUC::roc(yy$Pred.MIN, yy.pdm))
x6.pdm.auroc.full <- auc(AUC::roc(yy$Pred.Full, yy.pdm))

## DM
yy <- office_test.All
yy.dm <- factor(yy$two >= 200)
x0.dm.auroc.a1c <- auc(AUC::roc(yy$a1c, yy.dm))
x0.dm.auroc.min <- auc(AUC::roc(yy$Pred.MIN, yy.dm))
x0.dm.auroc.full <- auc(AUC::roc(yy$Pred.Full, yy.dm))

yy <- office_test.Age
yy.dm <- factor(yy$two >= 200)
x1.dm.auroc.a1c <- auc(AUC::roc(yy$a1c, yy.dm))
x1.dm.auroc.min <- auc(AUC::roc(yy$Pred.MIN, yy.dm))
x1.dm.auroc.full <- auc(AUC::roc(yy$Pred.Full, yy.dm))

yy <- office_test.BMI
yy.dm <- factor(yy$two >= 200)
x2.dm.auroc.a1c <- auc(AUC::roc(yy$a1c, yy.dm))
x2.dm.auroc.min <- auc(AUC::roc(yy$Pred.MIN, yy.dm))
x2.dm.auroc.full <- auc(AUC::roc(yy$Pred.Full, yy.dm))

yy <- office_test.WC  
yy.dm <- factor(yy$two >= 200)
x3.dm.auroc.a1c <- auc(AUC::roc(yy$a1c, yy.dm))
x3.dm.auroc.min <- auc(AUC::roc(yy$Pred.MIN, yy.dm))
x3.dm.auroc.full <- auc(AUC::roc(yy$Pred.Full, yy.dm))

yy <- office_test.FIB4
yy.dm <- factor(yy$two >= 200)
x4.dm.auroc.a1c <- auc(AUC::roc(yy$a1c, yy.dm))
x4.dm.auroc.min <- auc(AUC::roc(yy$Pred.MIN, yy.dm))
x4.dm.auroc.full <- auc(AUC::roc(yy$Pred.Full, yy.dm))

yy <- office_test.GGT
yy.dm <- factor(yy$two >= 200)
x5.dm.auroc.a1c <- auc(AUC::roc(yy$a1c, yy.dm))
x5.dm.auroc.min <- auc(AUC::roc(yy$Pred.MIN, yy.dm))
x5.dm.auroc.full <- auc(AUC::roc(yy$Pred.Full, yy.dm))

yy <- office_test.SBP
yy.dm <- factor(yy$two >= 200)
x6.dm.auroc.a1c <- auc(AUC::roc(yy$a1c, yy.dm))
x6.dm.auroc.min <- auc(AUC::roc(yy$Pred.MIN, yy.dm))
x6.dm.auroc.full <- auc(AUC::roc(yy$Pred.Full, yy.dm))

```


```{r}
# Create a data frame with PDM and DM side by side
combined_auroc_table <- data.frame(
  Cohort = c("All", "Age>60", "BMI>30", "WC>110", "FIB4>2.67", "eGFR<60", "SBP>140"),
  AUROC_A1c_PDM = round(c(x0.pdm.auroc.a1c, x1.pdm.auroc.a1c, x2.pdm.auroc.a1c, x3.pdm.auroc.a1c, 
                           x4.pdm.auroc.a1c, x5.pdm.auroc.a1c, x6.pdm.auroc.a1c), 3),
  AUROC_A1c_DM  = round(c(x0.dm.auroc.a1c, x1.dm.auroc.a1c, x2.dm.auroc.a1c, x3.dm.auroc.a1c, 
                           x4.dm.auroc.a1c, x5.dm.auroc.a1c, x6.dm.auroc.a1c), 3),
  AUROC_Min_PDM = round(c(x0.pdm.auroc.min, x1.pdm.auroc.min, x2.pdm.auroc.min, x3.pdm.auroc.min, 
                           x4.pdm.auroc.min, x5.pdm.auroc.min, x6.pdm.auroc.min), 3),
  AUROC_Min_DM  = round(c(x0.dm.auroc.min, x1.dm.auroc.min, x2.dm.auroc.min, x3.dm.auroc.min, 
                           x4.dm.auroc.min, x5.dm.auroc.min, x6.dm.auroc.min), 3),
  AUROC_Full_PDM = round(c(x0.pdm.auroc.full, x1.pdm.auroc.full, x2.pdm.auroc.full, x3.pdm.auroc.full, 
                            x4.pdm.auroc.full, x5.pdm.auroc.full, x6.pdm.auroc.full), 3),
  AUROC_Full_DM  = round(c(x0.dm.auroc.full, x1.dm.auroc.full, x2.dm.auroc.full, x3.dm.auroc.full, 
                            x4.dm.auroc.full, x5.dm.auroc.full, x6.dm.auroc.full), 3)
)

# Print the table
print(combined_auroc_table)

# Optional: Display the table nicely using knitr if in RMarkdown
knitr::kable(combined_auroc_table, caption = "AUROC Results for PDM and DM")


```




```{r}
combined_auroc_table <- data.frame(
  Cohort = rep(c("All", "Age>60", "BMI>30", "WC>110", "FIB4>2.67", "eGFR<60", "SBP>140"), 2),
  Dx = rep(c("PDM", "DM"), each = 7),
  AUROC_A1c = round(c(x0.pdm.auroc.a1c, x1.pdm.auroc.a1c, x2.pdm.auroc.a1c, x3.pdm.auroc.a1c, 
                       x4.pdm.auroc.a1c, x5.pdm.auroc.a1c, x6.pdm.auroc.a1c,
                       x0.dm.auroc.a1c, x1.dm.auroc.a1c, x2.dm.auroc.a1c, x3.dm.auroc.a1c, 
                       x4.dm.auroc.a1c, x5.dm.auroc.a1c, x6.dm.auroc.a1c), 3),
  AUROC_Min = round(c(x0.pdm.auroc.min, x1.pdm.auroc.min, x2.pdm.auroc.min, x3.pdm.auroc.min, 
                       x4.pdm.auroc.min, x5.pdm.auroc.min, x6.pdm.auroc.min,
                       x0.dm.auroc.min, x1.dm.auroc.min, x2.dm.auroc.min, x3.dm.auroc.min, 
                       x4.dm.auroc.min, x5.dm.auroc.min, x6.dm.auroc.min), 3),
  AUROC_Full = round(c(x0.pdm.auroc.full, x1.pdm.auroc.full, x2.pdm.auroc.full, x3.pdm.auroc.full, 
                        x4.pdm.auroc.full, x5.pdm.auroc.full, x6.pdm.auroc.full,
                        x0.dm.auroc.full, x1.dm.auroc.full, x2.dm.auroc.full, x3.dm.auroc.full, 
                        x4.dm.auroc.full, x5.dm.auroc.full, x6.dm.auroc.full), 3)
)

# Print the table
print(combined_auroc_table)
```


```{r fig.cap="Figure: This is a figure"}

grid.arrange(ncol=3,
             plot.a1c.bins + labs(tag="A") + theme(axis.text=element_text(size=11),
            axis.title=element_text(size=18),
            plot.tag.position = c(0.01,0.99),
            plot.tag = element_text(size=20),
            plot.title = element_text(hjust = 0.5,size=18) ) ,
            plot.roc.abstract + labs(tag="B") + theme(axis.text=element_text(size=11),
            axis.title=element_text(size=18),
            plot.tag.position = c(0.01,0.99),
            plot.tag = element_text(size=20),
            plot.title = element_text(hjust = 0.5,size=18) ) ,
             plot.ppv + labs(tag="C") + theme(axis.text=element_text(size=11),
            axis.title=element_text(size=18),
            plot.tag.position = c(0.01,0.99),
            plot.tag = element_text(size=20),
            plot.title = element_text(hjust = 0.5,size=18) ) 
             )



```




```{r Manuscript DCA Plots - Cohorts ,  echo=FALSE, include=TRUE}
library(dcurves)

### Age
coh = "Age>60"
x = office_test.Age
df.dca.eval <- x %>% mutate(PreDM = as.integer(two >= 140 & two < 200), DM = as.integer(two >= 200))
df.dca.eval <-df.dca.eval[resample(seq(1,dim(df.dca.eval)[1]),probs=df.dca.eval$sample.ogtt.weight/sum(df.dca.eval$sample.ogtt.weight),size=10000),]

# Pre-Diabetes
### bm = binom.model

bm.pdm.a1c <- glm(data=df.dca.eval,family=binomial,PreDM ~ a1c)#, weights = sample.ogtt.weight)
bm.pdm.min <- glm(data=df.dca.eval,family=binomial,PreDM ~ Pred.MIN)#, weights = sample.ogtt.weight)

df.dca.eval <- df.dca.eval %>% 
  mutate(pm.pdm.a1c = broom::augment(bm.pdm.a1c, type.predict="response") %>% pull(".fitted"), 
         pm.pdm.min = broom::augment(bm.pdm.min, type.predict="response") %>% pull(".fitted"))

plot.dca.eval.pdm.Age <- dca(PreDM ~ pm.pdm.a1c + pm.pdm.min,
    data = df.dca.eval,
    thresholds = seq(0, 0.5, 0.05),
    label = list(  
  pm.pdm.a1c = "A1c",
  pm.pdm.min = "Model"
)) %>%
  plot(smooth = TRUE) + ggtitle(coh)


bm.dm.a1c <- glm(data=df.dca.eval,family=binomial,DM ~ a1c)#, weights = sample.ogtt.weight)
bm.dm.min <- glm(data=df.dca.eval,family=binomial,DM ~ Pred.MIN)#, weights = sample.ogtt.weight)

df.dca.eval <- df.dca.eval %>% 
  mutate(pm.dm.a1c = broom::augment(bm.dm.a1c, type.predict="response") %>% pull(".fitted"), 
         pm.dm.min = broom::augment(bm.dm.min, type.predict="response") %>% pull(".fitted"))

plot.dca.eval.dm.Age <- dca(DM ~ pm.dm.a1c + pm.dm.min,
    data = df.dca.eval,
    thresholds = seq(0, 0.5, 0.05),
    label = list(  
  pm.dm.a1c = "A1c",
  pm.dm.min = "Model"
)) %>%
  plot(smooth = TRUE) + ggtitle(coh)

plot.dca.eval.pdm.Age %>% plot()  %>% suppressWarnings()
plot.dca.eval.dm.Age %>%  plot() %>% suppressWarnings()




### SBP
coh = "SBP>140"
x = office_test.SBP
df.dca.eval <- x %>% mutate(PreDM = as.integer(two >= 140 & two < 200), DM = as.integer(two >= 200))
df.dca.eval <-df.dca.eval[resample(seq(1,dim(df.dca.eval)[1]),probs=df.dca.eval$sample.ogtt.weight/sum(df.dca.eval$sample.ogtt.weight),size=10000),]

bm.pdm.a1c <- glm(data=df.dca.eval,family=binomial,PreDM ~ a1c)#, weights = sample.ogtt.weight)
bm.pdm.min <- glm(data=df.dca.eval,family=binomial,PreDM ~ Pred.MIN)#, weights = sample.ogtt.weight)

df.dca.eval <- df.dca.eval %>% 
  mutate(pm.pdm.a1c = broom::augment(bm.pdm.a1c, type.predict="response") %>% pull(".fitted"), 
         pm.pdm.min = broom::augment(bm.pdm.min, type.predict="response") %>% pull(".fitted"))

plot.dca.eval.pdm.SBP <- dca(PreDM ~ pm.pdm.a1c + pm.pdm.min,
    data = df.dca.eval,
    thresholds = seq(0, 0.5, 0.05),
    label = list(  
  pm.pdm.a1c = "A1c",
  pm.pdm.min = "Model"
)) %>%
  plot(smooth = TRUE) + ggtitle(coh)


bm.dm.a1c <- glm(data=df.dca.eval,family=binomial,DM ~ a1c)#, weights = sample.ogtt.weight)
bm.dm.min <- glm(data=df.dca.eval,family=binomial,DM ~ Pred.MIN)#, weights = sample.ogtt.weight)

df.dca.eval <- df.dca.eval %>% 
  mutate(pm.dm.a1c = broom::augment(bm.dm.a1c, type.predict="response") %>% pull(".fitted"), 
         pm.dm.min = broom::augment(bm.dm.min, type.predict="response") %>% pull(".fitted"))

plot.dca.eval.dm.SBP <- dca(DM ~ pm.dm.a1c + pm.dm.min,
    data = df.dca.eval,
    thresholds = seq(0, 0.5, 0.05),
    label = list(  
  pm.dm.a1c = "A1c",
  pm.dm.min = "Model"
)) %>%
  plot(smooth = TRUE) + ggtitle(coh)

plot.dca.eval.pdm.SBP %>% plot()  %>% suppressWarnings()
plot.dca.eval.dm.SBP %>%  plot() %>% suppressWarnings()

### BMI
coh = "BMI>30"
x = office_test.BMI
df.dca.eval <- x %>% mutate(PreDM = as.integer(two >= 140 & two < 200), DM = as.integer(two >= 200))
df.dca.eval <-df.dca.eval[resample(seq(1,dim(df.dca.eval)[1]),probs=df.dca.eval$sample.ogtt.weight/sum(df.dca.eval$sample.ogtt.weight),size=10000),]

bm.pdm.a1c <- glm(data=df.dca.eval,family=binomial,PreDM ~ a1c)#, weights = sample.ogtt.weight)
bm.pdm.min <- glm(data=df.dca.eval,family=binomial,PreDM ~ Pred.MIN)#, weights = sample.ogtt.weight)

df.dca.eval <- df.dca.eval %>% 
  mutate(pm.pdm.a1c = broom::augment(bm.pdm.a1c, type.predict="response") %>% pull(".fitted"), 
         pm.pdm.min = broom::augment(bm.pdm.min, type.predict="response") %>% pull(".fitted"))

plot.dca.eval.pdm.BMI <- dca(PreDM ~ pm.pdm.a1c + pm.pdm.min,
    data = df.dca.eval,
    thresholds = seq(0, 0.5, 0.05),
    label = list(  
  pm.pdm.a1c = "A1c",
  pm.pdm.min = "Model"
)) %>%
  plot(smooth = TRUE) + ggtitle(coh)


bm.dm.a1c <- glm(data=df.dca.eval,family=binomial,DM ~ a1c)#, weights = sample.ogtt.weight)
bm.dm.min <- glm(data=df.dca.eval,family=binomial,DM ~ Pred.MIN)#, weights = sample.ogtt.weight)

df.dca.eval <- df.dca.eval %>% 
  mutate(pm.dm.a1c = broom::augment(bm.dm.a1c, type.predict="response") %>% pull(".fitted"), 
         pm.dm.min = broom::augment(bm.dm.min, type.predict="response") %>% pull(".fitted"))

plot.dca.eval.dm.BMI <- dca(DM ~ pm.dm.a1c + pm.dm.min,
    data = df.dca.eval,
    thresholds = seq(0, 0.5, 0.05),
    label = list(  
  pm.dm.a1c = "A1c",
  pm.dm.min = "Model"
)) %>%
  plot(smooth = TRUE)  + ggtitle(coh)

plot.dca.eval.pdm.BMI %>% plot()  %>% suppressWarnings()
plot.dca.eval.dm.BMI %>%  plot() %>% suppressWarnings()


### FIB4
coh = "FIB-4>2.67"
x = office_test.FIB4
df.dca.eval <- x %>% mutate(PreDM = as.integer(two >= 140 & two < 200), DM = as.integer(two >= 200))
df.dca.eval <-df.dca.eval[resample(seq(1,dim(df.dca.eval)[1]),probs=df.dca.eval$sample.ogtt.weight/sum(df.dca.eval$sample.ogtt.weight),size=10000),]

bm.pdm.a1c <- glm(data=df.dca.eval,family=binomial,PreDM ~ a1c)#, weights = sample.ogtt.weight)
bm.pdm.min <- glm(data=df.dca.eval,family=binomial,PreDM ~ Pred.MIN)#, weights = sample.ogtt.weight)

df.dca.eval <- df.dca.eval %>% 
  mutate(pm.pdm.a1c = broom::augment(bm.pdm.a1c, type.predict="response") %>% pull(".fitted"), 
         pm.pdm.min = broom::augment(bm.pdm.min, type.predict="response") %>% pull(".fitted"))

plot.dca.eval.pdm.FIB4 <- dca(PreDM ~ pm.pdm.a1c + pm.pdm.min,
    data = df.dca.eval,
    thresholds = seq(0, 0.5, 0.05),
    label = list(  
  pm.pdm.a1c = "A1c",
  pm.pdm.min = "Model"
)) %>%
  plot(smooth = TRUE) + ggtitle(coh)


bm.dm.a1c <- glm(data=df.dca.eval,family=binomial,DM ~ a1c)#, weights = sample.ogtt.weight)
bm.dm.min <- glm(data=df.dca.eval,family=binomial,DM ~ Pred.MIN)#, weights = sample.ogtt.weight)

df.dca.eval <- df.dca.eval %>% 
  mutate(pm.dm.a1c = broom::augment(bm.dm.a1c, type.predict="response") %>% pull(".fitted"), 
         pm.dm.min = broom::augment(bm.dm.min, type.predict="response") %>% pull(".fitted"))

plot.dca.eval.dm.FIB4 <- dca(DM ~ pm.dm.a1c + pm.dm.min,
    data = df.dca.eval,
    thresholds = seq(0, 0.5, 0.05),
    label = list(  
  pm.dm.a1c = "A1c",
  pm.dm.min = "Model"
)) %>%
  plot(smooth = TRUE)  + ggtitle(coh)

plot.dca.eval.pdm.FIB4 %>% plot()  %>% suppressWarnings()
plot.dca.eval.dm.FIB4 %>%  plot() %>% suppressWarnings()




### GGT
coh = "eGFR<60"
x = office_test.eGFR
df.dca.eval <- x %>% mutate(PreDM = as.integer(two >= 140 & two < 200), DM = as.integer(two >= 200))
df.dca.eval <-df.dca.eval[resample(seq(1,dim(df.dca.eval)[1]),probs=df.dca.eval$sample.ogtt.weight/sum(df.dca.eval$sample.ogtt.weight),size=10000),]

bm.pdm.a1c <- glm(data=df.dca.eval,family=binomial,PreDM ~ a1c)#, weights = sample.ogtt.weight)
bm.pdm.min <- glm(data=df.dca.eval,family=binomial,PreDM ~ Pred.MIN)#, weights = sample.ogtt.weight)

df.dca.eval <- df.dca.eval %>% 
  mutate(pm.pdm.a1c = broom::augment(bm.pdm.a1c, type.predict="response") %>% pull(".fitted"), 
         pm.pdm.min = broom::augment(bm.pdm.min, type.predict="response") %>% pull(".fitted"))

plot.dca.eval.pdm.eGFR <- dca(PreDM ~ pm.pdm.a1c + pm.pdm.min,
    data = df.dca.eval,
    thresholds = seq(0, 0.5, 0.05),
    label = list(  
  pm.pdm.a1c = "A1c",
  pm.pdm.min = "Model"
)) %>%
  plot(smooth = TRUE) + ggtitle(coh)


bm.dm.a1c <- glm(data=df.dca.eval,family=binomial,DM ~ a1c)#, weights = sample.ogtt.weight)
bm.dm.min <- glm(data=df.dca.eval,family=binomial,DM ~ Pred.MIN)#, weights = sample.ogtt.weight)

df.dca.eval <- df.dca.eval %>% 
  mutate(pm.dm.a1c = broom::augment(bm.dm.a1c, type.predict="response") %>% pull(".fitted"), 
         pm.dm.min = broom::augment(bm.dm.min, type.predict="response") %>% pull(".fitted"))

plot.dca.eval.dm.eGFR <- dca(DM ~ pm.dm.a1c + pm.dm.min,
    data = df.dca.eval,
    thresholds = seq(0, 0.5, 0.05),
    label = list(  
  pm.dm.a1c = "A1c",
  pm.dm.min = "Model"
)) %>%
  plot(smooth = TRUE)  + ggtitle(coh)


plot.dca.eval.pdm.eGFR %>% plot()  %>% suppressWarnings()
plot.dca.eval.dm.eGFR %>%  plot() %>% suppressWarnings()

### 
coh = "All"
x = office_test.All
df.dca.eval <- x %>% mutate(PreDM = as.integer(two >= 140 & two < 200), DM = as.integer(two >= 200))
df.dca.eval <-df.dca.eval[resample(seq(1,dim(df.dca.eval)[1]),probs=df.dca.eval$sample.ogtt.weight/sum(df.dca.eval$sample.ogtt.weight),size=10000),]

bm.pdm.a1c <- glm(data=df.dca.eval,family=binomial,PreDM ~ a1c)#, weights = sample.ogtt.weight)
bm.pdm.min <- glm(data=df.dca.eval,family=binomial,PreDM ~ Pred.MIN)#, weights = sample.ogtt.weight)

df.dca.eval <- df.dca.eval %>% 
  mutate(pm.pdm.a1c = broom::augment(bm.pdm.a1c, type.predict="response") %>% pull(".fitted"), 
         pm.pdm.min = broom::augment(bm.pdm.min, type.predict="response") %>% pull(".fitted"))

plot.dca.eval.pdm.All <- dca(PreDM ~ pm.pdm.a1c + pm.pdm.min,
    data = df.dca.eval,
    thresholds = seq(0, 0.5, 0.05),
    label = list(  
  pm.pdm.a1c = "A1c",
  pm.pdm.min = "Model"
)) %>%
  plot(smooth = TRUE) + ggtitle(coh)


bm.dm.a1c <- glm(data=df.dca.eval,family=binomial,DM ~ a1c)#, weights = sample.ogtt.weight)
bm.dm.min <- glm(data=df.dca.eval,family=binomial,DM ~ Pred.MIN)#, weights = sample.ogtt.weight)

df.dca.eval <- df.dca.eval %>% 
  mutate(pm.dm.a1c = broom::augment(bm.dm.a1c, type.predict="response") %>% pull(".fitted"), 
         pm.dm.min = broom::augment(bm.dm.min, type.predict="response") %>% pull(".fitted"))

plot.dca.eval.dm.All <- dca(DM ~ pm.dm.a1c + pm.dm.min,
    data = df.dca.eval,
    thresholds = seq(0, 0.5, 0.05),
    label = list(  
  pm.dm.a1c = "A1c",
  pm.dm.min = "Model"
)) %>%
  plot(smooth = TRUE)  + ggtitle(coh)

plot.dca.eval.pdm.All %>% plot()  %>% suppressWarnings()
plot.dca.eval.dm.All %>%  plot() %>% suppressWarnings()


library(grid)
library(cowplot)

legend1<-get_legend(
  plot.dca.eval.pdm.All +theme(legend.direction = "horizontal" ) + scale_color_discrete(labels=c("Test All","Test None","A1c","Model"))
  ) 

grid.dca.pdm.dm <- grid.arrange(nrow=2,heights=c(3,0.3),
  arrangeGrob(ncol=2,
    plot.dca.eval.pdm.All + theme(legend.position = "none") + ggtitle("Pre-Diabetes"),
    plot.dca.eval.dm.All + theme(legend.position = "none") + ggtitle("Diabetes")),
  legend1,top = textGrob("All Participants"))%>% suppressWarnings()
ggsave(file='~/Dropbox/NHANES manuscript/DCA-Grid-PDM-DM.jpg',plot=grid.dca.pdm.dm,width=7,height=3.5,units="in")




legend1<-get_legend(
  plot.dca.eval.pdm.All +theme(legend.direction = "horizontal" ) + scale_color_discrete(labels=c("Test All","Test None","A1c","Model"))
  ) 

grid.dca.pdm <- grid.arrange(nrow=3,heights=c(3,3,0.5),
            arrangeGrob(ncol=3,                             
            plot.dca.eval.pdm.All + theme(legend.position = "none"),             
             plot.dca.eval.pdm.Age+ theme(legend.position = "none"),
             plot.dca.eval.pdm.BMI+ theme(legend.position = "none")),
            arrangeGrob(ncol=3,            
             plot.dca.eval.pdm.FIB4+ theme(legend.position = "none"),
             plot.dca.eval.pdm.eGFR+ theme(legend.position = "none"),
             plot.dca.eval.pdm.SBP+ theme(legend.position = "none")),
            legend1,
             top = textGrob("Pre-Diabetes")
             ) %>% suppressWarnings()
ggsave(file='~/Dropbox/NHANES manuscript/DCA-Grid-PDM.jpg',plot=grid.dca.pdm)

library(cowplot)
legend1<-get_legend(
  plot.dca.eval.dm.All +theme(legend.direction = "horizontal" ) + scale_color_discrete(labels=c("Test All","Test None","A1c","Model"))
  ) 

grid.dca.dm <- grid.arrange(nrow=3,heights=c(3,3,0.5),
            arrangeGrob(ncol=3,
            plot.dca.eval.dm.All + theme(legend.position = "none"),             
             plot.dca.eval.dm.Age+ theme(legend.position = "none"),
             plot.dca.eval.dm.BMI+ theme(legend.position = "none")),
            arrangeGrob(ncol=3,
             plot.dca.eval.dm.FIB4+ theme(legend.position = "none"),
             plot.dca.eval.dm.eGFR+ theme(legend.position = "none"),
             plot.dca.eval.dm.SBP+ theme(legend.position = "none")),
            legend1,
             top = textGrob("Diabetes")
             ) %>% suppressWarnings()

ggsave(file='~/Dropbox/NHANES manuscript/DCA-Grid-DM.jpg',plot=grid.dca.dm)

```





```{r}

gold_standard_threshold <- 200

data<- bind_rows(
office_test.Age %>% select(two,a1c,Pred.MIN) %>% mutate(Cohort="Age>60"),
office_test.All %>% select(two,a1c,Pred.MIN) %>% mutate(Cohort="All"),
office_test.BMI %>% select(two,a1c,Pred.MIN) %>% mutate(Cohort="BMI"),
office_test.FIB4 %>% select(two,a1c,Pred.MIN) %>% mutate(Cohort="FIB4"),
office_test.GGT %>% select(two,a1c,Pred.MIN) %>% mutate(Cohort="GGT"),
office_test.SBP %>% select(two,a1c,Pred.MIN) %>% mutate(Cohort="SBP")
) 




calculate_metrics <- function(data, test_var, gold_standard, threshold) {
  data %>%
    mutate(
      gold_standard_pos = !!sym(gold_standard) >= threshold,
      test_var_pos = !!sym(test_var) >= threshold
    ) %>%
    summarise(
      TP = sum(gold_standard_pos & test_var_pos),
      FP = sum(!gold_standard_pos & test_var_pos),
      FN = sum(gold_standard_pos & !test_var_pos)
    )
}

metrics_a1c <- data %>%
  group_by(Cohort) %>%
  do(calculate_metrics(., "a1c", "two", gold_standard_threshold)) %>%
  mutate(Test_Var = "a1c")

metrics_pred_min <- data %>%
  group_by(Cohort) %>%
  do(calculate_metrics(., "Pred.MIN", "two", gold_standard_threshold)) %>%
  mutate(Test_Var = "Pred.MIN")

metrics <- bind_rows(metrics_a1c, metrics_pred_min)

metrics

```







```{r}



calculate_metrics_two_dm <- function(data, pred_min_threshold) {
  data %>%
    mutate(
      gold_standard_pos = two >= 200,  # Gold standard: values in 'two' greater than or equal to 200
      test_var_pos = Pred.MIN >= pred_min_threshold  # Test variable: Pred.MIN greater than or equal to threshold
    ) %>%
    summarise(
      TP = sum(gold_standard_pos & test_var_pos),
      FP = sum(!gold_standard_pos & test_var_pos),
      FN = sum(gold_standard_pos & !test_var_pos),
      TN = sum(!gold_standard_pos & !test_var_pos),
      Precision = if_else(TP + FP > 0, TP / (TP + FP), 0),
      Recall = if_else(TP + FN > 0, TP / (TP + FN), 0),
      F1 = if_else(Precision + Recall > 0, 2 * Precision * Recall / (Precision + Recall), 0),
      Accuracy = (TP + TN) / (TP + FP + FN + TN)
    )
}

calculate_metrics_a1c_dm <- function(data, pred_min_threshold) {
  data %>%
    mutate(
      gold_standard_pos = two >= 200,  # Gold standard: values in 'two' greater than or equal to 200
      test_var_pos = a1c >= 6.5 ) %>%   # Note we can change this to 
    dplyr::summarise(
      TP = sum(gold_standard_pos & test_var_pos,na.rm=TRUE),
      FP = sum(!gold_standard_pos & test_var_pos,na.rm=TRUE),
      FN = sum(gold_standard_pos & !test_var_pos,na.rm=TRUE),
      TN = sum(!gold_standard_pos & !test_var_pos,na.rm=TRUE),
      Precision = if_else(TP + FP > 0, TP / (TP + FP), 0),
      Recall = if_else(TP + FN > 0, TP / (TP + FN), 0),
      F1 = if_else(Precision + Recall > 0, 2 * Precision * Recall / (Precision + Recall), 0),
      Accuracy = (TP + TN) / (TP + FP + FN + TN)
    )
}

calculate_metrics_two_pdm <- function(data, pred_min_threshold,pred_max_threshold=NA) {
  pred_max_threshold = ifelse(is.na(pred_max_threshold),100000000000,pred_max_threshold )
  data %>%
    mutate(
      gold_standard_pos = two >= 140 & two < 200,  # Gold standard: values in 'two' greater than or equal to 200
      test_var_pos = Pred.MIN >= pred_min_threshold & Pred.MIN < pred_max_threshold  # Test variable: Pred.MIN greater than or equal to threshold
    ) %>%
    summarise(
      TP = sum(gold_standard_pos & test_var_pos),
      FP = sum(!gold_standard_pos & test_var_pos),
      FN = sum(gold_standard_pos & !test_var_pos),
      TN = sum(!gold_standard_pos & !test_var_pos),
      Precision = if_else(TP + FP > 0, TP / (TP + FP), 0),
      Recall = if_else(TP + FN > 0, TP / (TP + FN), 0),
      F1 = if_else(Precision + Recall > 0, 2 * Precision * Recall / (Precision + Recall), 0),
      Accuracy = (TP + TN) / (TP + FP + FN + TN)
    )
}

calculate_metrics_a1c_pdm <- function(data, pred_min_threshold,pred_max_threshold=NA) {
  pred_max_threshold = ifelse(is.na(pred_max_threshold),100000000000,pred_max_threshold )
  data %>%
    mutate(
      gold_standard_pos = two >= 140 & two < 200,  # Gold standard: values in 'two' greater than or equal to 200
      test_var_pos = a1c >= 5.7 & a1c<6.5) %>%   # Note we can change this to 
    dplyr::summarise(
      TP = sum(gold_standard_pos & test_var_pos,na.rm=TRUE),
      FP = sum(!gold_standard_pos & test_var_pos,na.rm=TRUE),
      FN = sum(gold_standard_pos & !test_var_pos,na.rm=TRUE),
      TN = sum(!gold_standard_pos & !test_var_pos,na.rm=TRUE),
      Precision = if_else(TP + FP > 0, TP / (TP + FP), 0),
      Recall = if_else(TP + FN > 0, TP / (TP + FN), 0),
      F1 = if_else(Precision + Recall > 0, 2 * Precision * Recall / (Precision + Recall), 0),
      Accuracy = (TP + TN) / (TP + FP + FN + TN)
    )
}


```





```{r CALCULATING METRICS }


f.pROC.cutoff <- function(x,predictor.x,response.x) 
pROC::coords(pROC::roc_(data=x,predictor=predictor.x,response=response.x),"best")["threshold"] 


int.resample.df <- resample(seq(1,dim(df %>% drop_na(two,a1c,sample.ogtt.weight))[1]),probs=sample.ogtt.weight/sum(sample.ogtt.weight),size=10000)
#f.pROC.cutoff(office_test.FIB4,"a1c","DM")

x <- office_test.FIB4
x <- x[resample(seq(1,nrow(x)),probs=x$sample.ogtt.weight/sum(x$sample.ogtt.weight),size=10000),]
x$PDM <- as.factor(x$two >= 140 & x$two < 200)
x$DM <- as.factor(x$two >= 200)
x.metric.a1c.FIB4 <- calculate_metrics_a1c_dm(x, unlist(f.pROC.cutoff(x,"a1c","DM"))) %>%     mutate(Stat="a1c",Cohort="FIB4>2.67",Dx="DM")
x.metric.min.FIB4 <- calculate_metrics_two_dm(x, unlist(f.pROC.cutoff(x,"Pred.MIN","DM"))) %>% mutate(Stat="Pred.MIN",Cohort="FIB4>2.67",Dx="DM")

x <- office_test.Age
x <- x[resample(seq(1,nrow(x)),probs=x$sample.ogtt.weight/sum(x$sample.ogtt.weight),size=10000),]
x$PDM <- as.factor(x$two >= 140 & x$two < 200)
x$DM <- as.factor(x$two >= 200)
co <- "Age>60"
dx <- "DM"
x.metric.a1c.Age <- calculate_metrics_a1c_dm(x, unlist(f.pROC.cutoff(x,"a1c",dx))) %>%     mutate(Stat="a1c",Cohort=co,Dx=dx)
x.metric.min.Age <- calculate_metrics_two_dm(x, unlist(f.pROC.cutoff(x,"Pred.MIN",dx)) )%>% mutate(Stat="Pred.MIN",Cohort=co,Dx=dx)


x <- office_test.All
x <- x[resample(seq(1,nrow(x)),probs=x$sample.ogtt.weight/sum(x$sample.ogtt.weight),size=10000),]
x$PDM <- as.factor(x$two >= 140 & x$two < 200)
x$DM <- as.factor(x$two >= 200)
co <- "All"
dx <- "DM"
x.metric.a1c.All <- calculate_metrics_a1c_dm(x, unlist(f.pROC.cutoff(x,"a1c",dx))) %>%     mutate(Stat="a1c",Cohort=co,Dx=dx)
x.metric.min.All <- calculate_metrics_two_dm(x, unlist(f.pROC.cutoff(x,"Pred.MIN",dx)) )%>% mutate(Stat="Pred.MIN",Cohort=co,Dx=dx)

x <- office_test.eGFR
x <- x[resample(seq(1,nrow(x)),probs=x$sample.ogtt.weight/sum(x$sample.ogtt.weight),size=10000),]
x$PDM <- as.factor(x$two >= 140 & x$two < 200)
x$DM <- as.factor(x$two >= 200)
co <- "GGT>40"
dx <- "DM"
x.metric.a1c.eGFR<- calculate_metrics_a1c_dm(x, unlist(f.pROC.cutoff(x,"a1c",dx))) %>%     mutate(Stat="a1c",Cohort=co,Dx=dx)
x.metric.min.eGFR <- calculate_metrics_two_dm(x, unlist(f.pROC.cutoff(x,"Pred.MIN",dx)) )%>% mutate(Stat="Pred.MIN",Cohort=co,Dx=dx)

x <- office_test.SBP
x <- x[resample(seq(1,nrow(x)),probs=x$sample.ogtt.weight/sum(x$sample.ogtt.weight),size=10000),]
x$PDM <- as.factor(x$two >= 140 & x$two < 200)
x$DM <- as.factor(x$two >= 200)
co <- "SBP>140"
dx <- "DM"
x.metric.a1c.SBP<- calculate_metrics_a1c_dm(x, unlist(f.pROC.cutoff(x,"a1c",dx))) %>%     mutate(Stat="a1c",Cohort=co,Dx=dx)
x.metric.min.SBP <- calculate_metrics_two_dm(x, unlist(f.pROC.cutoff(x,"Pred.MIN",dx)) )%>% mutate(Stat="Pred.MIN",Cohort=co,Dx=dx)

x <- office_test.BMI
x <- x[resample(seq(1,nrow(x)),probs=x$sample.ogtt.weight/sum(x$sample.ogtt.weight),size=10000),]
x$PDM <- as.factor(x$two >= 140 & x$two < 200)
x$DM <- as.factor(x$two >= 200)
co <- "BMI>30"
dx <- "DM"
x.metric.a1c.BMI<- calculate_metrics_a1c_dm(x, unlist(f.pROC.cutoff(x,"a1c",dx))) %>%     mutate(Stat="a1c",Cohort=co,Dx=dx)
x.metric.min.BMI <- calculate_metrics_two_dm(x, unlist(f.pROC.cutoff(x,"Pred.MIN",dx)) )%>% mutate(Stat="Pred.MIN",Cohort=co,Dx=dx)

# 
# 
# 
# 
# x <- office_test.
# x$PDM <- as.factor(x$two >= 140 & x$two < 200)
# x$DM <- as.factor(x$two >= 200)
# co <- ""
# dx <- "DM"
# x.metric.a1c. <- calculate_metrics(x, f.pROC.cutoff(x,"a1c",dx)) %>%     mutate(Stat="a1c",Cohort=co,Dx=dx)
# x.metric.min. <- calculate_metrics(x, f.pROC.cutoff(x,"Pred.MIN",dx)) %>% mutate(Stat="Pred.MIN",Cohort=co,Dx=dx)


x.metrics<-bind_rows(
  x.metric.a1c.FIB4,
  x.metric.min.FIB4,
  x.metric.a1c.Age,
  x.metric.min.Age, 
  x.metric.a1c.All,
  x.metric.min.All,
  x.metric.a1c.BMI,
  x.metric.min.BMI, 
  x.metric.a1c.eGFR,
  x.metric.min.eGFR,
  x.metric.a1c.SBP,
  x.metric.min.SBP)


x <- office_test.FIB4
x <- x[resample(seq(1,nrow(x)),probs=x$sample.ogtt.weight/sum(x$sample.ogtt.weight),size=10000),]
x$PDM <- as.factor(x$two >= 140 & x$two < 200)
x$DM <- as.factor(x$two >= 200)
x.metric.a1c.FIB4 <- calculate_metrics_a1c_pdm(x, unlist(f.pROC.cutoff(x,"a1c","PDM"))) %>%     mutate(Stat="a1c",Cohort="FIB4>2.67",Dx="PDM")
x.metric.min.FIB4 <- calculate_metrics_two_pdm(x, unlist(f.pROC.cutoff(x,"Pred.MIN","PDM")),unlist(f.pROC.cutoff(x,"Pred.MIN","DM"))) %>% mutate(Stat="Pred.MIN",Cohort="FIB4>2.67",Dx="PDM")

x <- office_test.Age
x <- x[resample(seq(1,nrow(x)),probs=x$sample.ogtt.weight/sum(x$sample.ogtt.weight),size=10000),]
x$PDM <- as.factor(x$two >= 140 & x$two < 200)
x$DM <- as.factor(x$two >= 200)
co <- "Age>60"
dx <- "PDM"
x.metric.a1c.Age <- calculate_metrics_a1c_pdm(x, unlist(f.pROC.cutoff(x,"a1c",dx))) %>%     mutate(Stat="a1c",Cohort=co,Dx=dx)
x.metric.min.Age <- calculate_metrics_two_pdm(x, unlist(f.pROC.cutoff(x,"Pred.MIN",dx)),unlist(f.pROC.cutoff(x,"Pred.MIN","DM")))%>% mutate(Stat="Pred.MIN",Cohort=co,Dx=dx)


x <- office_test.All
x <- x[resample(seq(1,nrow(x)),probs=x$sample.ogtt.weight/sum(x$sample.ogtt.weight),size=10000),]
x$PDM <- as.factor(x$two >= 140 & x$two < 200)
x$DM <- as.factor(x$two >= 200)
co <- "All"
dx <- "PDM"
x.metric.a1c.All <- calculate_metrics_a1c_pdm(x, unlist(f.pROC.cutoff(x,"a1c",dx))) %>%     mutate(Stat="a1c",Cohort=co,Dx=dx)
x.metric.min.All <- calculate_metrics_two_pdm(x, unlist(f.pROC.cutoff(x,"Pred.MIN",dx)),unlist(f.pROC.cutoff(x,"Pred.MIN","DM")))%>% mutate(Stat="Pred.MIN",Cohort=co,Dx=dx)

x <- office_test.eGFR
x <- x[resample(seq(1,nrow(x)),probs=x$sample.ogtt.weight/sum(x$sample.ogtt.weight),size=10000),]
x$PDM <- as.factor(x$two >= 140 & x$two < 200)
x$DM <- as.factor(x$two >= 200)
co <- "eGFR<60"
dx <- "PDM"
x.metric.a1c.eGFR<- calculate_metrics_a1c_pdm(x, unlist(f.pROC.cutoff(x,"a1c",dx))) %>%     mutate(Stat="a1c",Cohort=co,Dx=dx)
x.metric.min.eGFR <- calculate_metrics_two_pdm(x, unlist(f.pROC.cutoff(x,"Pred.MIN",dx)),unlist(f.pROC.cutoff(x,"Pred.MIN","DM")))%>% mutate(Stat="Pred.MIN",Cohort=co,Dx=dx)

x <- office_test.SBP
x <- x[resample(seq(1,nrow(x)),probs=x$sample.ogtt.weight/sum(x$sample.ogtt.weight),size=10000),]
x$PDM <- as.factor(x$two >= 140 & x$two < 200)
x$DM <- as.factor(x$two >= 200)
co <- "SBP>140"
dx <- "PDM"
x.metric.a1c.SBP<- calculate_metrics_a1c_pdm(x, unlist(f.pROC.cutoff(x,"a1c",dx))) %>%     mutate(Stat="a1c",Cohort=co,Dx=dx)
x.metric.min.SBP <- calculate_metrics_two_pdm(x, unlist(f.pROC.cutoff(x,"Pred.MIN",dx)),unlist(f.pROC.cutoff(x,"Pred.MIN","DM")))%>% mutate(Stat="Pred.MIN",Cohort=co,Dx=dx)

x <- office_test.BMI
x <- x[resample(seq(1,nrow(x)),probs=x$sample.ogtt.weight/sum(x$sample.ogtt.weight),size=10000),]
x$PDM <- as.factor(x$two >= 140 & x$two < 200)
x$DM <- as.factor(x$two >= 200)
co <- "BMI>30"
dx <- "PDM"
x.metric.a1c.BMI<- calculate_metrics_a1c_pdm(x, unlist(f.pROC.cutoff(x,"a1c",dx))) %>%     mutate(Stat="a1c",Cohort=co,Dx=dx)
x.metric.min.BMI <- calculate_metrics_two_pdm(x, unlist(f.pROC.cutoff(x,"Pred.MIN",dx)),unlist(f.pROC.cutoff(x,"Pred.MIN","DM")))%>% mutate(Stat="Pred.MIN",Cohort=co,Dx=dx)

# 
x.metrics <- bind_rows(  x.metrics,
  x.metric.a1c.FIB4,
  x.metric.min.FIB4,
  x.metric.a1c.Age,
  x.metric.min.Age, 
  x.metric.a1c.All,
  x.metric.min.All,
  x.metric.a1c.BMI,
  x.metric.min.BMI, 
  x.metric.a1c.eGFR,
  x.metric.min.eGFR,
  x.metric.a1c.SBP,
  x.metric.min.SBP)

grid.arrange(ncol=2,
x.metrics %>%  filter(Dx=="PDM") %>% group_by(Cohort,Stat,Dx) %>% summarise(Cohort=Cohort,Stat=Stat,Dx=Dx,Observed=TP+FP,Expected=TP+FN) %>% 
  pivot_longer(-c(Cohort,Stat,Dx),names_to = "Variable",values_to = "Value")  %>%  ggplot() + geom_col(aes(x=Stat,y=Value,fill=Variable),position="dodge") + facet_wrap(~Cohort,scales = 'free') + labs(title="Pre-Diabetes Diagnosis"),
x.metrics %>%  filter(Dx=="DM") %>% group_by(Cohort,Stat,Dx) %>% summarise(Cohort=Cohort,Stat=Stat,Dx=Dx,Observed=TP+FP,Expected=TP+FN) %>% 
  pivot_longer(-c(Cohort,Stat,Dx),names_to = "Variable",values_to = "Value")  %>%  ggplot() + geom_col(aes(x=Stat,y=Value,fill=Variable),position="dodge") + facet_wrap(~Cohort,scales="free") + labs(title="Diabetes Diagnosis")
)  
  
bind_rows(
  x.metric.a1c.FIB4,
  x.metric.min.FIB4,
  x.metric.a1c.Age,
  x.metric.min.Age 
) %>% ggplot() +  
  geom_col(aes(x=Stat,y=TP+FP),fill='red',position=position_nudge(x=0.5)) + 
  geom_col(aes(x=Stat,y=TP+FN),fill='blue',position=position_nudge(x=-0.5)) + facet_grid(Cohort ~ Stat,scales="free")  
  

office_test.Age%>% ggplot() + geom_point(aes(x=a1c,y=two,color=a1c>=6.5 & two>=200))

office_test.Age %>% filter( a1c>=5.95 & two>=200) %>% dim()
office_test.Age %>% filter( two>=200)%>% dim()
36/690
```


```{r}

plot.metrics.pdm <- x.metrics %>%  filter(Dx=="PDM") %>% filter(Cohort=="All") %>% group_by(Cohort,Stat,Dx) %>% summarise(Cohort=Cohort,Stat=Stat,Dx=Dx,TP=TP,FP=FP,FN=FN,TN=TN) %>% 
  pivot_longer(-c(Cohort,Stat,Dx),names_to = "Variable",values_to = "Value")  %>% mutate(Stat=ifelse(Stat=="a1c","A1c",ifelse(Stat=="Pred.MIN","Model",NA))) %>%  ggplot() + geom_col(aes(x=Stat,y=Value,fill=Variable),position="dodge") + facet_wrap(~Cohort,scales = 'free') + labs(title="Pre-Diabetes Diagnosis") #+ scale_fill_discrete(label=c("Expected (TP+FN)","Observed (TP+FP)"))

plot.metrics.dm <- x.metrics %>%  filter(Dx=="DM") %>% filter(Cohort=="All")%>% group_by(Cohort,Stat,Dx) %>% summarise(Cohort=Cohort,Stat=Stat,Dx=Dx,TP=TP,FP=FP,FN=FN,TN=TN) %>% 
  pivot_longer(-c(Cohort,Stat,Dx),names_to = "Variable",values_to = "Value")  %>% mutate(Stat=ifelse(Stat=="a1c","A1c",ifelse(Stat=="Pred.MIN","Model",NA)))  %>%  ggplot() + geom_col(aes(x=Stat,y=Value,fill=Variable),position="dodge") + facet_wrap(~Cohort,scales="free") + labs(title="Diabetes Diagnosis") #+ scale_fill_discrete(label=c("Expected (TP+FN)","Observed (TP+FP)"))

legend2 <- get_legend(plot.metrics.dm + theme(legend.direction = "horizontal" ))

plot.tpfp.all<-grid.arrange(nrow=2,heights=c(3,0.2),
arrangeGrob(ncol=2,
            plot.metrics.pdm + theme(legend.position="none"),
            plot.metrics.dm + theme(legend.position="none")),
legend2
)
ggsave(file="~/Dropbox/NHANES manuscript/TPFP-all-A1c-vs-Model.jpg",plot=plot.tpfp.all)



plot.metrics.pdm <- x.metrics %>%  filter(Dx=="PDM") %>% group_by(Cohort,Stat,Dx) %>% summarise(Cohort=Cohort,Stat=Stat,Dx=Dx,TP=TP,FP=FP,FN=FN,TN=TN) %>% 
  pivot_longer(-c(Cohort,Stat,Dx),names_to = "Variable",values_to = "Value") %>% mutate(Stat=ifelse(Stat=="a1c","A1c",ifelse(Stat=="Pred.MIN","Model",NA)))  %>%  ggplot() + geom_col(aes(x=Stat,y=Value,fill=Variable),position="dodge") + facet_wrap(~Cohort,scales = 'free') + labs(title="Pre-Diabetes Diagnosis") #+ scale_fill_discrete(label=c("Expected (TP+FN)","Observed (TP+FP)"))

plot.metrics.dm <- x.metrics %>%  filter(Dx=="DM") %>% group_by(Cohort,Stat,Dx) %>% summarise(Cohort=Cohort,Stat=Stat,Dx=Dx,TP=TP,FP=FP,FN=FN,TN=TN) %>% 
  pivot_longer(-c(Cohort,Stat,Dx),names_to = "Variable",values_to = "Value") %>% mutate(Stat=ifelse(Stat=="a1c","A1c",ifelse(Stat=="Pred.MIN","Model",NA)))   %>%  ggplot() + geom_col(aes(x=Stat,y=Value,fill=Variable),position="dodge") + facet_wrap(~Cohort,scales="free") + labs(title="Diabetes Diagnosis") #+ scale_fill_discrete(label=c("Expected (TP+FN)","Observed (TP+FP)"))

legend2 <- get_legend(plot.metrics.dm + theme(legend.direction = "horizontal" ))

plot.tpfp.cohorts<- grid.arrange(nrow=2,heights=c(3,0.2),
arrangeGrob(ncol=2,
            plot.metrics.pdm + theme(legend.position="none"),
            plot.metrics.dm + theme(legend.position="none")),
legend2
)
ggsave(file="~/Dropbox/NHANES manuscript/TPFP-Cohorts-A1c-vs-Model.jpg",plot=plot.tpfp.cohorts)

```





```{r CALCULATING METRICS - A1c 6.5%}
#dev.off()

f.pROC.cutoff <- function(x,predictor.x,response.x) 
pROC::coords(pROC::roc_(data=x,predictor=predictor.x,response=response.x),"best")["threshold"] 



#f.pROC.cutoff(office_test.FIB4,"a1c","DM")

x <- office_test.FIB4 %>% filter(a1c<6.5)
x$PDM <- as.factor(x$two >= 140 & x$two < 200)
x$DM <- as.factor(x$two >= 200)
x.metric.a1c.FIB4 <- calculate_metrics_a1c_dm(x, unlist(f.pROC.cutoff(x,"a1c","DM"))) %>%     mutate(Stat="a1c",Cohort="FIB4>2.67",Dx="DM")
x.metric.min.FIB4 <- calculate_metrics_two_dm(x, unlist(f.pROC.cutoff(x,"Pred.MIN","DM"))) %>% mutate(Stat="Pred.MIN",Cohort="FIB4>2.67",Dx="DM")

x <- office_test.Age %>% filter(a1c<6.5)
x$PDM <- as.factor(x$two >= 140 & x$two < 200)
x$DM <- as.factor(x$two >= 200)
co <- "Age>60"
dx <- "DM"
x.metric.a1c.Age <- calculate_metrics_a1c_dm(x, unlist(f.pROC.cutoff(x,"a1c",dx))) %>%     mutate(Stat="a1c",Cohort=co,Dx=dx)
x.metric.min.Age <- calculate_metrics_two_dm(x, unlist(f.pROC.cutoff(x,"Pred.MIN",dx)) )%>% mutate(Stat="Pred.MIN",Cohort=co,Dx=dx)


x <- office_test.All %>% filter(a1c<6.5)
x$PDM <- as.factor(x$two >= 140 & x$two < 200)
x$DM <- as.factor(x$two >= 200)
co <- "All"
dx <- "DM"
x.metric.a1c.All <- calculate_metrics_a1c_dm(x, unlist(f.pROC.cutoff(x,"a1c",dx))) %>%     mutate(Stat="a1c",Cohort=co,Dx=dx)
x.metric.min.All <- calculate_metrics_two_dm(x, unlist(f.pROC.cutoff(x,"Pred.MIN",dx)) )%>% mutate(Stat="Pred.MIN",Cohort=co,Dx=dx)

x <- office_test.eGFR %>% filter(a1c<6.5)
x$PDM <- as.factor(x$two >= 140 & x$two < 200)
x$DM <- as.factor(x$two >= 200)
co <- "eGFR<60"
dx <- "DM"
x.metric.a1c.eGFR<- calculate_metrics_a1c_dm(x, unlist(f.pROC.cutoff(x,"a1c",dx))) %>%     mutate(Stat="a1c",Cohort=co,Dx=dx)
x.metric.min.eGFR <- calculate_metrics_two_dm(x, unlist(f.pROC.cutoff(x,"Pred.MIN",dx)) )%>% mutate(Stat="Pred.MIN",Cohort=co,Dx=dx)

x <- office_test.SBP %>% filter(a1c<6.5)
x$PDM <- as.factor(x$two >= 140 & x$two < 200)
x$DM <- as.factor(x$two >= 200)
co <- "SBP>140"
dx <- "DM"
x.metric.a1c.SBP<- calculate_metrics_a1c_dm(x, unlist(f.pROC.cutoff(x,"a1c",dx))) %>%     mutate(Stat="a1c",Cohort=co,Dx=dx)
x.metric.min.SBP <- calculate_metrics_two_dm(x, unlist(f.pROC.cutoff(x,"Pred.MIN",dx)) )%>% mutate(Stat="Pred.MIN",Cohort=co,Dx=dx)

x <- office_test.BMI %>% filter(a1c<6.5)
x$PDM <- as.factor(x$two >= 140 & x$two < 200)
x$DM <- as.factor(x$two >= 200)
co <- "BMI>30"
dx <- "DM"
x.metric.a1c.BMI<- calculate_metrics_a1c_dm(x, unlist(f.pROC.cutoff(x,"a1c",dx))) %>%     mutate(Stat="a1c",Cohort=co,Dx=dx)
x.metric.min.BMI <- calculate_metrics_two_dm(x, unlist(f.pROC.cutoff(x,"Pred.MIN",dx)) )%>% mutate(Stat="Pred.MIN",Cohort=co,Dx=dx)

# 
# 
# 
# 
# x <- office_test.
# x$PDM <- as.factor(x$two >= 140 & x$two < 200)
# x$DM <- as.factor(x$two >= 200)
# co <- ""
# dx <- "DM"
# x.metric.a1c. <- calculate_metrics(x, f.pROC.cutoff(x,"a1c",dx)) %>%     mutate(Stat="a1c",Cohort=co,Dx=dx)
# x.metric.min. <- calculate_metrics(x, f.pROC.cutoff(x,"Pred.MIN",dx)) %>% mutate(Stat="Pred.MIN",Cohort=co,Dx=dx)


x.metrics<-bind_rows(
  x.metric.a1c.FIB4,
  x.metric.min.FIB4,
  x.metric.a1c.Age,
  x.metric.min.Age, 
  x.metric.a1c.All,
  x.metric.min.All,
  x.metric.a1c.BMI,
  x.metric.min.BMI, 
  x.metric.a1c.eGFR,
  x.metric.min.eGFR,
  x.metric.a1c.SBP,
  x.metric.min.SBP)


x <- office_test.FIB4 %>% filter(a1c<6.5)
x$PDM <- as.factor(x$two >= 140 & x$two < 200)
x$DM <- as.factor(x$two >= 200)
x.metric.a1c.FIB4 <- calculate_metrics_a1c_pdm(x, unlist(f.pROC.cutoff(x,"a1c","PDM"))) %>%     mutate(Stat="a1c",Cohort="FIB4>2.67",Dx="PDM")
x.metric.min.FIB4 <- calculate_metrics_two_pdm(x, unlist(f.pROC.cutoff(x,"Pred.MIN","PDM"))) %>% mutate(Stat="Pred.MIN",Cohort="FIB4>2.67",Dx="PDM")

x <- office_test.Age %>% filter(a1c<6.5)
x$PDM <- as.factor(x$two >= 140 & x$two < 200)
x$DM <- as.factor(x$two >= 200)
co <- "Age>60"
dx <- "PDM"
x.metric.a1c.Age <- calculate_metrics_a1c_pdm(x, unlist(f.pROC.cutoff(x,"a1c",dx))) %>%     mutate(Stat="a1c",Cohort=co,Dx=dx)
x.metric.min.Age <- calculate_metrics_two_pdm(x, unlist(f.pROC.cutoff(x,"Pred.MIN",dx)) )%>% mutate(Stat="Pred.MIN",Cohort=co,Dx=dx)


x <- office_test.All %>% filter(a1c<6.5)
x$PDM <- as.factor(x$two >= 140 & x$two < 200)
x$DM <- as.factor(x$two >= 200)
co <- "All"
dx <- "PDM"
x.metric.a1c.All <- calculate_metrics_a1c_pdm(x, unlist(f.pROC.cutoff(x,"a1c",dx))) %>%     mutate(Stat="a1c",Cohort=co,Dx=dx)
x.metric.min.All <- calculate_metrics_two_pdm(x, unlist(f.pROC.cutoff(x,"Pred.MIN",dx)) )%>% mutate(Stat="Pred.MIN",Cohort=co,Dx=dx)

x <- office_test.eGFR %>% filter(a1c<6.5)
x$PDM <- as.factor(x$two >= 140 & x$two < 200)
x$DM <- as.factor(x$two >= 200)
co <- "eGFR<60"
dx <- "PDM"
x.metric.a1c.eGFR<- calculate_metrics_a1c_pdm(x, unlist(f.pROC.cutoff(x,"a1c",dx))) %>%     mutate(Stat="a1c",Cohort=co,Dx=dx)
x.metric.min.eGFR <- calculate_metrics_two_pdm(x, unlist(f.pROC.cutoff(x,"Pred.MIN",dx)) )%>% mutate(Stat="Pred.MIN",Cohort=co,Dx=dx)

x <- office_test.SBP %>% filter(a1c<6.5)
x$PDM <- as.factor(x$two >= 140 & x$two < 200)
x$DM <- as.factor(x$two >= 200)
co <- "SBP>140"
dx <- "PDM"
x.metric.a1c.SBP<- calculate_metrics_a1c_pdm(x, unlist(f.pROC.cutoff(x,"a1c",dx))) %>%     mutate(Stat="a1c",Cohort=co,Dx=dx)
x.metric.min.SBP <- calculate_metrics_two_pdm(x, unlist(f.pROC.cutoff(x,"Pred.MIN",dx)) )%>% mutate(Stat="Pred.MIN",Cohort=co,Dx=dx)

x <- office_test.BMI %>% filter(a1c<6.5)
x$PDM <- as.factor(x$two >= 140 & x$two < 200)
x$DM <- as.factor(x$two >= 200)
co <- "BMI>30"
dx <- "PDM"
x.metric.a1c.BMI<- calculate_metrics_a1c_pdm(x, unlist(f.pROC.cutoff(x,"a1c",dx))) %>%     mutate(Stat="a1c",Cohort=co,Dx=dx)
x.metric.min.BMI <- calculate_metrics_two_pdm(x, unlist(f.pROC.cutoff(x,"Pred.MIN",dx)) )%>% mutate(Stat="Pred.MIN",Cohort=co,Dx=dx)

# 
x.metrics <- bind_rows(  x.metrics,
  x.metric.a1c.FIB4,
  x.metric.min.FIB4,
  x.metric.a1c.Age,
  x.metric.min.Age, 
  x.metric.a1c.All,
  x.metric.min.All,
  x.metric.a1c.BMI,
  x.metric.min.BMI, 
  x.metric.a1c.eGFR,
  x.metric.min.eGFR,
  x.metric.a1c.SBP,
  x.metric.min.SBP)


plot.metrics.pdm <- x.metrics %>%  filter(Dx=="PDM") %>% group_by(Cohort,Stat,Dx) %>% summarise(Cohort=Cohort,Stat=Stat,Dx=Dx,Observed=TP+FP,Expected=TP+FN) %>% 
  pivot_longer(-c(Cohort,Stat,Dx),names_to = "Variable",values_to = "Value")  %>%  ggplot() + geom_col(aes(x=Stat,y=Value,fill=Variable),position="dodge") + facet_wrap(~Cohort,scales = 'free') + labs(title="Pre-Diabetes Diagnosis") + scale_fill_discrete(label=c("Expected (TP+FN)","Observed (TP+FP)"))

plot.metrics.dm <- x.metrics %>%  filter(Dx=="DM") %>% group_by(Cohort,Stat,Dx) %>% summarise(Cohort=Cohort,Stat=Stat,Dx=Dx,Observed=TP+FP,Expected=TP+FN) %>% 
  pivot_longer(-c(Cohort,Stat,Dx),names_to = "Variable",values_to = "Value")   %>%  ggplot() + geom_col(aes(x=Stat,y=Value,fill=Variable),position="dodge") + facet_wrap(~Cohort,scales="free") + labs(title="Diabetes Diagnosis") + scale_fill_discrete(label=c("Expected (TP+FN)","Observed (TP+FP)"))

legend2 <- cowplot::get_legend(plot.metrics.dm + theme(legend.direction = "horizontal" ))

grid.arrange(nrow=2,heights=c(3,0.2),
arrangeGrob(ncol=2,
            plot.metrics.pdm + theme(legend.position="none"),
            plot.metrics.dm + theme(legend.position="none")),
legend2
)
# 
# bind_rows(
#   x.metric.a1c.FIB4,
#   x.metric.min.FIB4,
#   x.metric.a1c.Age,
#   x.metric.min.Age 
# ) %>% ggplot() +  
#   geom_col(aes(x=Stat,y=TP+FP),fill='red',position=position_nudge(x=0.5)) + 
#   geom_col(aes(x=Stat,y=TP+FN),fill='blue',position=position_nudge(x=-0.5)) + facet_grid(Cohort ~ Stat,scales="free")  
  

```


```{r}

plot.metrics.pdm <- x.metrics %>%  filter(Dx=="PDM") %>% filter(Cohort=="All") %>% group_by(Cohort,Stat,Dx) %>% summarise(Cohort=Cohort,Stat=Stat,Dx=Dx,TP=TP,FP=FP,FN=FN,TN=TN) %>% 
  pivot_longer(-c(Cohort,Stat,Dx),names_to = "Variable",values_to = "Value")  %>%  ggplot() + geom_col(aes(x=Stat,y=Value,fill=Variable),position="dodge") + facet_wrap(~Cohort,scales = 'free') + labs(title="Pre-Diabetes Diagnosis") #+ scale_fill_discrete(label=c("Expected (TP+FN)","Observed (TP+FP)"))

plot.metrics.dm <- x.metrics %>%  filter(Dx=="DM") %>% filter(Cohort=="All")%>% group_by(Cohort,Stat,Dx) %>% summarise(Cohort=Cohort,Stat=Stat,Dx=Dx,TP=TP,FP=FP,FN=FN,TN=TN) %>% 
  pivot_longer(-c(Cohort,Stat,Dx),names_to = "Variable",values_to = "Value")   %>%  ggplot() + geom_col(aes(x=Stat,y=Value,fill=Variable),position="dodge") + facet_wrap(~Cohort,scales="free") + labs(title="Diabetes Diagnosis") #+ scale_fill_discrete(label=c("Expected (TP+FN)","Observed (TP+FP)"))

legend2 <- get_legend(plot.metrics.dm + theme(legend.direction = "horizontal" ))

grid.arrange(nrow=2,heights=c(3,0.2),
arrangeGrob(ncol=2,
            plot.metrics.pdm + theme(legend.position="none"),
            plot.metrics.dm + theme(legend.position="none")),
legend2
)




plot.metrics.pdm <- x.metrics %>%  filter(Dx=="PDM") %>% group_by(Cohort,Stat,Dx) %>% summarise(Cohort=Cohort,Stat=Stat,Dx=Dx,TP=TP,FP=FP,FN=FN,TN=TN) %>% 
  pivot_longer(-c(Cohort,Stat,Dx),names_to = "Variable",values_to = "Value")  %>%  ggplot() + geom_col(aes(x=Stat,y=Value,fill=Variable),position="dodge") + facet_wrap(~Cohort,scales = 'free') + labs(title="Pre-Diabetes Diagnosis") #+ scale_fill_discrete(label=c("Expected (TP+FN)","Observed (TP+FP)"))

plot.metrics.dm <- x.metrics %>%  filter(Dx=="DM") %>% group_by(Cohort,Stat,Dx) %>% summarise(Cohort=Cohort,Stat=Stat,Dx=Dx,TP=TP,FP=FP,FN=FN,TN=TN) %>% 
  pivot_longer(-c(Cohort,Stat,Dx),names_to = "Variable",values_to = "Value")   %>%  ggplot() + geom_col(aes(x=Stat,y=Value,fill=Variable),position="dodge") + facet_wrap(~Cohort,scales="free") + labs(title="Diabetes Diagnosis") #+ scale_fill_discrete(label=c("Expected (TP+FN)","Observed (TP+FP)"))

legend2 <- get_legend(plot.metrics.dm + theme(legend.direction = "horizontal" ))

grid.arrange(nrow=2,heights=c(3,0.2),
arrangeGrob(ncol=2,
            plot.metrics.pdm + theme(legend.position="none"),
            plot.metrics.dm + theme(legend.position="none")),
legend2
)

```

