---
title: "1999-04 Mortality"
output: html_document
date: "2025-07-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(xgboost)
library(caret)
library(dplyr)
library(nhanesA)
library(pROC)
library(data.table)
library(purrr)
library(haven)
library(knitr)

```


```{r}

f.align_columns <- function(ma, mb) {
  ma_columns <- colnames(ma)
  mb_columns <- colnames(mb)
  
  missing_columns <- setdiff(ma_columns, mb_columns)
  
  for (col in missing_columns) {
    zero_col <- matrix(0, nrow = nrow(mb), ncol = 1)
    colnames(zero_col) <- col
    mb <- cbind(mb, zero_col)
  }
  
  mb <- mb[, ma_columns, drop = FALSE]
  
  return(mb)
}


f.just.prepare.data <- function(clean.output, config) {
  train_processed <- rlang::as_function(config$mutate_expr)(clean.output$office_train)
  train_X <- makeX(train_processed)
  dtrain <- xgb.DMatrix(data = train_X, label = clean.output$label.train)

  test_processed <- rlang::as_function(config$mutate_expr)(clean.output$office_test)
  test_X <- makeX(test_processed)
  test_X <- f.align_columns(train_X, test_X)
  dtest <- xgb.DMatrix(data = test_X)

  weight.sample.train.norm <- clean.output$weight.sample.train / sum(clean.output$weight.sample.train)
  return(list(train_X, dtrain, test_X, dtest, weight.sample.train.norm))
}


f.clean.data.for.xgboost <- function(df) {
  df_n <- sapply(df, function(x) sum(!is.na(x)))
  keep <- names(df_n[df_n / nrow(df) > 0.88])
  keep <- unique(c(keep, 'two', 'sample.ogtt.weight', 'Year', 'SEQN', 'fpg', 'a1c'))
  train <- df %>% select(all_of(keep)) %>% filter(Year < 2005) %>% drop_na(sample.ogtt.weight)
  test  <- df %>% select(all_of(keep)) %>% filter(Year >= 2005 & Year <= 2006)
  test$two <- NA
  list(
    year.train         = train$Year,
    year.test          = test$Year,
    label.train        = as.integer(train$two) - 1,
    label.test         = as.integer(test$two) - 1,
    id.train           = train$SEQN,
    id.test            = test$SEQN,
    weight.sample.train= train$sample.ogtt.weight,
    weight.sample.test = test$sample.ogtt.weight,
    office_train       = train %>% select(-c(sample.ogtt.weight, Year, two)),
    office_test        = test  %>% select(-c(sample.ogtt.weight, Year, two))
  )
}

```

```{r}

# Function to train and predict for each model
f.run_xgb_model <- function(clean.output, config) {
  
  year.train = clean.output$year.train
  year.test = clean.output$year.test
  label_train = clean.output$label.train
  label_test = clean.output$label.test
  weight.sample.train = clean.output$weight.sample.train
  weight.sample.test = clean.output$weight.sample.test
  train_data = clean.output$office_train
  test_data = clean.output$office_test
  
  # Prepare training data
  train_processed <- rlang::as_function(config$mutate_expr)(train_data)
  train_X <- makeX(train_processed)
  dtrain <- xgb.DMatrix(data = train_X, label = label_train)

  # Prepare testing data
  test_processed <- rlang::as_function(config$mutate_expr)(test_data)
  test_X <- makeX(test_processed)
  test_X <- f.align_columns(train_X, test_X)
  test_X <- test_X[, colnames(train_X)]
  dtest <- xgb.DMatrix(data = test_X, label = label_test)

  
  tune_grid.mod <<- expand.grid(
  nrounds = c(1500,2000),
  eta = c(0.01,0.05),
  max_depth = c(6,8),
  subsample = c(0.6,0.8),
  colsample_bytree = c(0.6,0.8),# bounded at maximum 1
  min_child_weight = c(1),
  gamma = c(0)
) 

  train_control <- trainControl(method = "cv", 
                              number = 5,
                              verboseIter = TRUE)
  
  weight.sample.train.norm <- weight.sample.train / sum(weight.sample.train)
  # Train model
  xgb_tuned <- caret::train(
    method = "xgbTree",
    x = train_X,
    y = label_train,
    tuneLength = 1,
    trControl = train_control,
    tuneGrid = tune_grid.mod,
    metric = "RMSE",
    weights = weight.sample.train.norm,
    verbose = TRUE
  )

  xgb_model <- xgboost::xgb.train(params = xgb_tuned$bestTune %>% flatten(), dtrain, nrounds = 2000)

  # Make predictions
  pred <- predict(xgb_model, dtest)

  return(list(pred = pred, model = xgb_model))
}
```


```{r}
# data for 1999 

demo_1999 <- nhanes("DEMO", 1999)
bmx_1999 <- nhanesA::nhanes("BMX", 1999)
bpx_1999 <-nhanes("BPX", 1999)
mcq_1999 <- nhanes("MCQ", 1999)
diq_1999 <- nhanes("DIQ", 1999)
l10_1999 <- nhanes("LAB10", 1999)
l10am_1999 <- nhanes("LAB10AM", 1999)
lb25_1999 <- nhanes("LAB25", 1999)
lb18_1999 <- nhanes("LAB18", 1999)
bpq_1999 <- nhanes("BPQ", 1999)

bpx_1999$BPXSY <- rowMeans(
  bpx_1999[, c("BPXSY1", "BPXSY2", "BPXSY3")],
  na.rm = TRUE
)

bpx_1999$BPXDI <- rowMeans(
  bpx_1999[, c("BPXDI1", "BPXDI2", "BPXDI3")],
  na.rm = TRUE
)

vars.all.1999 <- c(
  "SEQN","RIDAGEYR","RIAGENDR","BPXPLS","BPXSY","BPXDI","BMXHT","BMXWT","BMXWAIST",
  "BMXARMC","BPXPULS","BPQ020",
  #"DIQ160","SLD012","DIQ180",
  "MCQ080","MCQ092",
  #"SLQ050",
  "DIQ010",
  #"DIQ170",
  "MCQ250C","MCQ010","MCQ053","LBXNEPCT","LBXLYPCT","LBXMCVSI",
  "LBXMOPCT","LBXEOPCT","LBXPLTSI","LBXMCHSI","LBXMPSI","LBXRBCSI","LBXHGB","LBXMC",
  "LBXBAPCT","LBXWBCSI","LBXRDW","LBXSNASI","LBXSKSI","LBXSCLSI","LBXSC3SI","LBXSBU","LBXGLU",
  "LBXSCR","LBXSCA","LBXSTP","LBXSTB","LBXSAL","LBXSASSI","LBXSATSI","LBXSAPSI","LBXGH"
)

df_1999 <- reduce(
  list(demo_1999, bmx_1999, bpx_1999, mcq_1999, diq_1999, l10_1999, l10am_1999, lb25_1999, lb18_1999, bpq_1999),
  full_join,
  by = "SEQN"
) %>%
  select(any_of(vars.all.1999)) %>%
  mutate(Year = 1999) 

```


```{r}

# importing, adjusting, cleaning data

demo_2001 <- nhanesA::nhanes("DEMO", 2001)
bpx_2001 <- nhanesA::nhanes("BPX_B", 2001)
bmx_2001 <- nhanesA::nhanes("BMX_B", 2001)
l10_2001 <- nhanesA::nhanes("L10_B", 2001)
l10am_2001 <- nhanesA::nhanes("L10AM_B", 2001)
l25_2001 <- nhanesA::nhanes("L25_B", 2001)
l40_2001 <- nhanesA::nhanes("L40_B", 2001)
l40_2_2001 <- nhanesA::nhanes("L40_2_B", 2001)
bpq_2001 <- nhanesA::nhanes("BPQ_B", 2001)
diq_2001 <- nhanesA::nhanes("DIQ_B", 2001)
mcq_2001 <- nhanesA::nhanes("MCQ_B", 2001)

bpx_2001$BPXSY <- rowMeans(
  bpx_2001[, c("BPXSY1", "BPXSY2", "BPXSY3")],
  na.rm = TRUE
)

bpx_2001$BPXDI <- rowMeans(
  bpx_2001[, c("BPXDI1", "BPXDI2", "BPXDI3")],
  na.rm = TRUE
)

vars.all.2001 <- c(
  "SEQN","RIDAGEYR","RIAGENDR","BPXPLS","BPXSY","BPXDI","BMXHT","BMXWT","BMXWAIST",
  "BMXARMC","BPXPULS","BPQ020", "MCQ080","MCQ092","DIQ010", "MCQ250C","MCQ010",
  "MCQ053","LBXNEPCT","LBXLYPCT","LBXMCVSI", "LBXMOPCT","LBXEOPCT","LBXPLTSI","LBXMCHSI",
  "LBXMPSI","LBXRBCSI","LBXHGB","LBXMC","LBXBAPCT","LBXWBCSI","LBXRDW", "LBXGLU",
  "LBXSNASI","LBXSKSI","LBXSCLSI","LBXSC3SI","LBXSBU","LBDSCR","LBXSCA","LBXSTP","LBDSTB",
  "LBXSAL","LBXSASSI","LBXSATSI","LB2SAPSI","LBXGH"
)

df_2001 <- list(
  demo_2001,
  bpx_2001,  bmx_2001,  l10_2001, l10am_2001, l25_2001, l40_2001,
  l40_2_2001, bpq_2001,  diq_2001,  mcq_2001
) %>%
  reduce(full_join, by = "SEQN")  %>%
  select(any_of(vars.all.2001)) %>% 
  mutate(Year = 2001)

if ("LBDSCR" %in% names(df_2001)) {
  df_2001 <- df_2001 %>% rename(LBXSCR = LBDSCR)
}
if ("LBDSTB" %in% names(df_2001)) {
  df_2001 <- df_2001 %>% rename(LBXSTB = LBDSTB)
}
if ("LB2SAPSI" %in% names(df_2001)) {
  df_2001 <- df_2001 %>% rename(LBXSAPSI = LB2SAPSI)
}

demo_2003 <- nhanesA::nhanes("DEMO", 2003)
bpx_2003 <- nhanesA::nhanes("BPX_C", 2003)
bmx_2003 <- nhanesA::nhanes("BMX_C", 2003)
l10_2003 <- nhanesA::nhanes("L10_C", 2003)
l10am_2003 <- nhanesA::nhanes("L10AM_B", 2003)
l25_2003 <- nhanesA::nhanes("L25_C", 2003)
l40_2003 <- nhanesA::nhanes("L40_C", 2003)
bpq_2003 <- nhanesA::nhanes("BPQ_C", 2003)
diq_2003 <- nhanesA::nhanes("DIQ_C", 2003)
mcq_2003 <- nhanesA::nhanes("MCQ_C", 2003)

bpx_2003$BPXSY <- rowMeans(
  bpx_2003[, c("BPXSY1", "BPXSY2", "BPXSY3")],
  na.rm = TRUE
)

bpx_2003$BPXDI <- rowMeans(
  bpx_2003[, c("BPXDI1", "BPXDI2", "BPXDI3")],
  na.rm = TRUE
)

vars.all.2003 <- c(
  "SEQN","RIDAGEYR","RIAGENDR","BPXPLS","BPXSY","BPXDI","BMXHT","BMXWT","BMXWAIST",
  "BMXARMC","BPXPULS","BPQ020",
  #"DIQ160","SLD012","DIQ180",
  "MCQ080","MCQ092",
  #"SLQ050",
  "DIQ010",
  #"DIQ170",
  "MCQ250C", "MCQ010","MCQ053","LBXNEPCT","LBXLYPCT","LBXMCVSI",
  "LBXMOPCT","LBXEOPCT","LBXPLTSI","LBXMCHSI","LBXMPSI","LBXRBCSI","LBXHGB","LBXMC",
  "LBXBAPCT","LBXWBCSI","LBXRDW","LBXSNASI","LBXSKSI","LBXSCLSI","LBXSC3SI","LBXSBU", "LBXGLU",
  "LBXSCR","LBXSCA","LBXSTP","LBXSTB","LBXSAL","LBXSASSI","LBXSATSI","LBXSAPSI","LBXGH"
)

df_2003 <- list(
  demo_2003,
  bpx_2003,  bmx_2003,  l10_2003, l10am_2003, l25_2003, l40_2003, 
  bpq_2003,  diq_2003,  mcq_2003
) %>%
  reduce(full_join, by = "SEQN")  %>%
  select(any_of(vars.all.2003)) %>% 
  mutate(Year = 2003)

```


```{r}
unique_columns <- unique(c(names(df_1999), names(df_2001), names(df_2003)))


df_1999_final <- df_1999 %>% select(any_of(unique_columns))
df_2001_final <- df_2001 %>% select(any_of(unique_columns))
df_2003_final <- df_2003 %>% select(any_of(unique_columns))

df_combined <- bind_rows(df_1999_final, df_2001_final, df_2003_final)

saveRDS(df_combined, "df_combined.rds")

```



```{r}
df_combined %>% select(LBXGLU,Year) %>% mutate(Exist=!is.na(LBXGLU)) %>% select(Exist,Year)%>% table()
```


```{r}

# cleaning standard of care vars DONT DELETE

soc_vars <- c(
  "SEQN","Year", "RIDAGEYR","RIAGENDR","BPXPLS","SBP","DBP","BMXHT","BMXWT","BMXWAIST","BMXARMC","BPXPULS",
  "BPQ020","DIQ160","SLD012","DIQ180","MCQ080","MCQ092","SLQ050",
  "DIQ010", "DIQ170","MCQ300B","MCQ010","MCQ053","LBXNEPCT","LBXLYPCT","LBXMCVSI",
  "LBXMOPCT","LBXEOPCT","LBXPLTSI","LBXMCHSI","LBXMPSI","LBXRBCSI","LBXHGB","LBXMC","LBXBAPCT","LBXWBCSI","LBXRDW",
  "LBXSNASI","LBXSKSI","LBXSCLSI","LBXSC3SI","LBXSBU","LBXSCR","LBXSCA","LBXSTP","LBXSTB","LBXSAL","LBXSASSI","LBXSATSI","LBXSAPSI","LBXGH")
  

vars.all <- c(
  "SEQN","RIDAGEYR","RIAGENDR","BPXPLS","BPXSY","BPXDI","BMXHT","BMXWT","BMXWAIST",
  "BMXARMC","BPXPULS","BPQ020","DIQ160","SLD012","DIQ180","MCQ080","MCQ092","SLQ050",
  "DIQ010","DIQ170","MCQ300B","MCQ010","MCQ053","LBXNEPCT","LBXLYPCT","LBXMCVSI",
  "LBXMOPCT","LBXEOPCT","LBXPLTSI","LBXMCHSI","LBXMPSI","LBXRBCSI","LBXHGB","LBXMC",
  "LBXBAPCT","LBXWBCSI","LBXRDW","LBXSNASI","LBXSKSI","LBXSCLSI","LBXSC3SI","LBXSBU",
  "LBXSCR","LBXSCA","LBXSTP","LBXSTB","LBXSAL","LBXSASSI","LBXSATSI","LBXSAPSI","LBXGH"
)
```

```{r}
knitr::purl(input = "O", output = "your_script.R")

```


